// Transcribed from the user-supplied 2024 PDF. See docs/catalog-import for page coverage.
// Generated by scripts/catalog_data.py; preserve source order and values.
import part001 from './imported-data/part-001.js';
import part002 from './imported-data/part-002.js';
import part003 from './imported-data/part-003.js';
import part004 from './imported-data/part-004.js';
import part005 from './imported-data/part-005.js';
import part006 from './imported-data/part-006.js';
import part007 from './imported-data/part-007.js';
import part008 from './imported-data/part-008.js';
import part009 from './imported-data/part-009.js';
import part010 from './imported-data/part-010.js';
import part011 from './imported-data/part-011.js';
import part012 from './imported-data/part-012.js';
import part013 from './imported-data/part-013.js';
import part014 from './imported-data/part-014.js';
import part015 from './imported-data/part-015.js';
import part016 from './imported-data/part-016.js';
import part017 from './imported-data/part-017.js';
import part018 from './imported-data/part-018.js';
import part019 from './imported-data/part-019.js';
import part020 from './imported-data/part-020.js';
import part021 from './imported-data/part-021.js';
import part022 from './imported-data/part-022.js';
import part023 from './imported-data/part-023.js';
import part024 from './imported-data/part-024.js';
import part025 from './imported-data/part-025.js';

export const importedProducts = [
  ...part001,
  ...part002,
  ...part003,
  ...part004,
  ...part005,
  ...part006,
  ...part007,
  ...part008,
  ...part009,
  ...part010,
  ...part011,
  ...part012,
  ...part013,
  ...part014,
  ...part015,
  ...part016,
  ...part017,
  ...part018,
  ...part019,
  ...part020,
  ...part021,
  ...part022,
  ...part023,
  ...part024,
  ...part025,
];
export { default as catalogImport } from './imported-data/metadata.js';
