// Reference records transcribed from official public catalog pages.
// No price, availability, order-ready SKU or current certification is asserted.
export const officialProducts = [
  {
    "id": "tmg-400",
    "sku": "ТМГ-400/10(6)-0,4",
    "category": "transformers",
    "name": "ТМГ-400/10(6)-0,4",
    "power": 400,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГ.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГ"
  },
  {
    "id": "tmg-630",
    "sku": "ТМГ-630/10(6)-0,4",
    "category": "transformers",
    "name": "ТМГ-630/10(6)-0,4",
    "power": 630,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГ.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГ"
  },
  {
    "id": "tmg-1000",
    "sku": "ТМГ-1000/10(6)-0,4",
    "category": "transformers",
    "name": "ТМГ-1000/10(6)-0,4",
    "power": 1000,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГ.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГ"
  },
  {
    "id": "tmg-2500",
    "sku": "ТМГ-2500/10(6)-0,4",
    "category": "transformers",
    "name": "ТМГ-2500/10(6)-0,4",
    "power": 2500,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГ.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГ"
  },
  {
    "id": "tmgs-63",
    "sku": "ТМГС-63",
    "category": "transformers",
    "name": "ТМГС-63",
    "power": 63,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГС.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgs-6-10-kv-2-2",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГС"
  },
  {
    "id": "tmgs-160",
    "sku": "ТМГС-160",
    "category": "transformers",
    "name": "ТМГС-160",
    "power": 160,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГС.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgs-6-10-kv-2-2",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГС"
  },
  {
    "id": "tmgf-630",
    "sku": "ТМГФ-630",
    "category": "transformers",
    "name": "ТМГФ-630",
    "power": 630,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГФ.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgf-6-10-kv",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГФ"
  },
  {
    "id": "tmgf-1600",
    "sku": "ТМГФ-1600",
    "category": "transformers",
    "name": "ТМГФ-1600",
    "power": 1600,
    "voltage": "6/10 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМГФ.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgf-6-10-kv",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМГФ"
  },
  {
    "id": "tmeg-250",
    "sku": "ТМЭГ-250",
    "category": "transformers",
    "name": "ТМЭГ-250",
    "power": 250,
    "voltage": "6/6,3/10/10,5 → 0,4",
    "cooling": "Масляное",
    "installation": null,
    "source": "official",
    "description": "Трёхфазный распределительный трансформатор серии ТМЭГ.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «УТЗ»",
      "ТОО «ПЭТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Масляные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tmeg",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «УТЗ» · ТОО «ПЭТЗ»",
    "series": "ТМЭГ"
  },
  {
    "id": "tsl-630",
    "sku": "ТСЛ-630",
    "category": "transformers",
    "name": "ТСЛ-630",
    "power": 630,
    "voltage": "6–10 → 0,4",
    "cooling": "Сухое",
    "installation": null,
    "source": "official",
    "description": "Сухой трёхфазный трансформатор серии ТСЛ(З).",
    "manufacturers": [
      "АО «КТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Сухие трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tsl-z",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ»",
    "series": "ТСЛ"
  },
  {
    "id": "tsl-1600",
    "sku": "ТСЛ-1600",
    "category": "transformers",
    "name": "ТСЛ-1600",
    "power": 1600,
    "voltage": "6–10 → 0,4",
    "cooling": "Сухое",
    "installation": null,
    "source": "official",
    "description": "Сухой трёхфазный трансформатор серии ТСЛ(З).",
    "manufacturers": [
      "АО «КТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Сухие трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/tsl-z",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ»",
    "series": "ТСЛ"
  },
  {
    "id": "ntmi-6",
    "sku": "НТМИ-6",
    "category": "transformers",
    "name": "НТМИ-6",
    "power": null,
    "voltage": "6 → 0,1",
    "cooling": null,
    "installation": null,
    "source": "official",
    "description": "Трёхфазный измерительный трансформатор; основная вторичная обмотка 0,1 кВ.",
    "manufacturers": [
      "АО «КТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Измерительные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/ntmi",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ»",
    "series": "НТМИ"
  },
  {
    "id": "ntmi-10",
    "sku": "НТМИ-10",
    "category": "transformers",
    "name": "НТМИ-10",
    "power": null,
    "voltage": "10 → 0,1",
    "cooling": null,
    "installation": null,
    "source": "official",
    "description": "Трёхфазный измерительный трансформатор; основная вторичная обмотка 0,1 кВ.",
    "manufacturers": [
      "АО «КТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Измерительные трансформаторы",
    "sourceUrl": "https://alageum.com/ru/katalog/transformatory/ntmi",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ»",
    "series": "НТМИ"
  },
  {
    "id": "pktp-400",
    "sku": "ПКТП-400",
    "category": "substations",
    "name": "ПКТП-400",
    "power": 400,
    "voltage": "6/10 → 0,4",
    "cooling": null,
    "installation": "Перевозимая",
    "source": "official",
    "description": "Комплектная перевозимая трансформаторная подстанция, частота 50 Гц.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «АЭМЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Трансформаторные подстанции",
    "sourceUrl": "https://alageum.com/ru/katalog/shkafy-upravleniya/pktp",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «АЭМЗ»",
    "series": "ПКТП"
  },
  {
    "id": "pktp-1000",
    "sku": "ПКТП-1000",
    "category": "substations",
    "name": "ПКТП-1000",
    "power": 1000,
    "voltage": "6/10 → 0,4",
    "cooling": null,
    "installation": "Перевозимая",
    "source": "official",
    "description": "Комплектная перевозимая трансформаторная подстанция, частота 50 Гц.",
    "manufacturers": [
      "АО «КТЗ»",
      "ТОО «АЭМЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Трансформаторные подстанции",
    "sourceUrl": "https://alageum.com/ru/katalog/shkafy-upravleniya/pktp",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ» · ТОО «АЭМЗ»",
    "series": "ПКТП"
  },
  {
    "id": "rlnd",
    "sku": "РЛНД",
    "category": "switchgear",
    "name": "РЛНД",
    "power": null,
    "voltage": "10",
    "cooling": null,
    "installation": null,
    "source": "official",
    "description": "Разъединитель: номинальный ток 400, 630 или 1000 А; наибольшее рабочее напряжение 12 кВ.",
    "manufacturers": [
      "АО «КТЗ»"
    ],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-reference",
    "subtype": "Разъединители",
    "sourceUrl": "https://alageum.com/ru/katalog/elektrotekhnicheskoe-oborudovanie/rlnd",
    "sourceCheckedAt": "2026-09-30",
    "manufacturer": "АО «КТЗ»",
    "series": "РЛНД"
  },
  {
    "id": "kso-366",
    "sku": "КСО-366",
    "name": "КСО-366",
    "category": "switchgear",
    "subtype": "Высоковольтное оборудование",
    "power": null,
    "voltage": null,
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceUrl": "https://alageum.com/ru/katalog/shkafy-upravleniya/content/vysokovoltnoe-oborudovanie",
    "sourceCheckedAt": "2026-09-30",
    "description": "Серия КСО-366 представлена в разделе высоковольтного оборудования официального каталога. Техническое исполнение и производитель конкретной позиции требуют уточнения.",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-family",
    "series": "КСО-366"
  },
  {
    "id": "kso-292",
    "sku": "КСО-292",
    "name": "КСО-292",
    "category": "switchgear",
    "subtype": "Высоковольтное оборудование",
    "power": null,
    "voltage": null,
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceUrl": "https://alageum.com/ru/katalog/shkafy-upravleniya/content/vysokovoltnoe-oborudovanie",
    "sourceCheckedAt": "2026-09-30",
    "description": "Серия КСО-292 представлена в разделе высоковольтного оборудования официального каталога. Техническое исполнение и производитель конкретной позиции требуют уточнения.",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-family",
    "series": "КСО-292"
  },
  {
    "id": "kso-2-10",
    "sku": "КСО-2-10",
    "name": "КСО-2-10",
    "category": "switchgear",
    "subtype": "Высоковольтное оборудование",
    "power": null,
    "voltage": null,
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceUrl": "https://alageum.com/ru/katalog/shkafy-upravleniya/content/vysokovoltnoe-oborudovanie",
    "sourceCheckedAt": "2026-09-30",
    "description": "Серия КСО-2-10 представлена в разделе высоковольтного оборудования официального каталога. Техническое исполнение и производитель конкретной позиции требуют уточнения.",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "documentCount": 0,
    "recordType": "official-catalog-family",
    "series": "КСО-2-10"
  }
];
