// Generated by scripts/catalog_data.py; preserve source order and values.
const data = [
  {
    "id": "cat-ukzv-v001",
    "sku": "УКЗВ-6(10)В-1,2-2У1",
    "name": "УКЗВ-6(10)В-1,2-2У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 10,
    "voltage": "6(10) → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzv.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗВ-6(10)В-1,2-2У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Воздушный или кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzv",
    "familyName": "УКЗВ",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzv-v002",
    "sku": "УКЗВ-6(10)К-1,2-2У1",
    "name": "УКЗВ-6(10)К-1,2-2У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 10,
    "voltage": "6(10) → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzv.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗВ-6(10)К-1,2-2У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Воздушный или кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzv",
    "familyName": "УКЗВ",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzv-v003",
    "sku": "УКЗВ-6(10)В-1,2-4У1",
    "name": "УКЗВ-6(10)В-1,2-4У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 10,
    "voltage": "6(10) → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzv.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗВ-6(10)В-1,2-4У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Воздушный или кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "4",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzv",
    "familyName": "УКЗВ",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "4",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzv-v004",
    "sku": "УКЗВ-6(10)К-1,2-4У1",
    "name": "УКЗВ-6(10)К-1,2-4У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 10,
    "voltage": "6(10) → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzv.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗВ-6(10)К-1,2-4У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Воздушный или кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "4",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzv",
    "familyName": "УКЗВ",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "4",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzv-v005",
    "sku": "УКЗВ-6(10)В-3-2У1",
    "name": "УКЗВ-6(10)В-3-2У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 10,
    "voltage": "6(10) → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzv.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗВ-6(10)В-3-2У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Воздушный или кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "3",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzv",
    "familyName": "УКЗВ",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "3",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzv-v006",
    "sku": "УКЗВ-6(10)К-3-2У1",
    "name": "УКЗВ-6(10)К-3-2У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 10,
    "voltage": "6(10) → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzv.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗВ-6(10)К-3-2У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Воздушный или кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "3",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzv",
    "familyName": "УКЗВ",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "3",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzv-v007",
    "sku": "УКЗВ-6(10)К-5-1У1",
    "name": "УКЗВ-6(10)К-5-1У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 10,
    "voltage": "6(10) → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzv.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗВ-6(10)К-5-1У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Воздушный или кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "5",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "1",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzv",
    "familyName": "УКЗВ",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "5",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "1",
        "unit": "шт.",
        "page": 93
      },
      {
        "label": "Мощность трансформатора",
        "value": "10",
        "unit": "кВА",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Напряжение трансформатора НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzn",
    "sku": "УКЗН",
    "name": "Устройство катодной защиты УКЗН",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗН",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzn.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      }
    ],
    "notes": [
      "Номинал питающей сети для УКЗН в таблице 0,23 кВ, при этом обозначения исполнений содержат 0,22. Сохранено как в источнике."
    ],
    "variantIds": [
      "cat-ukzn-v001",
      "cat-ukzn-v002",
      "cat-ukzn-v003",
      "cat-ukzn-v004"
    ],
    "configurations": []
  },
  {
    "id": "cat-ukzn-v001",
    "sku": "УКЗН-0,22-1,2-2У1",
    "name": "УКЗН-0,22-1,2-2У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗН",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzn.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗН-0,22-1,2-2У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      }
    ],
    "notes": [
      "Номинал питающей сети для УКЗН в таблице 0,23 кВ, при этом обозначения исполнений содержат 0,22. Сохранено как в источнике."
    ],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzn",
    "familyName": "УКЗН",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzn-v002",
    "sku": "УКЗН-0,22-1,2-4У1",
    "name": "УКЗН-0,22-1,2-4У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗН",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzn.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗН-0,22-1,2-4У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "4",
        "unit": "шт.",
        "page": 93
      }
    ],
    "notes": [
      "Номинал питающей сети для УКЗН в таблице 0,23 кВ, при этом обозначения исполнений содержат 0,22. Сохранено как в источнике."
    ],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzn",
    "familyName": "УКЗН",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "1,2",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "4",
        "unit": "шт.",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzn-v003",
    "sku": "УКЗН-0,22-3-2У1",
    "name": "УКЗН-0,22-3-2У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗН",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzn.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗН-0,22-3-2У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "3",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      }
    ],
    "notes": [
      "Номинал питающей сети для УКЗН в таблице 0,23 кВ, при этом обозначения исполнений содержат 0,22. Сохранено как в источнике."
    ],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzn",
    "familyName": "УКЗН",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "3",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "2",
        "unit": "шт.",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-ukzn-v004",
    "sku": "УКЗН-0,22-5-1У1",
    "name": "УКЗН-0,22-5-1У1",
    "category": "protection",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      93,
      94
    ],
    "series": "УКЗН",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ukzn.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 93,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Распределительное устройство катодной защиты газонефтепроводов и подземных металлических сооружений от почвенной коррозии; автоматическое или ручное регулирование потенциала. Каталожное обозначение (включая печатные шаблоны): УКЗН-0,22-5-1У1. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "0,23",
        "unit": "кВ",
        "page": 93
      },
      {
        "label": "Ввод",
        "value": "Кабельный",
        "unit": "",
        "page": 93
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 93
      },
      {
        "label": "Мощность станции катодной защиты",
        "value": "5",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "1",
        "unit": "шт.",
        "page": 93
      }
    ],
    "notes": [
      "Номинал питающей сети для УКЗН в таблице 0,23 кВ, при этом обозначения исполнений содержат 0,22. Сохранено как в источнике."
    ],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ukzn",
    "familyName": "УКЗН",
    "variantSpecs": [
      {
        "label": "Мощность станции катодной защиты",
        "value": "5",
        "unit": "кВт",
        "page": 93
      },
      {
        "label": "Количество станций",
        "value": "1",
        "unit": "шт.",
        "page": 93
      }
    ]
  },
  {
    "id": "cat-bueskn",
    "sku": "БУЭСКН",
    "name": "Блок управления электродвигателями станков-качалок БУЭСКН",
    "category": "cabinets",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "0,38",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      95
    ],
    "series": "БУЭСКН",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-bueskn.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 95,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Управление, защита от перегрузок и коротких замыканий, аварийное отключение и самозапуск после восстановления питания электродвигателей станков-качалок.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей цепи",
        "value": "380",
        "unit": "В",
        "page": 95
      },
      {
        "label": "Частота",
        "value": "50",
        "unit": "Гц",
        "page": 95
      },
      {
        "label": "Режим работы",
        "value": "Ручной и автоматический",
        "unit": "",
        "page": 95
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 95
      },
      {
        "label": "Габариты В×Ш×Г",
        "value": "800×650×310",
        "unit": "мм",
        "page": 95
      },
      {
        "label": "Масса, не более",
        "value": "60",
        "unit": "кг",
        "page": 95
      }
    ],
    "notes": [
      "Варианты обозначены мощностью из таблицы; полные индивидуальные обозначения заказа не напечатаны."
    ],
    "variantIds": [],
    "configurations": [
      {
        "designation": "5 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "5",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "10",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "7,5 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "7,5",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "16",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "9,0 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "9,0",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "20",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "11 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "11",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "25",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "15 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "15",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "32",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "18,5 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "18,5",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "40",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "22 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "22",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "50",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "30 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "30",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "63",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "40 кВт",
        "page": 95,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "40",
            "unit": "кВт",
            "page": 95
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "80",
            "unit": "А",
            "page": 95
          }
        ],
        "kind": "configuration"
      }
    ]
  },
  {
    "id": "cat-bushk-2m",
    "sku": "БУШК-2М",
    "name": "Блок управления электродвигателями станков-качалок БУШК-2М",
    "category": "cabinets",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "0,38",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      96
    ],
    "series": "БУШК-2М",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-bushk-2m.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 96,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Управление, защита от перегрузок и коротких замыканий, аварийное отключение и самозапуск после восстановления питания электродвигателей станков-качалок.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей цепи",
        "value": "380",
        "unit": "В",
        "page": 96
      },
      {
        "label": "Частота",
        "value": "50",
        "unit": "Гц",
        "page": 96
      },
      {
        "label": "Режим работы",
        "value": "Ручной и автоматический",
        "unit": "",
        "page": 96
      },
      {
        "label": "Климатическое исполнение",
        "value": "У1",
        "unit": "",
        "page": 96
      },
      {
        "label": "Габариты В×Ш×Г",
        "value": "1275×600×300",
        "unit": "мм",
        "page": 96
      },
      {
        "label": "Масса, не более",
        "value": "50",
        "unit": "кг",
        "page": 96
      },
      {
        "label": "Степень защиты",
        "value": "IP44",
        "unit": "",
        "page": 96
      },
      {
        "label": "Температура",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 96
      },
      {
        "label": "Относительная влажность при +20 °C",
        "value": "до 80",
        "unit": "%",
        "page": 96
      },
      {
        "label": "Высота над уровнем моря",
        "value": "до 1000",
        "unit": "м",
        "page": 96
      }
    ],
    "notes": [
      "Варианты обозначены мощностью из таблицы; полные индивидуальные обозначения заказа не напечатаны."
    ],
    "variantIds": [],
    "configurations": [
      {
        "designation": "5 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "5",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "10",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "7,5 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "7,5",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "16",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "9,0 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "9,0",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "20",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "11 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "11",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "25",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "15 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "15",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "32",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "18,5 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "18,5",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "40",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "22 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "22",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "50",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "30 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "30",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "63",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      },
      {
        "designation": "40 кВт",
        "page": 96,
        "specifications": [
          {
            "label": "Мощность управляемого электродвигателя",
            "value": "40",
            "unit": "кВт",
            "page": 96
          },
          {
            "label": "Номинальный ток электродвигателя",
            "value": "80",
            "unit": "А",
            "page": 96
          }
        ],
        "kind": "configuration"
      }
    ]
  },
  {
    "id": "cat-ktpnd",
    "sku": "КТПНД 25–400/6(10)/0,4 кВ У1",
    "name": "Комплектная трансформаторная подстанция для нефтедобычи КТПНД",
    "category": "substations",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": null,
    "voltage": "6(10) → 0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      97
    ],
    "series": "КТПНД 25–400/6(10)/0,4 кВ У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpnd.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 97,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Подстанции наружной установки для промысловых скважин добычи нефти и других промышленных объектов. Ввод ВН воздушный, вывод НН кабельный.",
    "technicalSpecs": [
      {
        "label": "Номинальное напряжение ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 97
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,4",
        "unit": "кВ",
        "page": 97
      },
      {
        "label": "Число отходящих линий",
        "value": "6",
        "unit": "шт.",
        "page": 97
      },
      {
        "label": "Динамическая стойкость к токам КЗ",
        "value": "1,3–15,6",
        "unit": "кА",
        "page": 97
      },
      {
        "label": "Термическая стойкость к токам КЗ",
        "value": "0,9–8,1",
        "unit": "кА",
        "page": 97
      },
      {
        "label": "Количество фидеров",
        "value": "1",
        "unit": "",
        "page": 97
      },
      {
        "label": "Степень защиты",
        "value": "IP55 (по требованию заказчика)",
        "unit": "",
        "page": 97
      },
      {
        "label": "Масса без трансформатора",
        "value": "315",
        "unit": "кг",
        "page": 97
      },
      {
        "label": "Температура",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 97
      }
    ],
    "notes": [
      "В заголовке диапазон до 400 кВА, но таблица содержит только 25–250 кВА. Модель 400 не выдумана. В ячейке тока при 10 кВ для 40 кВА напечатано «2,3,1»; значение не исправлено."
    ],
    "variantIds": [
      "cat-ktpnd-v001",
      "cat-ktpnd-v002",
      "cat-ktpnd-v003",
      "cat-ktpnd-v004",
      "cat-ktpnd-v005",
      "cat-ktpnd-v006"
    ],
    "configurations": []
  },
  {
    "id": "cat-ktpnd-v001",
    "sku": "КТПНД 25",
    "name": "КТПНД 25",
    "category": "substations",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 25,
    "voltage": "6(10) → 0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      97
    ],
    "series": "КТПНД 25–400/6(10)/0,4 кВ У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpnd.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 97,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Подстанции наружной установки для промысловых скважин добычи нефти и других промышленных объектов. Ввод ВН воздушный, вывод НН кабельный. Каталожное обозначение (включая печатные шаблоны): КТПНД 25. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Номинальное напряжение ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 97
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,4",
        "unit": "кВ",
        "page": 97
      },
      {
        "label": "Число отходящих линий",
        "value": "6",
        "unit": "шт.",
        "page": 97
      },
      {
        "label": "Динамическая стойкость к токам КЗ",
        "value": "1,3–15,6",
        "unit": "кА",
        "page": 97
      },
      {
        "label": "Термическая стойкость к токам КЗ",
        "value": "0,9–8,1",
        "unit": "кА",
        "page": 97
      },
      {
        "label": "Количество фидеров",
        "value": "1",
        "unit": "",
        "page": 97
      },
      {
        "label": "Степень защиты",
        "value": "IP55 (по требованию заказчика)",
        "unit": "",
        "page": 97
      },
      {
        "label": "Масса без трансформатора",
        "value": "315",
        "unit": "кг",
        "page": 97
      },
      {
        "label": "Температура",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 97
      },
      {
        "label": "Мощность силового трансформатора",
        "value": "25",
        "unit": "кВА",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 6 кВ",
        "value": "2,4",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 10 кВ",
        "value": "1,45",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 6 кВ",
        "value": "8",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 10 кВ",
        "value": "5",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток НН",
        "value": "36",
        "unit": "А",
        "page": 97
      }
    ],
    "notes": [
      "В заголовке диапазон до 400 кВА, но таблица содержит только 25–250 кВА. Модель 400 не выдумана. В ячейке тока при 10 кВ для 40 кВА напечатано «2,3,1»; значение не исправлено."
    ],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ktpnd",
    "familyName": "КТПНД 25–400/6(10)/0,4 кВ У1",
    "variantSpecs": [
      {
        "label": "Мощность силового трансформатора",
        "value": "25",
        "unit": "кВА",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 6 кВ",
        "value": "2,4",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 10 кВ",
        "value": "1,45",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 6 кВ",
        "value": "8",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 10 кВ",
        "value": "5",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток НН",
        "value": "36",
        "unit": "А",
        "page": 97
      }
    ]
  },
  {
    "id": "cat-ktpnd-v002",
    "sku": "КТПНД 40",
    "name": "КТПНД 40",
    "category": "substations",
    "subtype": "Для нефтеперерабатывающей промышленности",
    "power": 40,
    "voltage": "6(10) → 0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      97
    ],
    "series": "КТПНД 25–400/6(10)/0,4 кВ У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpnd.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 97,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Подстанции наружной установки для промысловых скважин добычи нефти и других промышленных объектов. Ввод ВН воздушный, вывод НН кабельный. Каталожное обозначение (включая печатные шаблоны): КТПНД 40. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Номинальное напряжение ВН",
        "value": "6(10)",
        "unit": "кВ",
        "page": 97
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,4",
        "unit": "кВ",
        "page": 97
      },
      {
        "label": "Число отходящих линий",
        "value": "6",
        "unit": "шт.",
        "page": 97
      },
      {
        "label": "Динамическая стойкость к токам КЗ",
        "value": "1,3–15,6",
        "unit": "кА",
        "page": 97
      },
      {
        "label": "Термическая стойкость к токам КЗ",
        "value": "0,9–8,1",
        "unit": "кА",
        "page": 97
      },
      {
        "label": "Количество фидеров",
        "value": "1",
        "unit": "",
        "page": 97
      },
      {
        "label": "Степень защиты",
        "value": "IP55 (по требованию заказчика)",
        "unit": "",
        "page": 97
      },
      {
        "label": "Масса без трансформатора",
        "value": "315",
        "unit": "кг",
        "page": 97
      },
      {
        "label": "Температура",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 97
      },
      {
        "label": "Мощность силового трансформатора",
        "value": "40",
        "unit": "кВА",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 6 кВ",
        "value": "3,9",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 10 кВ",
        "value": "2,3,1",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 6 кВ",
        "value": "10",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 10 кВ",
        "value": "8",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток НН",
        "value": "58",
        "unit": "А",
        "page": 97
      }
    ],
    "notes": [
      "В заголовке диапазон до 400 кВА, но таблица содержит только 25–250 кВА. Модель 400 не выдумана. В ячейке тока при 10 кВ для 40 кВА напечатано «2,3,1»; значение не исправлено."
    ],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ktpnd",
    "familyName": "КТПНД 25–400/6(10)/0,4 кВ У1",
    "variantSpecs": [
      {
        "label": "Мощность силового трансформатора",
        "value": "40",
        "unit": "кВА",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 6 кВ",
        "value": "3,9",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток ВН при 10 кВ",
        "value": "2,3,1",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 6 кВ",
        "value": "10",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Плавкая вставка предохранителя при 10 кВ",
        "value": "8",
        "unit": "А",
        "page": 97
      },
      {
        "label": "Номинальный ток НН",
        "value": "58",
        "unit": "А",
        "page": 97
      }
    ]
  }
];
export default data;
