// Generated by scripts/catalog_data.py; preserve source order and values.
const data = [
  {
    "id": "cat-ktpo-4-10-v001",
    "sku": "КТПО-4/6/0,23",
    "name": "КТПО-4/6/0,23",
    "category": "substations",
    "subtype": "Специальная однофазная",
    "power": 4,
    "voltage": "6 → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная; железобетонные Т-образные стойки",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      17
    ],
    "series": "КТПО 4-10/6(10)/0,23кВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpo-4-10.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 17,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Подстанции КТПО устанавливаются на железобетонных Т-образных стойках. Включение со стороны ВН концевое, по тупиковой схеме. Подключение к воздушным сетям со стороны ВН и к воздушным или кабельным сетям со стороны НН. Каталожное обозначение (включая печатные шаблоны): КТПО-4/6/0,23. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Род тока",
        "value": "однофазный переменный",
        "unit": "",
        "page": 17
      },
      {
        "label": "Частота",
        "value": "50",
        "unit": "Гц",
        "page": 17
      },
      {
        "label": "Габариты по чертежу, ширина × глубина × высота",
        "value": "710 × 1000 × 2050",
        "unit": "мм",
        "page": 17
      },
      {
        "label": "Номинальная мощность",
        "value": "4",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "6",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "2",
        "unit": "шт.",
        "page": 17
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ktpo-4-10",
    "familyName": "КТПО 4-10/6(10)/0,23кВ",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "4",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "6",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "2",
        "unit": "шт.",
        "page": 17
      }
    ]
  },
  {
    "id": "cat-ktpo-4-10-v002",
    "sku": "КТПО-4/10/0,23",
    "name": "КТПО-4/10/0,23",
    "category": "substations",
    "subtype": "Специальная однофазная",
    "power": 4,
    "voltage": "10 → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная; железобетонные Т-образные стойки",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      17
    ],
    "series": "КТПО 4-10/6(10)/0,23кВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpo-4-10.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 17,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Подстанции КТПО устанавливаются на железобетонных Т-образных стойках. Включение со стороны ВН концевое, по тупиковой схеме. Подключение к воздушным сетям со стороны ВН и к воздушным или кабельным сетям со стороны НН. Каталожное обозначение (включая печатные шаблоны): КТПО-4/10/0,23. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Род тока",
        "value": "однофазный переменный",
        "unit": "",
        "page": 17
      },
      {
        "label": "Частота",
        "value": "50",
        "unit": "Гц",
        "page": 17
      },
      {
        "label": "Габариты по чертежу, ширина × глубина × высота",
        "value": "710 × 1000 × 2050",
        "unit": "мм",
        "page": 17
      },
      {
        "label": "Номинальная мощность",
        "value": "4",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "10",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "2",
        "unit": "шт.",
        "page": 17
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ktpo-4-10",
    "familyName": "КТПО 4-10/6(10)/0,23кВ",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "4",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "10",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "2",
        "unit": "шт.",
        "page": 17
      }
    ]
  },
  {
    "id": "cat-ktpo-4-10-v003",
    "sku": "КТПО 10/6/0,23",
    "name": "КТПО 10/6/0,23",
    "category": "substations",
    "subtype": "Специальная однофазная",
    "power": 10,
    "voltage": "6 → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная; железобетонные Т-образные стойки",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      17
    ],
    "series": "КТПО 4-10/6(10)/0,23кВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpo-4-10.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 17,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Подстанции КТПО устанавливаются на железобетонных Т-образных стойках. Включение со стороны ВН концевое, по тупиковой схеме. Подключение к воздушным сетям со стороны ВН и к воздушным или кабельным сетям со стороны НН. Каталожное обозначение (включая печатные шаблоны): КТПО 10/6/0,23. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Род тока",
        "value": "однофазный переменный",
        "unit": "",
        "page": 17
      },
      {
        "label": "Частота",
        "value": "50",
        "unit": "Гц",
        "page": 17
      },
      {
        "label": "Габариты по чертежу, ширина × глубина × высота",
        "value": "710 × 1000 × 2050",
        "unit": "мм",
        "page": 17
      },
      {
        "label": "Номинальная мощность",
        "value": "10",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "6",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "3",
        "unit": "шт.",
        "page": 17
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ktpo-4-10",
    "familyName": "КТПО 4-10/6(10)/0,23кВ",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "10",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "6",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "3",
        "unit": "шт.",
        "page": 17
      }
    ]
  },
  {
    "id": "cat-ktpo-4-10-v004",
    "sku": "КТПО-10/10/0,23",
    "name": "КТПО-10/10/0,23",
    "category": "substations",
    "subtype": "Специальная однофазная",
    "power": 10,
    "voltage": "10 → 0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная; железобетонные Т-образные стойки",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      17
    ],
    "series": "КТПО 4-10/6(10)/0,23кВ",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpo-4-10.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 17,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Подстанции КТПО устанавливаются на железобетонных Т-образных стойках. Включение со стороны ВН концевое, по тупиковой схеме. Подключение к воздушным сетям со стороны ВН и к воздушным или кабельным сетям со стороны НН. Каталожное обозначение (включая печатные шаблоны): КТПО-10/10/0,23. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Род тока",
        "value": "однофазный переменный",
        "unit": "",
        "page": 17
      },
      {
        "label": "Частота",
        "value": "50",
        "unit": "Гц",
        "page": 17
      },
      {
        "label": "Габариты по чертежу, ширина × глубина × высота",
        "value": "710 × 1000 × 2050",
        "unit": "мм",
        "page": 17
      },
      {
        "label": "Номинальная мощность",
        "value": "10",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "10",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "3",
        "unit": "шт.",
        "page": 17
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-ktpo-4-10",
    "familyName": "КТПО 4-10/6(10)/0,23кВ",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "10",
        "unit": "кВА",
        "page": 17
      },
      {
        "label": "Номинальное напряжение ВН",
        "value": "10",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,23",
        "unit": "кВ",
        "page": 17
      },
      {
        "label": "Количество отходящих линий",
        "value": "3",
        "unit": "шт.",
        "page": 17
      }
    ]
  },
  {
    "id": "cat-ktpto-80",
    "sku": "КТПТО 80/0,38 У1",
    "name": "Комплектная трансформаторная подстанция КТПТО 80/0,38 У1",
    "category": "substations",
    "subtype": "Для электропрогрева бетона и грунта",
    "power": 80,
    "voltage": "0,38 кВ; СН 55/65/75/85/95 В; НН 42 В",
    "voltageUnit": "",
    "cooling": null,
    "installation": "Наружная",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      18
    ],
    "series": "КТПТО 80/0,38 У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktpto-80.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 18,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Подстанция наружной установки для электропрогрева и электротермообработки бетона и мерзлого грунта с автоматическим регулированием температуры, а также питания временного освещения и ручного инструмента напряжением 42 В на строительных площадках. Оснащается трехфазным трехобмоточным трансформатором ТМТО-80/0,38 с естественным охлаждением. Предусмотрены блокировки, ручное, дистанционное и автоматическое управление.",
    "technicalSpecs": [
      {
        "label": "Мощность в обозначении силового трансформатора",
        "value": "80",
        "unit": "кВА",
        "page": 18
      },
      {
        "label": "Трансформатор",
        "value": "ТМТО-80/0,38",
        "unit": "",
        "page": 18
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −40 до +10",
        "unit": "°C",
        "page": 18
      },
      {
        "label": "Ступени напряжения холостого хода на стороне СН",
        "value": "55, 65, 75, 85, 95",
        "unit": "В",
        "page": 18
      },
      {
        "label": "Ток СН при напряжении 55–65 В",
        "value": "520",
        "unit": "А",
        "page": 18
      },
      {
        "label": "Ток СН при напряжении 75–85–95 В",
        "value": "471",
        "unit": "А",
        "page": 18
      },
      {
        "label": "Номинальная мощность обмотки НН силового трансформатора",
        "value": "2,5",
        "unit": "кВА",
        "page": 18
      },
      {
        "label": "Номинальное напряжение НН силового трансформатора",
        "value": "42",
        "unit": "В",
        "page": 18
      },
      {
        "label": "Диапазон автоматического регулирования температуры",
        "value": "0–100",
        "unit": "°C",
        "page": 18
      },
      {
        "label": "Питание стороннего потребителя, напряжение",
        "value": "380",
        "unit": "В",
        "page": 18
      },
      {
        "label": "Питание стороннего потребителя, ток",
        "value": "10",
        "unit": "А",
        "page": 18
      },
      {
        "label": "Габариты по чертежу, ширина основания × глубина × высота, не более",
        "value": "1015 × 1210 × 1470",
        "unit": "мм",
        "page": 18
      },
      {
        "label": "Ширина корпуса по чертежу, не более",
        "value": "1000",
        "unit": "мм",
        "page": 18
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": []
  },
  {
    "id": "cat-ktps-100-1600",
    "sku": "КТПС 100-1600/35/0,4кВ У1",
    "name": "Комплектные трансформаторные подстанции КТПС для электроснабжения небольших объектов",
    "category": "substations",
    "subtype": "Подстанция 35/0,4 кВ",
    "power": null,
    "voltage": "35/0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, по общему виду",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      19,
      20
    ],
    "series": "КТПС 100-1600/35/0,4кВ У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktps-100-1600.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 19,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Комплектные трансформаторные подстанции КТПС предназначены для энергоснабжения небольших объектов. В каталоге показаны общий вид, габариты и принципиальная схема.",
    "technicalSpecs": [
      {
        "label": "Мощность силового трансформатора в таблице",
        "value": "100;160;250;400;630;1000",
        "unit": "кВА",
        "page": 19
      },
      {
        "label": "Номинальное линейное напряжение ВН",
        "value": "35",
        "unit": "кВ",
        "page": 19
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,4",
        "unit": "кВ",
        "page": 19
      },
      {
        "label": "Номинальный ток предохранителя 35 кВ",
        "value": "5;8;10;16;20;31;50",
        "unit": "А",
        "page": 19
      },
      {
        "label": "Номинальный ток отключения предохранителя 35 кВ",
        "value": "8",
        "unit": "кА",
        "page": 19
      },
      {
        "label": "Уровень звука",
        "value": "60",
        "unit": "дБА",
        "page": 19
      },
      {
        "label": "Схема и группа соединения обмоток",
        "value": "У/У-0, Д/У-11",
        "unit": "",
        "page": 19
      },
      {
        "label": "Степень защиты шкафа НН",
        "value": "IP 34",
        "unit": "",
        "page": 19
      },
      {
        "label": "Степень защиты остальных элементов",
        "value": "IP 00",
        "unit": "",
        "page": 19
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 19
      },
      {
        "label": "Ширина по чертежу КТПС 100–630/35кВ",
        "value": "2500",
        "unit": "мм",
        "page": 19
      },
      {
        "label": "Высота по чертежу КТПС 100–630/35кВ",
        "value": "≥4500",
        "unit": "мм",
        "page": 19
      },
      {
        "label": "Ширина по чертежу КТПС 1000–1600/35кВ",
        "value": "3000",
        "unit": "мм",
        "page": 20
      },
      {
        "label": "Высота над верхом фундамента по чертежу КТПС 1000–1600/35кВ",
        "value": "4300",
        "unit": "мм",
        "page": 20
      },
      {
        "label": "Высота фундамента по чертежу",
        "value": "600",
        "unit": "мм",
        "page": 20
      }
    ],
    "notes": [
      "В таблице 6 значений мощности и 7 значений тока предохранителя; взаимное соответствие не задано и не угадано.",
      "Диапазон заголовка включает 1600 кВА, тогда как перечень мощности заканчивается 1000 кВА; исполнение КТПС-1600 дополнительно подписано на странице 20.",
      "Мощности и токи предохранителей в таблице имеют разное число элементов. Нет надежного соответствия значений отдельным мощностям."
    ],
    "variantIds": [
      "cat-ktps-100-1600-v007"
    ],
    "configurations": [
      {
        "designation": "100 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "100",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "160 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "160",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "250 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "250",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "400 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "400",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "630 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "630",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "1000 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "1000",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      }
    ]
  },
  {
    "id": "cat-ktps-100-1600-v007",
    "sku": "КТПС-1600",
    "name": "КТПС-1600",
    "category": "substations",
    "subtype": "Подстанция 35/0,4 кВ",
    "power": 1600,
    "voltage": "35/0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, по общему виду",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      19,
      20
    ],
    "series": "КТПС 100-1600/35/0,4кВ У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ktps-100-1600.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 19,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Комплектные трансформаторные подстанции КТПС предназначены для энергоснабжения небольших объектов. В каталоге показаны общий вид, габариты и принципиальная схема. Каталожное обозначение (включая печатные шаблоны): КТПС-1600. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Мощность силового трансформатора в таблице",
        "value": "100;160;250;400;630;1000",
        "unit": "кВА",
        "page": 19
      },
      {
        "label": "Номинальное линейное напряжение ВН",
        "value": "35",
        "unit": "кВ",
        "page": 19
      },
      {
        "label": "Номинальное напряжение НН",
        "value": "0,4",
        "unit": "кВ",
        "page": 19
      },
      {
        "label": "Номинальный ток предохранителя 35 кВ",
        "value": "5;8;10;16;20;31;50",
        "unit": "А",
        "page": 19
      },
      {
        "label": "Номинальный ток отключения предохранителя 35 кВ",
        "value": "8",
        "unit": "кА",
        "page": 19
      },
      {
        "label": "Уровень звука",
        "value": "60",
        "unit": "дБА",
        "page": 19
      },
      {
        "label": "Схема и группа соединения обмоток",
        "value": "У/У-0, Д/У-11",
        "unit": "",
        "page": 19
      },
      {
        "label": "Степень защиты шкафа НН",
        "value": "IP 34",
        "unit": "",
        "page": 19
      },
      {
        "label": "Степень защиты остальных элементов",
        "value": "IP 00",
        "unit": "",
        "page": 19
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 19
      },
      {
        "label": "Ширина по чертежу КТПС 100–630/35кВ",
        "value": "2500",
        "unit": "мм",
        "page": 19
      },
      {
        "label": "Высота по чертежу КТПС 100–630/35кВ",
        "value": "≥4500",
        "unit": "мм",
        "page": 19
      },
      {
        "label": "Ширина по чертежу КТПС 1000–1600/35кВ",
        "value": "3000",
        "unit": "мм",
        "page": 20
      },
      {
        "label": "Высота над верхом фундамента по чертежу КТПС 1000–1600/35кВ",
        "value": "4300",
        "unit": "мм",
        "page": 20
      },
      {
        "label": "Высота фундамента по чертежу",
        "value": "600",
        "unit": "мм",
        "page": 20
      },
      {
        "label": "Мощность, указанная в обозначении на схеме",
        "value": "1600",
        "unit": "кВА",
        "page": 20
      }
    ],
    "notes": [
      "В таблице 6 значений мощности и 7 значений тока предохранителя; взаимное соответствие не задано и не угадано.",
      "Диапазон заголовка включает 1600 кВА, тогда как перечень мощности заканчивается 1000 кВА; исполнение КТПС-1600 дополнительно подписано на странице 20.",
      "Мощности и токи предохранителей в таблице имеют разное число элементов. Нет надежного соответствия значений отдельным мощностям.",
      "Тип подписан на принципиальной схеме. В перечне мощности на странице 19 значение 1600 отсутствует."
    ],
    "variantIds": [],
    "configurations": [
      {
        "designation": "100 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "100",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "160 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "160",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "250 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "250",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "400 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "400",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "630 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "630",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      },
      {
        "designation": "1000 кВА",
        "specifications": [
          {
            "label": "Мощность силового трансформатора",
            "value": "1000",
            "unit": "кВА",
            "page": 19
          }
        ],
        "page": 19,
        "notes": [
          "Полное обозначение варианта не напечатано; значение взято из перечня мощности."
        ],
        "kind": "configuration"
      }
    ],
    "familyId": "cat-ktps-100-1600",
    "familyName": "КТПС 100-1600/35/0,4кВ У1",
    "variantSpecs": [
      {
        "label": "Мощность, указанная в обозначении на схеме",
        "value": "1600",
        "unit": "кВА",
        "page": 20
      }
    ]
  },
  {
    "id": "cat-mtp-25-100",
    "sku": "МТП 25-100/10(6) У1",
    "name": "Мачтовая трансформаторная подстанция МТП",
    "category": "substations",
    "subtype": "Мачтовая однотрансформаторная трехфазная",
    "power": null,
    "voltage": "10(6)/0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, мачтовая",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      21
    ],
    "series": "МТП 25-100/10(6) У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-mtp-25-100.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 21,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Мачтовые однотрансформаторные подстанции наружной установки для приема электроэнергии 6 или 10 кВ, преобразования в 0,4 кВ и электроснабжения населенных пунктов, небольших промышленных объектов и других потребителей в умеренном климате.",
    "technicalSpecs": [
      {
        "label": "Мощность",
        "value": "25;40;63;100",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Род тока",
        "value": "Переменный, трехфазный",
        "unit": "",
        "page": 21
      },
      {
        "label": "Количество фидеров",
        "value": "2;3",
        "unit": "",
        "page": 21
      },
      {
        "label": "Степень защиты",
        "value": "IP-23",
        "unit": "",
        "page": 21
      },
      {
        "label": "Масса шкафа РУНН",
        "value": "115",
        "unit": "кг",
        "page": 21
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 21
      },
      {
        "label": "Соответствие",
        "value": "СТ АО 940140001056-041-2010",
        "unit": "",
        "page": 21
      }
    ],
    "notes": [],
    "variantIds": [
      "cat-mtp-25-100-v001",
      "cat-mtp-25-100-v002",
      "cat-mtp-25-100-v003",
      "cat-mtp-25-100-v004"
    ],
    "configurations": []
  },
  {
    "id": "cat-mtp-25-100-v001",
    "sku": "МТП-25/10(6)",
    "name": "МТП-25/10(6)",
    "category": "substations",
    "subtype": "Мачтовая однотрансформаторная трехфазная",
    "power": 25,
    "voltage": "6(10)",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, мачтовая",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      21
    ],
    "series": "МТП 25-100/10(6) У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-mtp-25-100.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 21,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Мачтовые однотрансформаторные подстанции наружной установки для приема электроэнергии 6 или 10 кВ, преобразования в 0,4 кВ и электроснабжения населенных пунктов, небольших промышленных объектов и других потребителей в умеренном климате. Каталожное обозначение (включая печатные шаблоны): МТП-25/10(6). Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Мощность",
        "value": "25",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Род тока",
        "value": "Переменный, трехфазный",
        "unit": "",
        "page": 21
      },
      {
        "label": "Количество фидеров",
        "value": "2;3",
        "unit": "",
        "page": 21
      },
      {
        "label": "Степень защиты",
        "value": "IP-23",
        "unit": "",
        "page": 21
      },
      {
        "label": "Масса шкафа РУНН",
        "value": "115",
        "unit": "кг",
        "page": 21
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 21
      },
      {
        "label": "Соответствие",
        "value": "СТ АО 940140001056-041-2010",
        "unit": "",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "31,5",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "31,5",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "−",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "8(5)",
        "unit": "А",
        "page": 21
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-mtp-25-100",
    "familyName": "МТП 25-100/10(6) У1",
    "variantSpecs": [
      {
        "label": "Мощность",
        "value": "25",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "31,5",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "31,5",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "−",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "8(5)",
        "unit": "А",
        "page": 21
      }
    ]
  },
  {
    "id": "cat-mtp-25-100-v002",
    "sku": "МТП-40/10(6)",
    "name": "МТП-40/10(6)",
    "category": "substations",
    "subtype": "Мачтовая однотрансформаторная трехфазная",
    "power": 40,
    "voltage": "6(10)",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, мачтовая",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      21
    ],
    "series": "МТП 25-100/10(6) У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-mtp-25-100.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 21,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Мачтовые однотрансформаторные подстанции наружной установки для приема электроэнергии 6 или 10 кВ, преобразования в 0,4 кВ и электроснабжения населенных пунктов, небольших промышленных объектов и других потребителей в умеренном климате. Каталожное обозначение (включая печатные шаблоны): МТП-40/10(6). Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Мощность",
        "value": "40",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Род тока",
        "value": "Переменный, трехфазный",
        "unit": "",
        "page": 21
      },
      {
        "label": "Количество фидеров",
        "value": "2;3",
        "unit": "",
        "page": 21
      },
      {
        "label": "Степень защиты",
        "value": "IP-23",
        "unit": "",
        "page": 21
      },
      {
        "label": "Масса шкафа РУНН",
        "value": "115",
        "unit": "кг",
        "page": 21
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 21
      },
      {
        "label": "Соответствие",
        "value": "СТ АО 940140001056-041-2010",
        "unit": "",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "31,5",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "63",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "−",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "10(8)",
        "unit": "А",
        "page": 21
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-mtp-25-100",
    "familyName": "МТП 25-100/10(6) У1",
    "variantSpecs": [
      {
        "label": "Мощность",
        "value": "40",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "31,5",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "63",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "−",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "10(8)",
        "unit": "А",
        "page": 21
      }
    ]
  },
  {
    "id": "cat-mtp-25-100-v003",
    "sku": "МТП-63/10(6)",
    "name": "МТП-63/10(6)",
    "category": "substations",
    "subtype": "Мачтовая однотрансформаторная трехфазная",
    "power": 63,
    "voltage": "6(10)",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, мачтовая",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      21
    ],
    "series": "МТП 25-100/10(6) У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-mtp-25-100.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 21,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Мачтовые однотрансформаторные подстанции наружной установки для приема электроэнергии 6 или 10 кВ, преобразования в 0,4 кВ и электроснабжения населенных пунктов, небольших промышленных объектов и других потребителей в умеренном климате. Каталожное обозначение (включая печатные шаблоны): МТП-63/10(6). Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Мощность",
        "value": "63",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Род тока",
        "value": "Переменный, трехфазный",
        "unit": "",
        "page": 21
      },
      {
        "label": "Количество фидеров",
        "value": "2;3",
        "unit": "",
        "page": 21
      },
      {
        "label": "Степень защиты",
        "value": "IP-23",
        "unit": "",
        "page": 21
      },
      {
        "label": "Масса шкафа РУНН",
        "value": "115",
        "unit": "кг",
        "page": 21
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 21
      },
      {
        "label": "Соответствие",
        "value": "СТ АО 940140001056-041-2010",
        "unit": "",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "40",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "63",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "40",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "16(10)",
        "unit": "А",
        "page": 21
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-mtp-25-100",
    "familyName": "МТП 25-100/10(6) У1",
    "variantSpecs": [
      {
        "label": "Мощность",
        "value": "63",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "40",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "63",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "40",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "16(10)",
        "unit": "А",
        "page": 21
      }
    ]
  },
  {
    "id": "cat-mtp-25-100-v004",
    "sku": "МТП-100/10(6)",
    "name": "МТП-100/10(6)",
    "category": "substations",
    "subtype": "Мачтовая однотрансформаторная трехфазная",
    "power": 100,
    "voltage": "6(10)",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, мачтовая",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      21
    ],
    "series": "МТП 25-100/10(6) У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-mtp-25-100.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 21,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Мачтовые однотрансформаторные подстанции наружной установки для приема электроэнергии 6 или 10 кВ, преобразования в 0,4 кВ и электроснабжения населенных пунктов, небольших промышленных объектов и других потребителей в умеренном климате. Каталожное обозначение (включая печатные шаблоны): МТП-100/10(6). Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Мощность",
        "value": "100",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Род тока",
        "value": "Переменный, трехфазный",
        "unit": "",
        "page": 21
      },
      {
        "label": "Количество фидеров",
        "value": "2;3",
        "unit": "",
        "page": 21
      },
      {
        "label": "Степень защиты",
        "value": "IP-23",
        "unit": "",
        "page": 21
      },
      {
        "label": "Масса шкафа РУНН",
        "value": "115",
        "unit": "кг",
        "page": 21
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −45 до +40",
        "unit": "°C",
        "page": 21
      },
      {
        "label": "Соответствие",
        "value": "СТ АО 940140001056-041-2010",
        "unit": "",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "40",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "63",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "80",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "20(16)",
        "unit": "А",
        "page": 21
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-mtp-25-100",
    "familyName": "МТП 25-100/10(6) У1",
    "variantSpecs": [
      {
        "label": "Мощность",
        "value": "100",
        "unit": "кВА",
        "page": 21
      },
      {
        "label": "Номинальное высшее напряжение питающей сети",
        "value": "6(10)",
        "unit": "кВ",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №1",
        "value": "40",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №2",
        "value": "63",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера №3",
        "value": "80",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток фидера освещения",
        "value": "16",
        "unit": "А",
        "page": 21
      },
      {
        "label": "Номинальный ток плавкой вставки предохранителя на стороне ВН",
        "value": "20(16)",
        "unit": "А",
        "page": 21
      }
    ]
  },
  {
    "id": "cat-mtpo-4-10",
    "sku": "МТПО 4-10/10(6)/0,23 У1",
    "name": "Мачтовая трансформаторная подстанция однофазная МТПО",
    "category": "substations",
    "subtype": "Мачтовая однофазная",
    "power": null,
    "voltage": "10(6)/0,23",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Наружная, мачтовая",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      22
    ],
    "series": "МТПО 4-10/10(6)/0,23 У1",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-mtpo-4-10.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 22,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Однофазные мачтовые подстанции для приема электроэнергии 6 или 10 кВ, преобразования в 0,23 кВ и электроснабжения фермерских хозяйств, садоводческих участков и других сельскохозяйственных потребителей в умеренном климате. Подключаются к ЛЭП через разъединитель на ближайшей концевой опоре. Комплектуются металлоконструкциями для шкафа РУНН, трансформатора, разрядников и предохранителей. Количество и токи отходящих линий могут изменяться по желанию заказчика.",
    "technicalSpecs": [
      {
        "label": "Род тока",
        "value": "Однофазный переменный",
        "unit": "",
        "page": 22
      },
      {
        "label": "Соответствие",
        "value": "СТ АО 00010033-025-2010",
        "unit": "",
        "page": 22
      },
      {
        "label": "Отходящие фидеры в описании",
        "value": "Два фидера по 25 А и один фидер на 40 А",
        "unit": "",
        "page": 22
      },
      {
        "label": "Высота установки верхнего узла по чертежу",
        "value": "6000",
        "unit": "мм",
        "page": 22
      },
      {
        "label": "Высота установки шкафа РУНН по чертежу",
        "value": "2000",
        "unit": "мм",
        "page": 22
      }
    ],
    "notes": [
      "Описание фидеров (25/25/40 А) не согласовано с таблицей, в которой линия №1 — 25 А для 4 кВА и 50 А для 10 кВА, линия освещения — 6/10 А. Значения сохранены раздельно.",
      "Текстовый перечень токов фидеров и табличные характеристики линий различаются."
    ],
    "variantIds": [],
    "configurations": [
      {
        "designation": "4 кВА",
        "specifications": [
          {
            "label": "Мощность",
            "value": "4",
            "unit": "кВА",
            "page": 22
          },
          {
            "label": "Напряжение ВН",
            "value": "6",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Напряжение НН",
            "value": "0,23",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Номинальный ток плавкой вставки предохранителя ВН",
            "value": "2",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Номинальный ток трансформатора НН",
            "value": "17,4",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия №1",
            "value": "25",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия уличного освещения",
            "value": "6",
            "unit": "А",
            "page": 22
          }
        ],
        "page": 22,
        "notes": [
          "Вариант соответствует отдельному подстолбцу таблицы; полное обозначение модели для сочетания мощности и ВН не напечатано."
        ],
        "kind": "configuration"
      },
      {
        "designation": "4 кВА",
        "specifications": [
          {
            "label": "Мощность",
            "value": "4",
            "unit": "кВА",
            "page": 22
          },
          {
            "label": "Напряжение ВН",
            "value": "10",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Напряжение НН",
            "value": "0,23",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Номинальный ток плавкой вставки предохранителя ВН",
            "value": "2",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Номинальный ток трансформатора НН",
            "value": "17,4",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия №1",
            "value": "25",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия уличного освещения",
            "value": "6",
            "unit": "А",
            "page": 22
          }
        ],
        "page": 22,
        "notes": [
          "Вариант соответствует отдельному подстолбцу таблицы; полное обозначение модели для сочетания мощности и ВН не напечатано."
        ],
        "kind": "configuration"
      },
      {
        "designation": "10 кВА",
        "specifications": [
          {
            "label": "Мощность",
            "value": "10",
            "unit": "кВА",
            "page": 22
          },
          {
            "label": "Напряжение ВН",
            "value": "6",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Напряжение НН",
            "value": "0,23",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Номинальный ток плавкой вставки предохранителя ВН",
            "value": "2",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Номинальный ток трансформатора НН",
            "value": "43,4",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия №1",
            "value": "50",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия уличного освещения",
            "value": "10",
            "unit": "А",
            "page": 22
          }
        ],
        "page": 22,
        "notes": [
          "Вариант соответствует отдельному подстолбцу таблицы; полное обозначение модели для сочетания мощности и ВН не напечатано."
        ],
        "kind": "configuration"
      },
      {
        "designation": "10 кВА",
        "specifications": [
          {
            "label": "Мощность",
            "value": "10",
            "unit": "кВА",
            "page": 22
          },
          {
            "label": "Напряжение ВН",
            "value": "10",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Напряжение НН",
            "value": "0,23",
            "unit": "кВ",
            "page": 22
          },
          {
            "label": "Номинальный ток плавкой вставки предохранителя ВН",
            "value": "2",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Номинальный ток трансформатора НН",
            "value": "43,4",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия №1",
            "value": "50",
            "unit": "А",
            "page": 22
          },
          {
            "label": "Линия уличного освещения",
            "value": "10",
            "unit": "А",
            "page": 22
          }
        ],
        "page": 22,
        "notes": [
          "Вариант соответствует отдельному подстолбцу таблицы; полное обозначение модели для сочетания мощности и ВН не напечатано."
        ],
        "kind": "configuration"
      }
    ]
  },
  {
    "id": "kso-366",
    "sku": "КСО-366",
    "name": "Камеры сборные одностороннего обслуживания серии КСО-366",
    "category": "switchgear",
    "subtype": "Камера сборная одностороннего обслуживания",
    "power": null,
    "voltage": "6;10",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "Внутренняя",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      23
    ],
    "series": "КСО-366",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/kso-366.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 23,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Камеры внутренней установки для комплектования высоковольтных распределительных устройств 6 или 10 кВ. Разборная металлоконструкция с аппаратурой главных цепей, фасадными приводами выключателя нагрузки и разъединителя и верхним релейным отсеком. Доступ через переднюю дверь со смотровым окном и замком. Предусмотрены блокировки и взаимозаменяемость с камерами КСО-2-10. Изготовление по схемам главных цепей и опросному листу.",
    "technicalSpecs": [
      {
        "label": "Номинальное напряжение",
        "value": "6;10",
        "unit": "кВ",
        "page": 23
      },
      {
        "label": "Частота",
        "value": "50",
        "unit": "Гц",
        "page": 23
      },
      {
        "label": "Род тока",
        "value": "Трехфазный переменный",
        "unit": "",
        "page": 23
      },
      {
        "label": "Нейтраль системы",
        "value": "Изолированная или заземленная через дугогасящий реактор",
        "unit": "",
        "page": 23
      },
      {
        "label": "Температура окружающего воздуха",
        "value": "от −25 до +45",
        "unit": "°C",
        "page": 23
      },
      {
        "label": "Высота над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 23
      },
      {
        "label": "Степень защиты со стороны фасада",
        "value": "IP 20",
        "unit": "",
        "page": 23
      },
      {
        "label": "Степень защиты с остальных сторон",
        "value": "IP 00",
        "unit": "",
        "page": 23
      },
      {
        "label": "Климатическое исполнение",
        "value": "УХЛ по ГОСТ 15150",
        "unit": "",
        "page": 23
      },
      {
        "label": "Категория размещения",
        "value": "3 по ГОСТ 15543.1",
        "unit": "",
        "page": 23
      },
      {
        "label": "Выключатель нагрузки",
        "value": "ВНА-630/10",
        "unit": "",
        "page": 23
      },
      {
        "label": "Разъединитель",
        "value": "РВЗ-630/10",
        "unit": "",
        "page": 23
      },
      {
        "label": "Трансформаторы тока",
        "value": "ТОЛ",
        "unit": "",
        "page": 23
      },
      {
        "label": "Трансформаторы напряжения",
        "value": "НТМИ",
        "unit": "",
        "page": 23
      },
      {
        "label": "Разрядники / ограничители перенапряжения",
        "value": "РВО или ОПН-П",
        "unit": "",
        "page": 23
      },
      {
        "label": "Предохранители",
        "value": "Предусмотрены",
        "unit": "",
        "page": 23
      },
      {
        "label": "Ширина по чертежу",
        "value": "800",
        "unit": "мм",
        "page": 23
      },
      {
        "label": "Глубина по чертежу",
        "value": "800",
        "unit": "мм",
        "page": 23
      },
      {
        "label": "Высота по чертежу",
        "value": "max 2000",
        "unit": "мм",
        "page": 23
      },
      {
        "label": "Структура условного обозначения",
        "value": "КСО - 366 - X - 630X",
        "unit": "",
        "page": 23
      }
    ],
    "notes": [
      "Схемы главных цепей показаны без обозначений конкретных моделей; комплектующие не выделены в самостоятельные товары."
    ],
    "variantIds": [],
    "configurations": []
  }
];
export default data;
