// Generated by scripts/catalog_data.py; preserve source order and values.
const data = [
  {
    "id": "cat-ya5000-rusm5000-v025",
    "sku": "Я5435",
    "name": "Я 5000-5435 и РУСМ 5000 · Я5435",
    "category": "cabinets",
    "subtype": "Ящики управления электродвигателями",
    "power": null,
    "voltage": "380 В по принципиальной схеме",
    "voltageUnit": "",
    "cooling": null,
    "installation": "На стене, колонне или другом вертикальном основании",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      66
    ],
    "series": "Я 5000-5435 и РУСМ 5000",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ya5000-rusm5000.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 66,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Для местного, дистанционного и автоматического управления асинхронными электродвигателями мощностью до 75 кВт с длительным режимом работы, а также сигнализации и защиты асинхронных двигателей с короткозамкнутым ротором. Металлический бокс с аппаратурой на внутренней панели и двери. Каталожное обозначение (включая печатные шаблоны): Я5435. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Мощность управляемого электродвигателя",
        "value": "до 75",
        "unit": "кВт",
        "page": 66
      },
      {
        "label": "Температура воздуха",
        "value": "+1…+40",
        "unit": "°C",
        "page": 66
      },
      {
        "label": "Высота над уровнем моря",
        "value": "не более 2000",
        "unit": "м",
        "page": 66
      },
      {
        "label": "Габариты по чертежу Ш×В×Г",
        "value": "350±1×500±1×225",
        "unit": "мм",
        "page": 66
      },
      {
        "label": "Вертикальный установочный размер",
        "value": "400±1",
        "unit": "мм",
        "page": 66
      },
      {
        "label": "Окружающая среда",
        "value": "невзрывоопасная, без токопроводящей пыли, агрессивных газов и паров",
        "unit": "",
        "page": 66
      },
      {
        "label": "Типовой индекс, диапазон в каталоге",
        "value": "18–34",
        "unit": "",
        "page": 66
      }
    ],
    "notes": [
      "Типы ящиков и типовые индексы перечислены независимо, без изготовления комбинаций обозначений.",
      "В каталоге для индекса 22xx* диапазон теплового реле напечатан 0,95–0,6 А; сохранено без исправления.",
      "Последняя группа типов повторяет Я5434; повтор одного обозначения не создан как второй товар.",
      "Для индекса 22xx* предел регулировки реле напечатан 0,95–0,6 А. Последняя группа повторяет Я5434; в списке сохранен один экземпляр. Диапазоны типовых индексов и визуальная группировка строк не дают однозначной полной матрицы моделей; комбинации не созданы."
    ],
    "variantIds": [],
    "configurations": [
      {
        "designation": "18xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "0,6",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "0,38–0,68",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "1,6",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "20xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "1",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "0,61–1,0",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "—",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "22xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "1,6",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "0,95–0,6",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "2,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "24xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "2,5",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "1,5–2,6",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "3,15",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "26xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "4",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "2,4–4,0",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "5,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "28xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "6",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "3,8–6,0",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "8,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "29xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "8",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "5,5–8,0",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "10,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "30xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "10",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "7–10",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "12,5",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "31xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "12,5",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "9,5–14",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "16,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "32xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "16",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "13–19",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "20,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "34xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "25",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "18–25",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "31,5",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "35xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "32",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "27,2–36,8",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "40,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "36xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "40",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "34–40",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "50,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "37xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "50",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "42,5–57,5",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "63,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "38xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "63",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "53,5–63,0",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "80,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "39xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "80",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "68–92",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "100,0",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "40xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "100",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "85–100",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "125",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "41xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "125",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "106–143",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "160",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      },
      {
        "designation": "42xx*",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "типовой индекс; самостоятельное обозначение изделия не указано",
            "unit": "",
            "page": 66
          },
          {
            "label": "Номинальный ток ящика",
            "value": "160",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Предел регулировки тока теплового реле",
            "value": "136–160",
            "unit": "А",
            "page": 66
          },
          {
            "label": "Номинальный ток расцепления автоматического выключателя",
            "value": "160",
            "unit": "А",
            "page": 66
          }
        ],
        "page": 66,
        "kind": "code-option"
      }
    ],
    "familyId": "cat-ya5000-rusm5000",
    "familyName": "Я 5000-5435 и РУСМ 5000",
    "variantSpecs": [
      {
        "label": "Типовой индекс, диапазон в каталоге",
        "value": "18–34",
        "unit": "",
        "page": 66
      }
    ]
  },
  {
    "id": "cat-yauo",
    "sku": "ЯУО 9601; ЯУО 9602",
    "name": "Ящики управления освещением серии ЯУО",
    "category": "cabinets",
    "subtype": "Ящики управления освещением",
    "power": null,
    "voltage": null,
    "voltageUnit": "",
    "cooling": null,
    "installation": "Настенное защищенное исполнение",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      67
    ],
    "series": "ЯУО 9601; ЯУО 9602",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": null,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Для автоматического, местного, ручного и дистанционного управления осветительными сетями производственных зданий, сооружений и территорий любых объектов с различными источниками света. Состоят из настенного защищенного стального ящика с передней дверью и выносной фотоголовки.",
    "technicalSpecs": [
      {
        "label": "Способы управления",
        "value": "фотодатчик; реле времени; кнопки на дверях; телемеханика из диспетчерского пункта",
        "unit": "",
        "page": 67
      },
      {
        "label": "Реле времени для ЯУО 9601",
        "value": "суточное типа 2РВМ",
        "unit": "",
        "page": 67
      },
      {
        "label": "Источники света",
        "value": "лампы накаливания; ДРЛ; ДРИ и другие",
        "unit": "",
        "page": 67
      }
    ],
    "notes": [],
    "variantIds": [
      "cat-yauo-v001",
      "cat-yauo-v002"
    ],
    "configurations": []
  },
  {
    "id": "cat-yauo-v001",
    "sku": "ЯУО 9601",
    "name": "ЯУО 9601",
    "category": "cabinets",
    "subtype": "Ящики управления освещением",
    "power": null,
    "voltage": null,
    "voltageUnit": "",
    "cooling": null,
    "installation": "Настенное защищенное исполнение",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      67
    ],
    "series": "ЯУО 9601; ЯУО 9602",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": null,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Для автоматического, местного, ручного и дистанционного управления осветительными сетями производственных зданий, сооружений и территорий любых объектов с различными источниками света. Состоят из настенного защищенного стального ящика с передней дверью и выносной фотоголовки. Каталожное обозначение (включая печатные шаблоны): ЯУО 9601. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Способы управления",
        "value": "фотодатчик; реле времени; кнопки на дверях; телемеханика из диспетчерского пункта",
        "unit": "",
        "page": 67
      },
      {
        "label": "Реле времени для ЯУО 9601",
        "value": "суточное типа 2РВМ",
        "unit": "",
        "page": 67
      },
      {
        "label": "Источники света",
        "value": "лампы накаливания; ДРЛ; ДРИ и другие",
        "unit": "",
        "page": 67
      },
      {
        "label": "Режимы",
        "value": "автоматический по времени; по времени и уровню освещенности; ручной; дистанционный",
        "unit": "",
        "page": 67
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-yauo",
    "familyName": "ЯУО 9601; ЯУО 9602",
    "variantSpecs": [
      {
        "label": "Режимы",
        "value": "автоматический по времени; по времени и уровню освещенности; ручной; дистанционный",
        "unit": "",
        "page": 67
      }
    ]
  },
  {
    "id": "cat-yauo-v002",
    "sku": "ЯУО 9602",
    "name": "ЯУО 9602",
    "category": "cabinets",
    "subtype": "Ящики управления освещением",
    "power": null,
    "voltage": null,
    "voltageUnit": "",
    "cooling": null,
    "installation": "Настенное защищенное исполнение",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      67
    ],
    "series": "ЯУО 9601; ЯУО 9602",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": null,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Для автоматического, местного, ручного и дистанционного управления осветительными сетями производственных зданий, сооружений и территорий любых объектов с различными источниками света. Состоят из настенного защищенного стального ящика с передней дверью и выносной фотоголовки. Каталожное обозначение (включая печатные шаблоны): ЯУО 9602. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Способы управления",
        "value": "фотодатчик; реле времени; кнопки на дверях; телемеханика из диспетчерского пункта",
        "unit": "",
        "page": 67
      },
      {
        "label": "Реле времени для ЯУО 9601",
        "value": "суточное типа 2РВМ",
        "unit": "",
        "page": 67
      },
      {
        "label": "Источники света",
        "value": "лампы накаливания; ДРЛ; ДРИ и другие",
        "unit": "",
        "page": 67
      },
      {
        "label": "Режимы",
        "value": "автоматический по уровню освещенности; ручной; дистанционный",
        "unit": "",
        "page": 67
      }
    ],
    "notes": [],
    "variantIds": [],
    "configurations": [],
    "familyId": "cat-yauo",
    "familyName": "ЯУО 9601; ЯУО 9602",
    "variantSpecs": [
      {
        "label": "Режимы",
        "value": "автоматический по уровню освещенности; ручной; дистанционный",
        "unit": "",
        "page": 67
      }
    ]
  },
  {
    "id": "cat-rusm-5100-5400",
    "sku": "РУСМ 5100; РУСМ 5400",
    "name": "Ящики типа РУСМ 5100 и РУСМ 5400",
    "category": "cabinets",
    "subtype": "Низковольтные ящики управления",
    "power": null,
    "voltage": "Переменный ток до 660 В; постоянный ток до 440 В",
    "voltageUnit": "",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      67
    ],
    "series": "РУСМ 5100; РУСМ 5400",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": null,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Низковольтные устройства управления нереверсивными и реверсивными двигателями с короткозамкнутым ротором. Аппараты размещены на внутренней панели и передней крышке металлического ящика; ввод и вывод проводников через сальники. Могут комплектоваться в щиты.",
    "technicalSpecs": [
      {
        "label": "Номинальное напряжение переменного тока",
        "value": "до 660",
        "unit": "В",
        "page": 67
      },
      {
        "label": "Номинальное напряжение постоянного тока",
        "value": "до 440",
        "unit": "В",
        "page": 67
      },
      {
        "label": "Ток силовой цепи устройств управления электроприводами",
        "value": "до 160",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Ток устройств ввода, распределения и учета электроэнергии",
        "value": "до 630",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Ток цепи управления",
        "value": "до 10",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Электродинамическая стойкость сборных шин до 400 А",
        "value": "25",
        "unit": "кА",
        "page": 67
      },
      {
        "label": "Электродинамическая стойкость сборных шин до 630 А",
        "value": "50",
        "unit": "кА",
        "page": 67
      }
    ],
    "notes": [
      "Габаритные исполнения перечислены отдельными строками без привязки к РУСМ 5100 либо РУСМ 5400. Названия размерных исполнений не являются заводскими артикулами."
    ],
    "variantIds": [
      "cat-rusm-5100-5400-v001",
      "cat-rusm-5100-5400-v002"
    ],
    "configurations": [
      {
        "designation": "250×250×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "250×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×250×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×750×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×750×360 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "360",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "750×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "750×500×360 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "360",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      }
    ]
  },
  {
    "id": "cat-rusm-5100-5400-v001",
    "sku": "РУСМ 5100",
    "name": "РУСМ 5100",
    "category": "cabinets",
    "subtype": "Низковольтные ящики управления",
    "power": null,
    "voltage": "Переменный ток до 660 В; постоянный ток до 440 В",
    "voltageUnit": "",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      67
    ],
    "series": "РУСМ 5100; РУСМ 5400",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": null,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Низковольтные устройства управления нереверсивными и реверсивными двигателями с короткозамкнутым ротором. Аппараты размещены на внутренней панели и передней крышке металлического ящика; ввод и вывод проводников через сальники. Могут комплектоваться в щиты. Каталожное обозначение (включая печатные шаблоны): РУСМ 5100. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Номинальное напряжение переменного тока",
        "value": "до 660",
        "unit": "В",
        "page": 67
      },
      {
        "label": "Номинальное напряжение постоянного тока",
        "value": "до 440",
        "unit": "В",
        "page": 67
      },
      {
        "label": "Ток силовой цепи устройств управления электроприводами",
        "value": "до 160",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Ток устройств ввода, распределения и учета электроэнергии",
        "value": "до 630",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Ток цепи управления",
        "value": "до 10",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Электродинамическая стойкость сборных шин до 400 А",
        "value": "25",
        "unit": "кА",
        "page": 67
      },
      {
        "label": "Электродинамическая стойкость сборных шин до 630 А",
        "value": "50",
        "unit": "кА",
        "page": 67
      },
      {
        "label": "Назначение",
        "value": "управление нереверсивными двигателями",
        "unit": "",
        "page": 67
      }
    ],
    "notes": [
      "Габаритные исполнения перечислены отдельными строками без привязки к РУСМ 5100 либо РУСМ 5400. Названия размерных исполнений не являются заводскими артикулами."
    ],
    "variantIds": [],
    "configurations": [
      {
        "designation": "250×250×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "250×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×250×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×750×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×750×360 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "360",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "750×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "750×500×360 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "360",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      }
    ],
    "familyId": "cat-rusm-5100-5400",
    "familyName": "РУСМ 5100; РУСМ 5400",
    "variantSpecs": [
      {
        "label": "Назначение",
        "value": "управление нереверсивными двигателями",
        "unit": "",
        "page": 67
      }
    ]
  },
  {
    "id": "cat-rusm-5100-5400-v002",
    "sku": "РУСМ 5400",
    "name": "РУСМ 5400",
    "category": "cabinets",
    "subtype": "Низковольтные ящики управления",
    "power": null,
    "voltage": "Переменный ток до 660 В; постоянный ток до 440 В",
    "voltageUnit": "",
    "cooling": null,
    "installation": null,
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      67
    ],
    "series": "РУСМ 5100; РУСМ 5400",
    "manufacturer": null,
    "manufacturers": [],
    "image": null,
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": null,
    "documentCount": 1,
    "recordType": "catalog-listed-variant",
    "recordKind": "variant",
    "isOrderableSku": false,
    "description": "Низковольтные устройства управления нереверсивными и реверсивными двигателями с короткозамкнутым ротором. Аппараты размещены на внутренней панели и передней крышке металлического ящика; ввод и вывод проводников через сальники. Могут комплектоваться в щиты. Каталожное обозначение (включая печатные шаблоны): РУСМ 5400. Полная комплектация и код заказа уточняются.",
    "technicalSpecs": [
      {
        "label": "Номинальное напряжение переменного тока",
        "value": "до 660",
        "unit": "В",
        "page": 67
      },
      {
        "label": "Номинальное напряжение постоянного тока",
        "value": "до 440",
        "unit": "В",
        "page": 67
      },
      {
        "label": "Ток силовой цепи устройств управления электроприводами",
        "value": "до 160",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Ток устройств ввода, распределения и учета электроэнергии",
        "value": "до 630",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Ток цепи управления",
        "value": "до 10",
        "unit": "А",
        "page": 67
      },
      {
        "label": "Электродинамическая стойкость сборных шин до 400 А",
        "value": "25",
        "unit": "кА",
        "page": 67
      },
      {
        "label": "Электродинамическая стойкость сборных шин до 630 А",
        "value": "50",
        "unit": "кА",
        "page": 67
      },
      {
        "label": "Назначение",
        "value": "управление реверсивными двигателями",
        "unit": "",
        "page": 67
      }
    ],
    "notes": [
      "Габаритные исполнения перечислены отдельными строками без привязки к РУСМ 5100 либо РУСМ 5400. Названия размерных исполнений не являются заводскими артикулами."
    ],
    "variantIds": [],
    "configurations": [
      {
        "designation": "250×250×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "250×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×250×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "250",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×750×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "500×750×360 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "360",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "750×500×250 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "250",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      },
      {
        "designation": "750×500×360 мм",
        "specifications": [
          {
            "label": "Вид записи",
            "value": "габаритное исполнение L×H×B без индивидуального обозначения",
            "unit": "",
            "page": 67
          },
          {
            "label": "L",
            "value": "750",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "H",
            "value": "500",
            "unit": "мм",
            "page": 67
          },
          {
            "label": "B",
            "value": "360",
            "unit": "мм",
            "page": 67
          }
        ],
        "page": 67,
        "kind": "configuration"
      }
    ],
    "familyId": "cat-rusm-5100-5400",
    "familyName": "РУСМ 5100; РУСМ 5400",
    "variantSpecs": [
      {
        "label": "Назначение",
        "value": "управление реверсивными двигателями",
        "unit": "",
        "page": 67
      }
    ]
  },
  {
    "id": "cat-ptm-tded",
    "sku": "ПТМ(Д), ТДЕ(Д)-9",
    "name": "Станции катодной защиты",
    "category": "protection",
    "subtype": "Катодная электрохимическая защита",
    "power": null,
    "voltage": "220 В; выпрямленное напряжение 24–96 В по исполнению",
    "voltageUnit": "",
    "cooling": null,
    "installation": "Климатическое исполнение У; категория размещения 1 или 3",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
    "sourceTitle": "Шкафные конструкции · 02.09.2024",
    "sourceCheckedAt": "2026-09-30",
    "sourcePages": [
      68,
      69
    ],
    "series": "ПТМ(Д), ТДЕ(Д)-9",
    "manufacturer": null,
    "manufacturers": [],
    "image": "/catalog-products/cat-ptm-tded.webp",
    "imageCaption": "Иллюстрация серии из каталога · не фото конкретного исполнения",
    "imageSourcePage": 69,
    "documentCount": 1,
    "recordType": "catalog-family",
    "recordKind": "family",
    "isOrderableSku": false,
    "description": "Для катодной электрохимической защиты подземных металлических сооружений, включая газопроводы, нефтепроводы и коммунальные объекты, от электрохимической коррозии. Преобразуют однофазный переменный ток в плавно регулируемый выпрямленный ток. Аналоги В-ОПЕ, УКЗТ-А, СКЗМ и других станций.",
    "technicalSpecs": [
      {
        "label": "Напряжение питающей сети",
        "value": "220",
        "unit": "В",
        "page": 68
      },
      {
        "label": "Частота питающей сети",
        "value": "50",
        "unit": "Гц",
        "page": 68
      },
      {
        "label": "Число фаз",
        "value": "1",
        "unit": "",
        "page": 68
      },
      {
        "label": "Предел регулирования выпрямленного напряжения от номинального",
        "value": "10–100",
        "unit": "%",
        "page": 68
      },
      {
        "label": "Коэффициент мощности",
        "value": "не менее 0,8",
        "unit": "",
        "page": 68
      },
      {
        "label": "Защитный потенциал при регулировании по разности потенциалов",
        "value": "0,8–8,0",
        "unit": "В",
        "page": 68
      },
      {
        "label": "Основная погрешность поддержания защитного потенциала",
        "value": "±2",
        "unit": "%",
        "page": 68
      },
      {
        "label": "Дополнительная погрешность на каждые 20 °C отклонения температуры",
        "value": "не более ±1",
        "unit": "%",
        "page": 68
      },
      {
        "label": "Дополнительная погрешность при изменении напряжения питающей сети",
        "value": "±0,5",
        "unit": "%",
        "page": 68
      },
      {
        "label": "Входное сопротивление измерительного блока при регулировании по разности потенциалов",
        "value": "не менее 0,1",
        "unit": "МОм",
        "page": 68
      },
      {
        "label": "Габаритные размеры ТДЕ В×Ш×Г",
        "value": "650×700×330",
        "unit": "мм",
        "page": 68
      }
    ],
    "notes": [
      "На странице 68 есть явные ошибки набора в обозначениях и мощности; спорные строки сохранены буквально.",
      "КПД исполнения 5,0 кВт в таблице не заполнен.",
      "Страница 69 содержит схему и размерные чертежи ПТМ(Д)-У1 и ТДЕ(Д)-9-У3, это технические иллюстрации.",
      "В заголовках таблицы буквально напечатаны «ТДЕД-9-го» и «ТДЕД-?-3,0», а выходная мощность колонки 3,0 дана «,03». Сохранены как напечатано; не исправлять без производителя. Строка напряжения режима 2 для колонки 2,0 содержит 96 В, несмотря на ток 42 А; не исправлена.",
      "КПД исполнения 5,0 кВт отсутствует; не выдуман."
    ],
    "variantIds": [
      "cat-ptm-tded-v001",
      "cat-ptm-tded-v002",
      "cat-ptm-tded-v003",
      "cat-ptm-tded-v004",
      "cat-ptm-tded-v005",
      "cat-ptm-tded-v006",
      "cat-ptm-tded-v007",
      "cat-ptm-tded-v008",
      "cat-ptm-tded-v009",
      "cat-ptm-tded-v010",
      "cat-ptm-tded-v011",
      "cat-ptm-tded-v012",
      "cat-ptm-tded-v013"
    ],
    "configurations": []
  }
];
export default data;
