import Link from 'next/link';
import PageIntro from '@/components/public/PageIntro';
import SourceNote from '@/components/public/SourceNote';
import ProjectCTA from '@/components/public/ProjectCTA';
import { offices } from '@/lib/public/content';
export const metadata = { title: 'Контакты', description: 'Официальные каналы связи ALAGEUM Electric: отдел продаж, публичный сайт и подготовка запроса по оборудованию.' };
export default function ContactsPage() {
 return <div className="site-container site-info-page"><PageIntro label="Контакты" title={<>Ваш проект.<br />Наш следующий разговор.</>} description="Свяжитесь с отделом продаж или сначала подготовьте список оборудования и исходные данные." /><section className="public-contact-grid"><article className="public-contact-primary"><p className="site-eyebrow">ОТДЕЛ ПРОДАЖ</p><h2>Поговорим<br />об оборудовании</h2><a className="public-contact-link" href="tel:+77710052222">+7 771 005 22 22</a><a className="public-contact-link" href="mailto:sales@alageum.com">sales@alageum.com</a><p>Телефон и почта опубликованы на официальном сайте группы. Срок ответа и часы работы здесь не заявлены.</p></article><div className="public-contact-secondary"><div><p className="site-eyebrow">ПЕРЕД ОБРАЩЕНИЕМ</p><h3>Подготовьте исходные данные</h3><p>Направление проекта, параметры оборудования, количество, место поставки и желаемый срок. Реквизиты и финансовые документы передавайте только по согласованному защищённому каналу.</p></div><div><p className="site-eyebrow">ПРОВЕРЕННЫЙ ИСТОЧНИК</p><h3>Официальный сайт группы</h3><a className="site-text-link" href="https://alageum.com/ru" target="_blank" rel="noopener noreferrer">alageum.com ↗</a></div></div></section><SourceNote href="https://alageum.com/ru/kontakty">Официальная контактная страница</SourceNote><section className="public-section"><div className="home-section-heading"><p className="site-eyebrow">РЕГИОНАЛЬНЫЕ КАНАЛЫ</p><h2>Отделы продаж</h2></div><div className="public-grid three">{offices.map(office => <article className="public-card" key={office.city}><p className="site-eyebrow">КАЗАХСТАН</p><h3>{office.city}</h3><p>{office.address}</p><a className="site-text-link" href={`tel:${office.tel}`}>{office.phone}</a><a className="site-text-link" href={`mailto:${office.email}`}>{office.email}</a></article>)}</div></section><ProjectCTA title="Отправная точка для диалога" text="Подготовьте текст обращения с нужными позициями. Перед передачей вы сможете его проверить." /><section className="public-section"><h2 className="public-section-title">Полезные разделы</h2><div className="public-grid three"><Link className="public-shortcut" href="/manufacturers"><span>Предприятия группы</span><span aria-hidden="true">↗</span></Link><Link className="public-shortcut" href="/documents"><span>Каталоги и документы</span><span aria-hidden="true">↗</span></Link><Link className="public-shortcut" href="/workspace"><span>Демо-кабинет проекта</span><span aria-hidden="true">↗</span></Link></div></section></div>;
}
