import Link from 'next/link';
import PageIntro from '@/components/public/PageIntro';
import SourceNote from '@/components/public/SourceNote';
import OfficeDirectory from '@/components/public/OfficeDirectory';
import { contactSource } from '@/lib/public/company';
import '../company-pages.css';
export const metadata = { title: 'Связаться с менеджером', description: 'Единый отдел продаж и региональные контакты ALAGEUM Electric. Телефоны, адреса, электронная почта и подготовка запроса по оборудованию.' };
export default function ContactsPage() {
  return <div className="corp-page site-container site-info-page"><PageIntro label="Контакты" title={<>Есть задача?<br /><span className="corp-heading-muted">Давайте обсудим.</span></>} description="Начните с единого отдела продаж или выберите региональный контакт. Поможем направить ваш запрос по оборудованию." />
    <section className="corp-contact-hero" aria-labelledby="contact-sales-title"><article className="corp-contact-main"><p className="site-eyebrow">01 / ЕДИНЫЙ ОТДЕЛ ПРОДАЖ</p><h2 id="contact-sales-title">На связи.<br />По делу.</h2><a href="tel:+77710052222" className="corp-contact-phone">+7 771 005 22 22 <span aria-hidden="true">↗</span></a><a href="mailto:sales@alageum.com" className="corp-contact-email">sales@alageum.com <span aria-hidden="true">↗</span></a><p>Общие вопросы по оборудованию и направлению запроса</p></article><aside className="corp-contact-prepare"><span className="site-eyebrow">ЧТОБЫ РАЗГОВОР БЫЛ ПРЕДМЕТНЫМ</span><h3>Начнём<br />с исходных данных</h3><ol><li><span>01</span>Задача и тип оборудования</li><li><span>02</span>Параметры и количество</li><li><span>03</span>Место и желаемый срок поставки</li></ol><Link href="/inquiry" className="site-button site-button-primary">Подготовить запрос <span aria-hidden="true">↗</span></Link><p>Вы проверите текст перед передачей. Форма не отправляет заявку на сервер; почтовая ссылка открывает вашу почтовую программу.</p></aside></section>
    <div className="corp-contact-shortcuts"><a href="#offices"><span>Найти региональный отдел</span><b aria-hidden="true">↓</b></a><Link href="/manufacturers"><span>Связаться с предприятием</span><b aria-hidden="true">↗</b></Link><a href="mailto:pr@alageum.com"><span>Для СМИ: pr@alageum.com</span><b aria-hidden="true">↗</b></a></div>
    <OfficeDirectory /><SourceNote href={contactSource} checkedAt="01.10.2026">Контакты на официальном сайте ALAGEUM Electric</SourceNote>
    <section className="corp-contact-faq"><div><p className="site-eyebrow">ПОЛЕЗНО ЗНАТЬ</p><h2>Перед обращением</h2></div><div className="public-faq"><details><summary>Как передать подборку оборудования?</summary><p>Сохраните нужные позиции в каталоге и перейдите в раздел «Подготовить запрос». Проверьте текст, скопируйте его или откройте в почтовой программе. Отправка выполняется вами самостоятельно.</p><Link className="site-text-link" href="/selection">Моя подборка <span aria-hidden="true">→</span></Link></details><details><summary>Можно ли приехать на предприятие?</summary><p>Сначала уточните адрес, часы приёма и порядок посещения по контактам выбранного предприятия. Отдел продаж и производственная площадка могут находиться по разным адресам.</p></details><details><summary>Куда направить реквизиты и документы?</summary><p>Согласуйте канал передачи с менеджером. Не вводите банковские данные и конфиденциальные документы в тестовую версию сайта. Выбранные в форме файлы не загружаются на сервер.</p></details></div></section>
    <p className="corp-small-note corp-end-note">Контакты перепроверены 1 октября 2026 года. Часы работы, срок ответа и персональный менеджер уточняются при обращении.</p>
  </div>;
}
