// Generated by scripts/complete-catalog-identities.mjs.
const data = [
  {
    "id": "alageum-2026-ntmi-10",
    "canonicalId": "ntmi-10",
    "relation": "same_catalog_model",
    "representation": "alias",
    "designation": "НТМИ-10",
    "execution": "измерительный",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      96
    ],
    "sourceRow": {
      "page": 96,
      "designation": "НТМИ-10",
      "execution": "измерительный",
      "kind": "explicit-model-row"
    },
    "sourceFamilyId": "ntmi",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "ВН",
        "value": "10",
        "unit": "кВ",
        "page": 96
      },
      {
        "label": "НН основная",
        "value": "0,1",
        "unit": "кВ",
        "page": 96
      },
      {
        "label": "НН дополнительная",
        "value": "0,1/3",
        "unit": "кВ",
        "page": 96
      },
      {
        "label": "Мощность в классе0,5",
        "value": "150",
        "unit": "ВА",
        "page": 96
      },
      {
        "label": "Мощность в классе1,0",
        "value": "300",
        "unit": "ВА",
        "page": 96
      },
      {
        "label": "Мощность в классе3,0",
        "value": "500",
        "unit": "ВА",
        "page": 96
      },
      {
        "label": "Максимальная(предельная) мощность",
        "value": "1000",
        "unit": "кВА",
        "page": 96
      },
      {
        "label": "H",
        "value": "486",
        "unit": "мм",
        "page": 96
      },
      {
        "label": "Масса",
        "value": "85",
        "unit": "кг",
        "page": 96
      },
      {
        "label": "Сеть",
        "value": "переменный ток с изолированной нейтралью",
        "unit": "",
        "page": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96",
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, взрывоопасная и агрессивная среда",
        "unit": "",
        "page": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96",
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "familySpecs": [],
    "description": "",
    "rawSourceSpecs": [
      {
        "label": "ВН",
        "raw": "10",
        "unitAsPrinted": "кВ",
        "sourcePage": 96
      },
      {
        "label": "НН основная",
        "raw": "0,1",
        "unitAsPrinted": "кВ",
        "sourcePage": 96
      },
      {
        "label": "НН дополнительная",
        "raw": "0,1/3",
        "unitAsPrinted": "кВ",
        "sourcePage": 96
      },
      {
        "label": "Мощность в классе0,5",
        "raw": "150",
        "unitAsPrinted": "ВА",
        "sourcePage": 96
      },
      {
        "label": "Мощность в классе1,0",
        "raw": "300",
        "unitAsPrinted": "ВА",
        "sourcePage": 96
      },
      {
        "label": "Мощность в классе3,0",
        "raw": "500",
        "unitAsPrinted": "ВА",
        "sourcePage": 96
      },
      {
        "label": "Максимальная(предельная) мощность",
        "raw": "1000",
        "unitAsPrinted": "кВА",
        "sourcePage": 96
      },
      {
        "label": "H",
        "raw": "486",
        "unitAsPrinted": "мм",
        "sourcePage": 96
      },
      {
        "label": "Масса",
        "raw": "85",
        "unitAsPrinted": "кг",
        "sourcePage": 96
      },
      {
        "label": "Сеть",
        "raw": "переменный ток с изолированной нейтралью",
        "unitAsPrinted": null,
        "sourcePage": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96"
      },
      {
        "label": "Исключенные условия работы",
        "raw": "тряска, вибрация, удары, взрывоопасная и агрессивная среда",
        "unitAsPrinted": null,
        "sourcePage": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96"
      }
    ],
    "configurations": [],
    "power": null,
    "manufacturer": null,
    "notes": [
      "Maximum power unit printed кВА and values630/1000, unlike adjacent rated VA; retain suspected source unit error.",
      "Максимальная мощность: каталог печатает кВА, сайт — ВА; числа совпадают. Заголовок номинальной мощности на сайте печатает кА, каталог — ВА. Единицы сохранены по источникам; нормализованная мощность в кВА не определена."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/ntmi",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "Hmm",
          "legacySourceValue": "486",
          "newCatalogValue": "486",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "H",
          "newUnit": "мм",
          "legacyUnit": "мм"
        },
        {
          "field": "massKg",
          "legacySourceValue": "85",
          "newCatalogValue": "85",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "hvKv",
          "legacySourceValue": "10",
          "newCatalogValue": "10",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "ВН",
          "newUnit": "кВ",
          "legacyUnit": "кВ"
        },
        {
          "field": "lvKv",
          "legacySourceValue": "0,1",
          "newCatalogValue": "0,1",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "НН основная",
          "newUnit": "кВ",
          "legacyUnit": "кВ"
        },
        {
          "field": "additionalLvKv",
          "legacySourceValue": "0,1/3",
          "newCatalogValue": "0,1/3",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "НН дополнительная",
          "newUnit": "кВ",
          "legacyUnit": "кВ"
        },
        {
          "field": "class05VA",
          "legacySourceValue": "150",
          "newCatalogValue": "150",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Мощность в классе 0,5",
          "newUnit": "ВА",
          "legacyUnit": "кА (заголовок сайта)"
        },
        {
          "field": "class10VA",
          "legacySourceValue": "300",
          "newCatalogValue": "300",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Мощность в классе 1,0",
          "newUnit": "ВА",
          "legacyUnit": "кА (заголовок сайта)"
        },
        {
          "field": "class30VA",
          "legacySourceValue": "500",
          "newCatalogValue": "500",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Мощность в классе 3,0",
          "newUnit": "ВА",
          "legacyUnit": "кА (заголовок сайта)"
        },
        {
          "field": "maximumPowerValue",
          "legacySourceValue": "1000",
          "newCatalogValue": "1000",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Максимальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "ВА"
        }
      ],
      "conflicts": [
        {
          "field": "maximumPowerUnit",
          "legacySourceValue": "ВА",
          "newCatalogValue": "кВА",
          "newSourcePage": 96,
          "status": "unit conflict; numerical value matches",
          "label": "Единица максимальной мощности"
        },
        {
          "field": "ratedPowerHeader",
          "legacySourceValue": "кА",
          "newCatalogValue": "ВА",
          "newSourcePage": 96,
          "status": "legacy web header is also inconsistent; retain provenance",
          "label": "Заголовок номинальной мощности"
        }
      ],
      "unresolved": "Resolve contradictory printed units only if a single normalized field is required; this does not block identity or source-backed descriptive publication.",
      "finding": "exact_catalog_model_match_with_field_unit_conflicts",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/ntmi",
          "locator": "НТМИ-10 row; first and continuation tables",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            96
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-046-101/models-018.json"
        }
      ]
    }
  },
  {
    "id": "alageum-2026-ntmi-6",
    "canonicalId": "ntmi-6",
    "relation": "same_catalog_model",
    "representation": "alias",
    "designation": "НТМИ-6",
    "execution": "измерительный",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      96
    ],
    "sourceRow": {
      "page": 96,
      "designation": "НТМИ-6",
      "execution": "измерительный",
      "kind": "explicit-model-row"
    },
    "sourceFamilyId": "ntmi",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "ВН",
        "value": "6",
        "unit": "кВ",
        "page": 96
      },
      {
        "label": "НН основная",
        "value": "0,1",
        "unit": "кВ",
        "page": 96
      },
      {
        "label": "НН дополнительная",
        "value": "0,1/3",
        "unit": "кВ",
        "page": 96
      },
      {
        "label": "Мощность в классе0,5",
        "value": "75",
        "unit": "ВА",
        "page": 96
      },
      {
        "label": "Мощность в классе1,0",
        "value": "150",
        "unit": "ВА",
        "page": 96
      },
      {
        "label": "Мощность в классе3,0",
        "value": "300",
        "unit": "ВА",
        "page": 96
      },
      {
        "label": "Максимальная(предельная) мощность",
        "value": "630",
        "unit": "кВА",
        "page": 96
      },
      {
        "label": "H",
        "value": "396",
        "unit": "мм",
        "page": 96
      },
      {
        "label": "Масса",
        "value": "80",
        "unit": "кг",
        "page": 96
      },
      {
        "label": "Сеть",
        "value": "переменный ток с изолированной нейтралью",
        "unit": "",
        "page": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96",
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, взрывоопасная и агрессивная среда",
        "unit": "",
        "page": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96",
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "familySpecs": [],
    "description": "",
    "rawSourceSpecs": [
      {
        "label": "ВН",
        "raw": "6",
        "unitAsPrinted": "кВ",
        "sourcePage": 96
      },
      {
        "label": "НН основная",
        "raw": "0,1",
        "unitAsPrinted": "кВ",
        "sourcePage": 96
      },
      {
        "label": "НН дополнительная",
        "raw": "0,1/3",
        "unitAsPrinted": "кВ",
        "sourcePage": 96
      },
      {
        "label": "Мощность в классе0,5",
        "raw": "75",
        "unitAsPrinted": "ВА",
        "sourcePage": 96
      },
      {
        "label": "Мощность в классе1,0",
        "raw": "150",
        "unitAsPrinted": "ВА",
        "sourcePage": 96
      },
      {
        "label": "Мощность в классе3,0",
        "raw": "300",
        "unitAsPrinted": "ВА",
        "sourcePage": 96
      },
      {
        "label": "Максимальная(предельная) мощность",
        "raw": "630",
        "unitAsPrinted": "кВА",
        "sourcePage": 96
      },
      {
        "label": "H",
        "raw": "396",
        "unitAsPrinted": "мм",
        "sourcePage": 96
      },
      {
        "label": "Масса",
        "raw": "80",
        "unitAsPrinted": "кг",
        "sourcePage": 96
      },
      {
        "label": "Сеть",
        "raw": "переменный ток с изолированной нейтралью",
        "unitAsPrinted": null,
        "sourcePage": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96"
      },
      {
        "label": "Исключенные условия работы",
        "raw": "тряска, вибрация, удары, взрывоопасная и агрессивная среда",
        "unitAsPrinted": null,
        "sourcePage": 96,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-15-p96"
      }
    ],
    "configurations": [],
    "power": null,
    "manufacturer": null,
    "notes": [
      "Maximum power unit printed кВА and values630/1000, unlike adjacent rated VA; retain suspected source unit error.",
      "Максимальная мощность: каталог печатает кВА, сайт — ВА; числа совпадают. Заголовок номинальной мощности на сайте печатает кА, каталог — ВА. Единицы сохранены по источникам; нормализованная мощность в кВА не определена."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/ntmi",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "Hmm",
          "legacySourceValue": "396",
          "newCatalogValue": "396",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "H",
          "newUnit": "мм",
          "legacyUnit": "мм"
        },
        {
          "field": "massKg",
          "legacySourceValue": "80",
          "newCatalogValue": "80",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "hvKv",
          "legacySourceValue": "6",
          "newCatalogValue": "6",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "ВН",
          "newUnit": "кВ",
          "legacyUnit": "кВ"
        },
        {
          "field": "lvKv",
          "legacySourceValue": "0,1",
          "newCatalogValue": "0,1",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "НН основная",
          "newUnit": "кВ",
          "legacyUnit": "кВ"
        },
        {
          "field": "additionalLvKv",
          "legacySourceValue": "0,1/3",
          "newCatalogValue": "0,1/3",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "НН дополнительная",
          "newUnit": "кВ",
          "legacyUnit": "кВ"
        },
        {
          "field": "class05VA",
          "legacySourceValue": "75",
          "newCatalogValue": "75",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Мощность в классе 0,5",
          "newUnit": "ВА",
          "legacyUnit": "кА (заголовок сайта)"
        },
        {
          "field": "class10VA",
          "legacySourceValue": "150",
          "newCatalogValue": "150",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Мощность в классе 1,0",
          "newUnit": "ВА",
          "legacyUnit": "кА (заголовок сайта)"
        },
        {
          "field": "class30VA",
          "legacySourceValue": "300",
          "newCatalogValue": "300",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Мощность в классе 3,0",
          "newUnit": "ВА",
          "legacyUnit": "кА (заголовок сайта)"
        },
        {
          "field": "maximumPowerValue",
          "legacySourceValue": "630",
          "newCatalogValue": "630",
          "newSourcePage": 96,
          "comparison": "match",
          "label": "Максимальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "ВА"
        }
      ],
      "conflicts": [
        {
          "field": "maximumPowerUnit",
          "legacySourceValue": "ВА",
          "newCatalogValue": "кВА",
          "newSourcePage": 96,
          "status": "unit conflict; numerical value matches",
          "label": "Единица максимальной мощности"
        },
        {
          "field": "ratedPowerHeader",
          "legacySourceValue": "кА",
          "newCatalogValue": "ВА",
          "newSourcePage": 96,
          "status": "legacy web header is also inconsistent; retain provenance",
          "label": "Заголовок номинальной мощности"
        }
      ],
      "unresolved": "Resolve contradictory printed units only if a single normalized field is required; this does not block identity or source-backed descriptive publication.",
      "finding": "exact_catalog_model_match_with_field_unit_conflicts",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/ntmi",
          "locator": "НТМИ-6 row; first and continuation tables",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            96
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-046-101/models-018.json"
        }
      ]
    }
  },
  {
    "id": "alageum-2026-thermal-cabinet",
    "canonicalId": "cat-shtz",
    "relation": "related_thermal_protection_accessory",
    "representation": "source-comparison",
    "designation": "Шкаф тепловой защиты (ШТЗ)",
    "execution": "optional",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      86
    ],
    "sourceRow": {
      "page": 86,
      "designation": "Шкаф тепловой защиты (ШТЗ)",
      "execution": "optional",
      "kind": "accessory"
    },
    "sourceFamilyId": "dry-accessories",
    "sourceRecordType": "accessory",
    "technicalSpecs": [
      {
        "label": "Контроль",
        "value": "реле ТР-100 с датчиками",
        "unit": "",
        "page": 86,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "familySpecs": [],
    "description": "",
    "rawSourceSpecs": [
      {
        "label": "Контроль",
        "raw": "реле ТР-100 с датчиками",
        "unitAsPrinted": null,
        "sourcePage": 86
      }
    ],
    "configurations": [],
    "power": null,
    "manufacturer": null,
    "notes": [
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно.",
      "Страница 86 не указывает напряжение шкафа, габариты, массу, климатическое исполнение или IP. Параметры старого каталога не перенесены в описание 2026 года."
    ],
    "comparison": {
      "legacySourceUrl": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
      "legacySourceTitle": "Шкафные конструкции · 02.09.2024",
      "legacySourcePages": [
        63
      ],
      "comparedSpecs": [],
      "conflicts": [],
      "unresolved": "Hard alias or transferring old specifications requires the manufacturer to identify the p86 cabinet execution or provide a matching drawing/nameplate.",
      "finding": "same_family_purpose_exact_cabinet_execution_unproven",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://drive.google.com/file/d/1qMKtgoDWWIjVhAwbrRd8YORKhIpSKazr/view",
          "locator": "supplied cabinet catalog p63",
          "pages": [
            63
          ]
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            86
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-046-101/models-017.json"
        }
      ]
    }
  },
  {
    "id": "alageum-2026-tmeg-250",
    "canonicalId": "tmeg-250",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМЭГ-250",
    "execution": "для питания электрооборудования экскаваторов",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      60,
      61
    ],
    "sourceRow": {
      "page": 60,
      "designation": "ТМЭГ-250",
      "execution": "для питания электрооборудования экскаваторов",
      "kind": "explicit-model-row"
    },
    "sourceFamilyId": "tmeg",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Pо",
        "value": "610",
        "unit": "Вт",
        "page": 60
      },
      {
        "label": "Pк",
        "value": "4200",
        "unit": "Вт",
        "page": 60
      },
      {
        "label": "Uк",
        "value": "4,5",
        "unit": "%",
        "page": 60
      },
      {
        "label": "Iо",
        "value": "1,9",
        "unit": "%",
        "page": 60
      },
      {
        "label": "L",
        "value": "1322",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "786",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1281",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "550",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "550",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "110",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "110",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "115",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "885",
        "unit": "кг",
        "page": 60
      },
      {
        "label": "Масса масла",
        "value": "158",
        "unit": "кг",
        "page": 60
      },
      {
        "label": "Номинальная мощность",
        "value": "250",
        "unit": "кВА",
        "page": 60
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(6,3)",
        "unit": "кВ",
        "page": 60
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0",
        "unit": "",
        "page": 60,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Охлаждение",
        "value": "естественное масляное",
        "unit": "",
        "page": 60,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-05-p60",
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Переключатель",
        "value": "без возбуждения",
        "unit": "",
        "page": 60,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-05-p60",
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Стандарт",
        "value": "ГОСТ11677",
        "unit": "",
        "page": 60,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-05-p60",
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "familySpecs": [],
    "description": "",
    "rawSourceSpecs": [
      {
        "label": "Pо",
        "raw": "610",
        "unitAsPrinted": "Вт",
        "sourcePage": 60
      },
      {
        "label": "Pк",
        "raw": "4200",
        "unitAsPrinted": "Вт",
        "sourcePage": 60
      },
      {
        "label": "Uк",
        "raw": "4,5",
        "unitAsPrinted": "%",
        "sourcePage": 60
      },
      {
        "label": "Iо",
        "raw": "1,9",
        "unitAsPrinted": "%",
        "sourcePage": 60
      },
      {
        "label": "L",
        "raw": "1322",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "B",
        "raw": "786",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "H",
        "raw": "1281",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "A",
        "raw": "550",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "A1",
        "raw": "550",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "M",
        "raw": "110",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "K",
        "raw": "230",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "h",
        "raw": "110",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "h1",
        "raw": "115",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "Полная масса",
        "raw": "885",
        "unitAsPrinted": "кг",
        "sourcePage": 60
      },
      {
        "label": "Масса масла",
        "raw": "158",
        "unitAsPrinted": "кг",
        "sourcePage": 60
      },
      {
        "label": "Номинальная мощность",
        "raw": "250",
        "unitAsPrinted": "кВА",
        "sourcePage": 60
      },
      {
        "label": "Номинальное напряжение",
        "raw": "6(6,3)",
        "unitAsPrinted": "кВ",
        "sourcePage": 60
      },
      {
        "label": "Группа соединения обмоток",
        "raw": "У/Ун-0",
        "unitAsPrinted": null,
        "sourcePage": 60
      },
      {
        "label": "Охлаждение",
        "raw": "естественное масляное",
        "unitAsPrinted": null,
        "sourcePage": 60,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-05-p60"
      },
      {
        "label": "Переключатель",
        "raw": "без возбуждения",
        "unitAsPrinted": null,
        "sourcePage": 60,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-05-p60"
      },
      {
        "label": "Стандарт",
        "raw": "ГОСТ11677",
        "unitAsPrinted": null,
        "sourcePage": 60,
        "sourceKind": "common-prose",
        "commonProseGroupId": "common-prose-05-p60"
      }
    ],
    "configurations": [],
    "power": 250,
    "manufacturer": null,
    "notes": [
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmeg",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 250,
          "newCatalogValue": "250",
          "newSourcePage": 60,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0",
          "newCatalogValue": "У/Ун-0",
          "newSourcePage": 60,
          "comparison": "match",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "4,5",
          "newCatalogValue": "4,5",
          "newSourcePage": 60,
          "comparison": "match",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "1,9",
          "newCatalogValue": "1,9",
          "newSourcePage": 60,
          "comparison": "match",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1361",
          "newCatalogValue": "1322",
          "newSourcePage": 60,
          "comparison": "different",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "786",
          "newCatalogValue": "786",
          "newSourcePage": 60,
          "comparison": "match",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1275",
          "newCatalogValue": "1281",
          "newSourcePage": 60,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "158",
          "newCatalogValue": "158",
          "newSourcePage": 60,
          "comparison": "match",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "885",
          "newCatalogValue": "885",
          "newSourcePage": 60,
          "comparison": "match",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "Lmm",
          "legacySourceValue": "1361",
          "newCatalogValue": "1322",
          "newSourcePage": 60,
          "comparison": "different",
          "label": "L"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1275",
          "newCatalogValue": "1281",
          "newSourcePage": 60,
          "comparison": "different",
          "label": "H"
        },
        {
          "field": "nominalVoltageScope",
          "legacySourceValue": "ВН 6;6,3;10;10,5 and НН 0,4 кВ",
          "newCatalogValue": "6(6,3) кВ only; no separate НН table column",
          "newSourcePage": 60,
          "status": "new source is narrower/incomplete; do not inherit legacy 10/10.5 kV or 0.4 kV",
          "label": "nominalVoltageScope"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmeg",
          "locator": "product technical table, row 250; retrieved web text line 85",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            60,
            61
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-046-101/models-007.json"
        }
      ]
    }
  },
  {
    "id": "alageum-tmg-standard-1000",
    "canonicalId": "tmg-1000",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГ-1000",
    "execution": "стандартный",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      6,
      7,
      13
    ],
    "sourceRow": {
      "designation": "ТМГ-1000",
      "electricalTablePage": 6,
      "dimensionsTablePage": 7
    },
    "sourceFamilyId": "tmg-standard",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "1000",
        "unit": "кВА",
        "page": 6
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 6
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1470",
        "unit": "Вт",
        "page": 6
      },
      {
        "label": "Рк",
        "value": "12200",
        "unit": "Вт",
        "page": 6
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "page": 6
      },
      {
        "label": "I о",
        "value": "0,8",
        "unit": "%",
        "page": 6
      },
      {
        "label": "L",
        "value": "1639",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1195",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1450",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "820",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "820",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "190",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "160",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "180",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "2230",
        "unit": "кг",
        "page": 7
      },
      {
        "label": "Масса масла",
        "value": "474",
        "unit": "кг",
        "page": 7
      }
    ],
    "familySpecs": [
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 6
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Стенки",
        "value": "гофрированные, для увеличения поверхности охлаждения и компенсации температурного расширения масла",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Расширитель / газовая подушка",
        "value": "Расширитель и воздушная или газовая «подушка» отсутствуют",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "Трехфазные силовые масляные трансформаторы; герметичное исполнение; гофрированные стенки; расширитель и воздушная или газовая подушка отсутствуют; наружная или внутренняя установка; высота не более 1000 м.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "1000",
        "unit": "кВА",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "1470",
        "unit": "Вт",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "12200",
        "unit": "Вт",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "0,8",
        "unit": "%",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1639",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "1195",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1450",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "820",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "820",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "190",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "230",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "160",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "180",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "2230",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "474",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-standard-1000-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-1000",
        "page": 6,
        "sourcePages": [
          6
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 6,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "12200",
            "unit": "Вт",
            "page": 6
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 6
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-1000-connection-1",
          "modelId": "alageum-tmg-standard-1000",
          "familyId": "tmg-standard",
          "page": 6,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "12200",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-standard-1000-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-1000",
        "page": 6,
        "sourcePages": [
          6
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 6,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "12200",
            "unit": "Вт",
            "page": 6
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 6
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-1000-connection-2",
          "modelId": "alageum-tmg-standard-1000",
          "familyId": "tmg-standard",
          "page": 6,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "12200",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 1000,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 1000,
          "newCatalogValue": "1000",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "5,5",
          "newCatalogValue": "5,5",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "0,8",
          "newCatalogValue": "0,8",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1644",
          "newCatalogValue": "1639",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "1082",
          "newCatalogValue": "1195",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1705",
          "newCatalogValue": "1450",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "510",
          "newCatalogValue": "474",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "2440",
          "newCatalogValue": "2230",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "Lmm",
          "legacySourceValue": "1644",
          "newCatalogValue": "1639",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "L"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "1082",
          "newCatalogValue": "1195",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "B"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1705",
          "newCatalogValue": "1450",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "510",
          "newCatalogValue": "474",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса масла"
        },
        {
          "field": "massKg",
          "legacySourceValue": "2440",
          "newCatalogValue": "2230",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
          "locator": "product technical table, row 1000; retrieved web text line 92",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            6,
            7,
            13
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-002.json"
        }
      ]
    }
  },
  {
    "id": "alageum-tmg-standard-2500",
    "canonicalId": "tmg-2500",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГ-2500",
    "execution": "стандартный",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      6,
      7,
      13
    ],
    "sourceRow": {
      "designation": "ТМГ-2500",
      "electricalTablePage": 7,
      "dimensionsTablePage": 7
    },
    "sourceFamilyId": "tmg-standard",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "2500",
        "unit": "кВА",
        "page": 7
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 7
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "2770",
        "unit": "Вт",
        "page": 7
      },
      {
        "label": "Рк",
        "value": "28000",
        "unit": "Вт",
        "page": 7
      },
      {
        "label": "U к",
        "value": "6,5",
        "unit": "%",
        "page": 7
      },
      {
        "label": "I о",
        "value": "0,4",
        "unit": "%",
        "page": 7
      },
      {
        "label": "L",
        "value": "1976",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1325",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1970",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "1070",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "1070",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "145",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "260",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "160",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "235",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "4505",
        "unit": "кг",
        "page": 7
      },
      {
        "label": "Масса масла",
        "value": "880",
        "unit": "кг",
        "page": 7
      }
    ],
    "familySpecs": [
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 6
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Стенки",
        "value": "гофрированные, для увеличения поверхности охлаждения и компенсации температурного расширения масла",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Расширитель / газовая подушка",
        "value": "Расширитель и воздушная или газовая «подушка» отсутствуют",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "Трехфазные силовые масляные трансформаторы; герметичное исполнение; гофрированные стенки; расширитель и воздушная или газовая подушка отсутствуют; наружная или внутренняя установка; высота не более 1000 м.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "2500",
        "unit": "кВА",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "2770",
        "unit": "Вт",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "28000",
        "unit": "Вт",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "6,5",
        "unit": "%",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "0,4",
        "unit": "%",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1976",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "1325",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1970",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "1070",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "1070",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "145",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "260",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "160",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "235",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "4505",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "880",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-standard-2500-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-2500",
        "page": 7,
        "sourcePages": [
          7
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 7,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "28000",
            "unit": "Вт",
            "page": 7
          },
          {
            "label": "U к",
            "value": "6,5",
            "unit": "%",
            "page": 7
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-2500-connection-1",
          "modelId": "alageum-tmg-standard-2500",
          "familyId": "tmg-standard",
          "page": 7,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "28000",
          "UkPercentRaw": "6,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-standard-2500-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-2500",
        "page": 7,
        "sourcePages": [
          7
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 7,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "28000",
            "unit": "Вт",
            "page": 7
          },
          {
            "label": "U к",
            "value": "6,5",
            "unit": "%",
            "page": 7
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-2500-connection-2",
          "modelId": "alageum-tmg-standard-2500",
          "familyId": "tmg-standard",
          "page": 7,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "28000",
          "UkPercentRaw": "6,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 2500,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 2500,
          "newCatalogValue": "2500",
          "newSourcePage": 7,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 7,
          "comparison": "match",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "6,5",
          "newCatalogValue": "6,5",
          "newSourcePage": 7,
          "comparison": "match",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "0,4",
          "newCatalogValue": "0,4",
          "newSourcePage": 7,
          "comparison": "match",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "2247",
          "newCatalogValue": "1976",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "1390",
          "newCatalogValue": "1325",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "2155",
          "newCatalogValue": "1970",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "1165",
          "newCatalogValue": "880",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "5390",
          "newCatalogValue": "4505",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "Lmm",
          "legacySourceValue": "2247",
          "newCatalogValue": "1976",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "L"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "1390",
          "newCatalogValue": "1325",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "B"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "2155",
          "newCatalogValue": "1970",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "1165",
          "newCatalogValue": "880",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса масла"
        },
        {
          "field": "massKg",
          "legacySourceValue": "5390",
          "newCatalogValue": "4505",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
          "locator": "product technical table, row 2500; retrieved web text line 96",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            7,
            13
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-002.json"
        }
      ]
    }
  }
];
export default data;
