// Generated by scripts/complete-catalog-identities.mjs.
const data = [
  {
    "id": "alageum-tmg-standard-400",
    "canonicalId": "tmg-400",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГ-400",
    "execution": "стандартный",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      6,
      7,
      12
    ],
    "sourceRow": {
      "designation": "ТМГ-400",
      "electricalTablePage": 6,
      "dimensionsTablePage": 7
    },
    "sourceFamilyId": "tmg-standard",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "400",
        "unit": "кВА",
        "page": 6
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 6
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "780",
        "unit": "Вт",
        "page": 6
      },
      {
        "label": "Рк",
        "value": "5500\n5900",
        "unit": "Вт",
        "page": 6
      },
      {
        "label": "U к",
        "value": "4,5",
        "unit": "%",
        "page": 6
      },
      {
        "label": "I о",
        "value": "1,4",
        "unit": "%",
        "page": 6
      },
      {
        "label": "L",
        "value": "1309",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "774",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1295",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "660",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "150",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "130",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "130",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "1165",
        "unit": "кг",
        "page": 7
      },
      {
        "label": "Масса масла",
        "value": "230",
        "unit": "кг",
        "page": 7
      }
    ],
    "familySpecs": [
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 6
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Стенки",
        "value": "гофрированные, для увеличения поверхности охлаждения и компенсации температурного расширения масла",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Расширитель / газовая подушка",
        "value": "Расширитель и воздушная или газовая «подушка» отсутствуют",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "Трехфазные силовые масляные трансформаторы; герметичное исполнение; гофрированные стенки; расширитель и воздушная или газовая подушка отсутствуют; наружная или внутренняя установка; высота не более 1000 м.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "400",
        "unit": "кВА",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "780",
        "unit": "Вт",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "5500\n5900",
        "unit": "Вт",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "4,5",
        "unit": "%",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "1,4",
        "unit": "%",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1309",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "774",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1295",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "660",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "150",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "230",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "130",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "130",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "1165",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "230",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-standard-400-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-400",
        "page": 6,
        "sourcePages": [
          6
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 6,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "5500",
            "unit": "Вт",
            "page": 6
          },
          {
            "label": "U к",
            "value": "4,5",
            "unit": "%",
            "page": 6
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-400-connection-1",
          "modelId": "alageum-tmg-standard-400",
          "familyId": "tmg-standard",
          "page": 6,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "5500",
          "UkPercentRaw": "4,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-standard-400-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-400",
        "page": 6,
        "sourcePages": [
          6
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 6,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "5900",
            "unit": "Вт",
            "page": 6
          },
          {
            "label": "U к",
            "value": "4,5",
            "unit": "%",
            "page": 6
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-400-connection-2",
          "modelId": "alageum-tmg-standard-400",
          "familyId": "tmg-standard",
          "page": 6,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "5900",
          "UkPercentRaw": "4,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 400,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 400,
          "newCatalogValue": "400",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;У/Zн-11;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "4,5",
          "newCatalogValue": "4,5",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "1,4",
          "newCatalogValue": "1,4",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1294",
          "newCatalogValue": "1309",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "762",
          "newCatalogValue": "774",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1250",
          "newCatalogValue": "1295",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "230",
          "newCatalogValue": "230",
          "newSourcePage": 7,
          "comparison": "match",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "1165",
          "newCatalogValue": "1165",
          "newSourcePage": 7,
          "comparison": "match",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;У/Zн-11;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "Группа соединения обмоток"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1294",
          "newCatalogValue": "1309",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "L"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "762",
          "newCatalogValue": "774",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "B"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1250",
          "newCatalogValue": "1295",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
          "locator": "product technical table, row 400; retrieved web text line 90",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            6,
            7,
            12
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-002.json"
        }
      ]
    }
  },
  {
    "id": "alageum-tmg-standard-630",
    "canonicalId": "tmg-630",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГ-630",
    "execution": "стандартный",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      6,
      7,
      12
    ],
    "sourceRow": {
      "designation": "ТМГ-630",
      "electricalTablePage": 6,
      "dimensionsTablePage": 7
    },
    "sourceFamilyId": "tmg-standard",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "630",
        "unit": "кВА",
        "page": 6
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 6
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1070",
        "unit": "Вт",
        "page": 6
      },
      {
        "label": "Рк",
        "value": "7900\n8500",
        "unit": "Вт",
        "page": 6
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "page": 6
      },
      {
        "label": "I о",
        "value": "1,0",
        "unit": "%",
        "page": 6
      },
      {
        "label": "L",
        "value": "1421",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1023",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1305",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "660",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "170",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "185",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "170",
        "unit": "",
        "page": 7,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "1580",
        "unit": "кг",
        "page": 7
      },
      {
        "label": "Масса масла",
        "value": "328",
        "unit": "кг",
        "page": 7
      }
    ],
    "familySpecs": [
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 6
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 6
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Стенки",
        "value": "гофрированные, для увеличения поверхности охлаждения и компенсации температурного расширения масла",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Расширитель / газовая подушка",
        "value": "Расширитель и воздушная или газовая «подушка» отсутствуют",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 6,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "Трехфазные силовые масляные трансформаторы; герметичное исполнение; гофрированные стенки; расширитель и воздушная или газовая подушка отсутствуют; наружная или внутренняя установка; высота не более 1000 м.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "630",
        "unit": "кВА",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "1070",
        "unit": "Вт",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "7900\n8500",
        "unit": "Вт",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "1,0",
        "unit": "%",
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1421",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "1023",
        "unit": null,
        "pdfPage": 6,
        "printedPage": "6",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1305",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "660",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "170",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "230",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "185",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "170",
        "unit": null,
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "1580",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "328",
        "unit": "кг",
        "pdfPage": 7,
        "printedPage": "7",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-standard-630-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-630",
        "page": 6,
        "sourcePages": [
          6
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 6,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "7900",
            "unit": "Вт",
            "page": 6
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 6
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-630-connection-1",
          "modelId": "alageum-tmg-standard-630",
          "familyId": "tmg-standard",
          "page": 6,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "7900",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-standard-630-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-standard-630",
        "page": 6,
        "sourcePages": [
          6
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 6,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "8500",
            "unit": "Вт",
            "page": 6
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 6
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-standard-630-connection-2",
          "modelId": "alageum-tmg-standard-630",
          "familyId": "tmg-standard",
          "page": 6,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "8500",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 630,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 630,
          "newCatalogValue": "630",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;У/Zн-11;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "5,5",
          "newCatalogValue": "5,5",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "1,0",
          "newCatalogValue": "1,0",
          "newSourcePage": 6,
          "comparison": "match",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1422",
          "newCatalogValue": "1421",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "868",
          "newCatalogValue": "1023",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1465",
          "newCatalogValue": "1305",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "380",
          "newCatalogValue": "328",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "1655",
          "newCatalogValue": "1580",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;У/Zн-11;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "Группа соединения обмоток"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1422",
          "newCatalogValue": "1421",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "L"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "868",
          "newCatalogValue": "1023",
          "newSourcePage": 6,
          "comparison": "different",
          "label": "B"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1465",
          "newCatalogValue": "1305",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "H"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "380",
          "newCatalogValue": "328",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса масла"
        },
        {
          "field": "massKg",
          "legacySourceValue": "1655",
          "newCatalogValue": "1580",
          "newSourcePage": 7,
          "comparison": "different",
          "label": "Масса"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmg-25-2500-6-10-kv-2-2",
          "locator": "product technical table, row 630; retrieved web text line 91",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            6,
            7,
            12
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-002.json"
        }
      ]
    }
  },
  {
    "id": "alageum-tmgf-1600",
    "canonicalId": "tmgf-1600",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГФ-1600",
    "execution": "",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      38,
      39
    ],
    "sourceRow": {
      "designation": "ТМГФ-1600",
      "electricalTablePage": 38,
      "dimensionsTablePage": 38
    },
    "sourceFamilyId": "tmgf",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "1600",
        "unit": "кВА",
        "page": 38
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 38
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1750",
        "unit": "Вт",
        "page": 38
      },
      {
        "label": "Рк",
        "value": "18200",
        "unit": "Вт",
        "page": 38
      },
      {
        "label": "U к",
        "value": "6,0",
        "unit": "%",
        "page": 38
      },
      {
        "label": "I о",
        "value": "0,5",
        "unit": "%",
        "page": 38
      },
      {
        "label": "L",
        "value": "1952",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1260",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "2078",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "3863",
        "unit": "кг",
        "page": 38
      },
      {
        "label": "Масса масла",
        "value": "1015",
        "unit": "кг",
        "page": 38
      }
    ],
    "familySpecs": [
      {
        "label": "Климатическое исполнение",
        "value": "У1 и УХЛ1",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Установка",
        "value": "в открытых электроустановках",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "Масляная серия ТМГФ для открытых электроустановок; У1 и УХЛ1; 6 или 10 кВ.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "1600",
        "unit": "кВА",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "1750",
        "unit": "Вт",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "18200",
        "unit": "Вт",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "6,0",
        "unit": "%",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "0,5",
        "unit": "%",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1952",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "1260",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "2078",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "3863",
        "unit": "кг",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "1015",
        "unit": "кг",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmgf-1600-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgf-1600",
        "page": 38,
        "sourcePages": [
          38
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 38,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "18200",
            "unit": "Вт",
            "page": 38
          },
          {
            "label": "U к",
            "value": "6,0",
            "unit": "%",
            "page": 38
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgf-1600-connection-1",
          "modelId": "alageum-tmgf-1600",
          "familyId": "tmgf",
          "page": 38,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "18200",
          "UkPercentRaw": "6,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmgf-1600-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgf-1600",
        "page": 38,
        "sourcePages": [
          38
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 38,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "18200",
            "unit": "Вт",
            "page": 38
          },
          {
            "label": "U к",
            "value": "6,0",
            "unit": "%",
            "page": 38
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgf-1600-connection-2",
          "modelId": "alageum-tmgf-1600",
          "familyId": "tmgf",
          "page": 38,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "18200",
          "UkPercentRaw": "6,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 1600,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgf-6-10-kv",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 1600,
          "newCatalogValue": "1600",
          "newSourcePage": 38,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 38,
          "comparison": "match",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "6,0",
          "newCatalogValue": "6,0",
          "newSourcePage": 38,
          "comparison": "match",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "0,8",
          "newCatalogValue": "0,5",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "2100",
          "newCatalogValue": "1952",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "1270",
          "newCatalogValue": "1260",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "2165",
          "newCatalogValue": "2078",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "1100",
          "newCatalogValue": "1015",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "4500",
          "newCatalogValue": "3863",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "I0Pct",
          "legacySourceValue": "0,8",
          "newCatalogValue": "0,5",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Ток холостого хода"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "2100",
          "newCatalogValue": "1952",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "L"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "1270",
          "newCatalogValue": "1260",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "B"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "2165",
          "newCatalogValue": "2078",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "H"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "1100",
          "newCatalogValue": "1015",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса масла"
        },
        {
          "field": "massKg",
          "legacySourceValue": "4500",
          "newCatalogValue": "3863",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmgf-6-10-kv",
          "locator": "product technical table, row 1600; retrieved web text line 85",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            38,
            39
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-016.json"
        }
      ]
    }
  },
  {
    "id": "alageum-tmgf-630",
    "canonicalId": "tmgf-630",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГФ-630",
    "execution": "",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      38,
      39
    ],
    "sourceRow": {
      "designation": "ТМГФ-630",
      "electricalTablePage": 38,
      "dimensionsTablePage": 38
    },
    "sourceFamilyId": "tmgf",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "630",
        "unit": "кВА",
        "page": 38
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 38
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1070",
        "unit": "Вт",
        "page": 38
      },
      {
        "label": "Рк",
        "value": "8600",
        "unit": "Вт",
        "page": 38
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "page": 38
      },
      {
        "label": "I о",
        "value": "1,0",
        "unit": "%",
        "page": 38
      },
      {
        "label": "L",
        "value": "1440",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "890",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1610",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "1800",
        "unit": "кг",
        "page": 38
      },
      {
        "label": "Масса масла",
        "value": "500",
        "unit": "кг",
        "page": 38
      }
    ],
    "familySpecs": [
      {
        "label": "Климатическое исполнение",
        "value": "У1 и УХЛ1",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Установка",
        "value": "в открытых электроустановках",
        "unit": "",
        "page": 38,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "Масляная серия ТМГФ для открытых электроустановок; У1 и УХЛ1; 6 или 10 кВ.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "630",
        "unit": "кВА",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "1070",
        "unit": "Вт",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "8600",
        "unit": "Вт",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "1,0",
        "unit": "%",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1440",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "890",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1610",
        "unit": null,
        "pdfPage": 38,
        "printedPage": "38",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "1800",
        "unit": "кг",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "500",
        "unit": "кг",
        "pdfPage": 38,
        "printedPage": "38",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmgf-630-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgf-630",
        "page": 38,
        "sourcePages": [
          38
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 38,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "8600",
            "unit": "Вт",
            "page": 38
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 38
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgf-630-connection-1",
          "modelId": "alageum-tmgf-630",
          "familyId": "tmgf",
          "page": 38,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "8600",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmgf-630-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgf-630",
        "page": 38,
        "sourcePages": [
          38
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 38,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "8600",
            "unit": "Вт",
            "page": 38
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 38
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgf-630-connection-2",
          "modelId": "alageum-tmgf-630",
          "familyId": "tmgf",
          "page": 38,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "8600",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 630,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgf-6-10-kv",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 630,
          "newCatalogValue": "630",
          "newSourcePage": 38,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nД/Ун-11",
          "newSourcePage": 38,
          "comparison": "match",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "5,5",
          "newCatalogValue": "5,5",
          "newSourcePage": 38,
          "comparison": "match",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "1,2",
          "newCatalogValue": "1,0",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1512",
          "newCatalogValue": "1440",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "898",
          "newCatalogValue": "890",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1802",
          "newCatalogValue": "1610",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "505",
          "newCatalogValue": "500",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "1915",
          "newCatalogValue": "1800",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "I0Pct",
          "legacySourceValue": "1,2",
          "newCatalogValue": "1,0",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Ток холостого хода"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1512",
          "newCatalogValue": "1440",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "L"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "898",
          "newCatalogValue": "890",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "B"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1802",
          "newCatalogValue": "1610",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "H"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "505",
          "newCatalogValue": "500",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса масла"
        },
        {
          "field": "massKg",
          "legacySourceValue": "1915",
          "newCatalogValue": "1800",
          "newSourcePage": 38,
          "comparison": "different",
          "label": "Масса"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmgf-6-10-kv",
          "locator": "product technical table, row 630; retrieved web text line 83",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            38,
            39
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-016.json"
        }
      ]
    }
  }
];
export default data;
