// Generated by scripts/complete-catalog-identities.mjs.
const data = [
  {
    "id": "alageum-tmgs-pole-160",
    "canonicalId": "tmgs-160",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГС-160 столбовой",
    "execution": "столбового исполнения",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      34,
      35
    ],
    "sourceRow": {
      "designation": "ТМГС-160 столбовой",
      "electricalTablePage": 34,
      "dimensionsTablePage": 34
    },
    "sourceFamilyId": "tmgs-pole",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "160",
        "unit": "кВА",
        "page": 34
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 34
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nУ/Zн-11\nД/Ун-11",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "450",
        "unit": "Вт",
        "page": 34
      },
      {
        "label": "Рк",
        "value": "2600\n3100\n3100",
        "unit": "Вт",
        "page": 34
      },
      {
        "label": "U к",
        "value": "5,0\n5,5\n5,0",
        "unit": "%",
        "page": 34
      },
      {
        "label": "I о",
        "value": "1,9",
        "unit": "%",
        "page": 34
      },
      {
        "label": "L",
        "value": "1345",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "750",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1080",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "550",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "550",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "90",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "190",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "115",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "120",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "645",
        "unit": "кг",
        "page": 34
      },
      {
        "label": "Масса масла",
        "value": "145",
        "unit": "кг",
        "page": 34
      }
    ],
    "familySpecs": [
      {
        "label": "Крепление",
        "value": "непосредственно на железобетонной опоре",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "С возможностью крепления непосредственно на железобетонной опоре; комплект крепежных элементов и монтажная траверса.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "160",
        "unit": "кВА",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nУ/Zн-11\nД/Ун-11",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "450",
        "unit": "Вт",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "2600\n3100\n3100",
        "unit": "Вт",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "5,0\n5,5\n5,0",
        "unit": "%",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "1,9",
        "unit": "%",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1345",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "750",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1080",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "550",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "550",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "90",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "190",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "115",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "120",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "645",
        "unit": "кг",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "145",
        "unit": "кг",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmgs-pole-160-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgs-pole-160",
        "page": 34,
        "sourcePages": [
          34
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 34,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "2600",
            "unit": "Вт",
            "page": 34
          },
          {
            "label": "U к",
            "value": "5,0",
            "unit": "%",
            "page": 34
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgs-pole-160-connection-1",
          "modelId": "alageum-tmgs-pole-160",
          "familyId": "tmgs-pole",
          "page": 34,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "2600",
          "UkPercentRaw": "5,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmgs-pole-160-connection-2",
        "designation": "У/Zн-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgs-pole-160",
        "page": 34,
        "sourcePages": [
          34
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Zн-11",
            "unit": "",
            "page": 34,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "3100",
            "unit": "Вт",
            "page": 34
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 34
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgs-pole-160-connection-2",
          "modelId": "alageum-tmgs-pole-160",
          "familyId": "tmgs-pole",
          "page": 34,
          "connectionGroupRaw": "У/Zн-11",
          "PkWRaw": "3100",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmgs-pole-160-connection-3",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgs-pole-160",
        "page": 34,
        "sourcePages": [
          34
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 34,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "3100",
            "unit": "Вт",
            "page": 34
          },
          {
            "label": "U к",
            "value": "5,0",
            "unit": "%",
            "page": 34
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgs-pole-160-connection-3",
          "modelId": "alageum-tmgs-pole-160",
          "familyId": "tmgs-pole",
          "page": 34,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "3100",
          "UkPercentRaw": "5,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 160,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgs-6-10-kv-2-2",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 160,
          "newCatalogValue": "160",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;У/Zн-11;Д/Ун-11",
          "newCatalogValue": "У/Ун-0\nУ/Zн-11\nД/Ун-11",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "5,0;5,5;6,0",
          "newCatalogValue": "5,0\n5,5\n5,0",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "1,9",
          "newCatalogValue": "1,9",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "1345",
          "newCatalogValue": "1345",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "750",
          "newCatalogValue": "750",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1085",
          "newCatalogValue": "1080",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "145",
          "newCatalogValue": "145",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "645",
          "newCatalogValue": "645",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "UkPct",
          "legacySourceValue": "5,0;5,5;6,0",
          "newCatalogValue": "5,0\n5,5\n5,0",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "Напряжение короткого замыкания"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "1085",
          "newCatalogValue": "1080",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "H"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmgs-6-10-kv-2-2",
          "locator": "product technical table, row 160; retrieved web text line 87",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            34,
            35
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-015.json"
        }
      ]
    }
  },
  {
    "id": "alageum-tmgs-pole-63",
    "canonicalId": "tmgs-63",
    "relation": "same_designation_lineage_not_equivalent",
    "representation": "source-comparison",
    "designation": "ТМГС-63 столбовой",
    "execution": "столбового исполнения",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourcePages": [
      34,
      35
    ],
    "sourceRow": {
      "designation": "ТМГС-63 столбовой",
      "electricalTablePage": 34,
      "dimensionsTablePage": 34
    },
    "sourceFamilyId": "tmgs-pole",
    "sourceRecordType": "explicit-model-row",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "63",
        "unit": "кВА",
        "page": 34
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 34
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nУ/Zн-11\nД/Ун-11",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "210",
        "unit": "Вт",
        "page": 34
      },
      {
        "label": "Рк",
        "value": "1280\n1470\n1470",
        "unit": "Вт",
        "page": 34
      },
      {
        "label": "U к",
        "value": "4,5\n4,7\n4,7",
        "unit": "%",
        "page": 34
      },
      {
        "label": "I о",
        "value": "2,6",
        "unit": "%",
        "page": 34
      },
      {
        "label": "L",
        "value": "928",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "675",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "935",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "450",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "400",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "90",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "190",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "85",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "110",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "376",
        "unit": "кг",
        "page": 34
      },
      {
        "label": "Масса масла",
        "value": "85",
        "unit": "кг",
        "page": 34
      }
    ],
    "familySpecs": [
      {
        "label": "Крепление",
        "value": "непосредственно на железобетонной опоре",
        "unit": "",
        "page": 34,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "description": "С возможностью крепления непосредственно на железобетонной опоре; комплект крепежных элементов и монтажная траверса.",
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "63",
        "unit": "кВА",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nУ/Zн-11\nД/Ун-11",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "210",
        "unit": "Вт",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "1280\n1470\n1470",
        "unit": "Вт",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "4,5\n4,7\n4,7",
        "unit": "%",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "2,6",
        "unit": "%",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "928",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "675",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "935",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "450",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "400",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "90",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "190",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "85",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "110",
        "unit": null,
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "376",
        "unit": "кг",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "85",
        "unit": "кг",
        "pdfPage": 34,
        "printedPage": "34",
        "table": "dimensions-and-masses"
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmgs-pole-63-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgs-pole-63",
        "page": 34,
        "sourcePages": [
          34
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 34,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "1280",
            "unit": "Вт",
            "page": 34
          },
          {
            "label": "U к",
            "value": "4,5",
            "unit": "%",
            "page": 34
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgs-pole-63-connection-1",
          "modelId": "alageum-tmgs-pole-63",
          "familyId": "tmgs-pole",
          "page": 34,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "1280",
          "UkPercentRaw": "4,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmgs-pole-63-connection-2",
        "designation": "У/Zн-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgs-pole-63",
        "page": 34,
        "sourcePages": [
          34
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Zн-11",
            "unit": "",
            "page": 34,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "1470",
            "unit": "Вт",
            "page": 34
          },
          {
            "label": "U к",
            "value": "4,7",
            "unit": "%",
            "page": 34
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgs-pole-63-connection-2",
          "modelId": "alageum-tmgs-pole-63",
          "familyId": "tmgs-pole",
          "page": 34,
          "connectionGroupRaw": "У/Zн-11",
          "PkWRaw": "1470",
          "UkPercentRaw": "4,7",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmgs-pole-63-connection-3",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmgs-pole-63",
        "page": 34,
        "sourcePages": [
          34
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 34,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "1470",
            "unit": "Вт",
            "page": 34
          },
          {
            "label": "U к",
            "value": "4,7",
            "unit": "%",
            "page": 34
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmgs-pole-63-connection-3",
          "modelId": "alageum-tmgs-pole-63",
          "familyId": "tmgs-pole",
          "page": 34,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "1470",
          "UkPercentRaw": "4,7",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ],
    "power": 63,
    "manufacturer": null,
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed.",
      "Источники относятся к одной серии или обозначению. Совпадение конкретного исполнения не установлено; значения каждого источника показаны отдельно."
    ],
    "comparison": {
      "legacySourceUrl": "https://alageum.com/ru/katalog/transformatory/tmgs-6-10-kv-2-2",
      "legacySourceTitle": "Публичная страница производителя",
      "legacySourcePages": [],
      "comparedSpecs": [
        {
          "field": "powerKva",
          "legacySourceValue": 63,
          "newCatalogValue": "63",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Номинальная мощность",
          "newUnit": "кВА",
          "legacyUnit": "кВА"
        },
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;У/Zн-11",
          "newCatalogValue": "У/Ун-0\nУ/Zн-11\nД/Ун-11",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "Группа соединения обмоток",
          "newUnit": "",
          "legacyUnit": ""
        },
        {
          "field": "UkPct",
          "legacySourceValue": "4,5;4,7",
          "newCatalogValue": "4,5\n4,7\n4,7",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "Напряжение короткого замыкания",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "I0Pct",
          "legacySourceValue": "2,6",
          "newCatalogValue": "2,6",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Ток холостого хода",
          "newUnit": "%",
          "legacyUnit": "%"
        },
        {
          "field": "Lmm",
          "legacySourceValue": "928",
          "newCatalogValue": "928",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "L",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Bmm",
          "legacySourceValue": "675",
          "newCatalogValue": "675",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "B",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "931",
          "newCatalogValue": "935",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "H",
          "newUnit": "",
          "legacyUnit": "мм"
        },
        {
          "field": "oilKg",
          "legacySourceValue": "85",
          "newCatalogValue": "85",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Масса масла",
          "newUnit": "кг",
          "legacyUnit": "кг"
        },
        {
          "field": "massKg",
          "legacySourceValue": "376",
          "newCatalogValue": "376",
          "newSourcePage": 34,
          "comparison": "match",
          "label": "Масса",
          "newUnit": "кг",
          "legacyUnit": "кг"
        }
      ],
      "conflicts": [
        {
          "field": "group",
          "legacySourceValue": "У/Ун-0;У/Zн-11",
          "newCatalogValue": "У/Ун-0\nУ/Zн-11\nД/Ун-11",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "Группа соединения обмоток"
        },
        {
          "field": "UkPct",
          "legacySourceValue": "4,5;4,7",
          "newCatalogValue": "4,5\n4,7\n4,7",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "Напряжение короткого замыкания"
        },
        {
          "field": "Hmm",
          "legacySourceValue": "931",
          "newCatalogValue": "935",
          "newSourcePage": 34,
          "comparison": "different",
          "label": "H"
        }
      ],
      "unresolved": "Manufacturer/source confirmation is required only for a hard alias, replacement of the old source, or asserting that differing dimensions describe the same physical execution.",
      "finding": "same_model_lineage_source_revision_or_execution_unresolved",
      "exactOrderableSkuProven": false,
      "citations": [
        {
          "source": "legacy-primary",
          "url": "https://alageum.com/ru/katalog/transformatory/tmgs-6-10-kv-2-2",
          "locator": "product technical table, row 63; retrieved web text line 85",
          "pages": null
        },
        {
          "source": "new-primary",
          "url": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
          "title": "технический каталог_по страницам_в кривых_18.03.2026-1.pdf",
          "sha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
          "pages": [
            34,
            35
          ],
          "reviewFile": "docs/catalog-transformers-2026/review/section-006-045/models-015.json"
        }
      ]
    }
  }
];
export default data;
