// Generated by scripts/complete-catalog-identities.mjs.
const data = [
  {
    "category": "transformers",
    "productKind": "transformer",
    "sku": null,
    "designation": "ТМГ-1000",
    "execution": "01",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourcePages": [
      8,
      9,
      13
    ],
    "sourceRow": {
      "designation": "ТМГ-1000",
      "electricalTablePage": 8,
      "dimensionsTablePage": 9
    },
    "sourceFamilyId": "tmg-01",
    "sourceRecordType": "explicit-model-row",
    "manufacturer": null,
    "manufacturers": [],
    "manufacturerEvidencePages": [],
    "brand": "Alageum electric",
    "isOrderableSku": false,
    "power": 1000,
    "voltage": "6(10)/0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "наружной или внутренней",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "1000",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1700",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "13000",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "5,0",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "1,04",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "1614",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1084",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1650",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "820",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "820",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "190",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "180",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "2232",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "434",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 8
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed."
    ],
    "image": "/catalog-source/transformers-2026/page-008.webp",
    "imageSourcePage": 8,
    "imageCaption": "Страница 8 исходного каталога; не фотография изделия",
    "documentCount": 1,
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "1000",
        "unit": "кВА",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "1700",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "13000",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "5,0",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "1,04",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1614",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "1084",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1650",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "820",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "820",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "190",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "230",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "180",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "150",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "2232",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "434",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      }
    ],
    "id": "alageum-tmg-01-1000",
    "name": "ТМГ-1000 (01)",
    "recordKind": "variant",
    "recordType": "catalog-model",
    "familyId": "tr2026-family-tmg-01",
    "familyName": "Трансформаторы ТМГ-63-2500 кВА (01)",
    "series": "ТМГ",
    "subtype": "01",
    "description": "ТМГ (01); герметичное исполнение; полностью заполнены трансформаторным маслом.",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "1000",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1700",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "13000",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "5,0",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "1,04",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "1614",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1084",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1650",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "820",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "820",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "190",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "180",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "2232",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "434",
        "unit": "кг",
        "page": 9
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-01-1000-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-1000",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "13000",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "5,0",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-1000-connection-1",
          "modelId": "alageum-tmg-01-1000",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "13000",
          "UkPercentRaw": "5,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-01-1000-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-1000",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "13000",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "5,0",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-1000-connection-2",
          "modelId": "alageum-tmg-01-1000",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "13000",
          "UkPercentRaw": "5,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ]
  },
  {
    "category": "transformers",
    "productKind": "transformer",
    "sku": null,
    "designation": "ТМГ-2500",
    "execution": "01",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourcePages": [
      8,
      9,
      13
    ],
    "sourceRow": {
      "designation": "ТМГ-2500",
      "electricalTablePage": 8,
      "dimensionsTablePage": 9
    },
    "sourceFamilyId": "tmg-01",
    "sourceRecordType": "explicit-model-row",
    "manufacturer": null,
    "manufacturers": [],
    "manufacturerEvidencePages": [],
    "brand": "Alageum electric",
    "isOrderableSku": false,
    "power": 2500,
    "voltage": "6(10)/0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "наружной или внутренней",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "2500",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "2900",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "28500",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "0,5",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "2035",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1348",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "2070",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "1070",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "1070",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "145",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "260",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "220",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "170",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "4895",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "1050",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 8
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed."
    ],
    "image": "/catalog-source/transformers-2026/page-008.webp",
    "imageSourcePage": 8,
    "imageCaption": "Страница 8 исходного каталога; не фотография изделия",
    "documentCount": 1,
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "2500",
        "unit": "кВА",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "2900",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "28500",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "0,5",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "2035",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "1348",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "2070",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "1070",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "1070",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "145",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "260",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "220",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "170",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "4895",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "1050",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      }
    ],
    "id": "alageum-tmg-01-2500",
    "name": "ТМГ-2500 (01)",
    "recordKind": "variant",
    "recordType": "catalog-model",
    "familyId": "tr2026-family-tmg-01",
    "familyName": "Трансформаторы ТМГ-63-2500 кВА (01)",
    "series": "ТМГ",
    "subtype": "01",
    "description": "ТМГ (01); герметичное исполнение; полностью заполнены трансформаторным маслом.",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "2500",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "2900",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "28500",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "5,5",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "0,5",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "2035",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "1348",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "2070",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "1070",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "1070",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "145",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "260",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "220",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "170",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "4895",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "1050",
        "unit": "кг",
        "page": 9
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-01-2500-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-2500",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "28500",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-2500-connection-1",
          "modelId": "alageum-tmg-01-2500",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "28500",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-01-2500-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-2500",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "28500",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "5,5",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-2500-connection-2",
          "modelId": "alageum-tmg-01-2500",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "28500",
          "UkPercentRaw": "5,5",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ]
  },
  {
    "category": "transformers",
    "productKind": "transformer",
    "sku": null,
    "designation": "ТМГ-400",
    "execution": "01",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourcePages": [
      8,
      9,
      12
    ],
    "sourceRow": {
      "designation": "ТМГ-400",
      "electricalTablePage": 8,
      "dimensionsTablePage": 9
    },
    "sourceFamilyId": "tmg-01",
    "sourceRecordType": "explicit-model-row",
    "manufacturer": null,
    "manufacturers": [],
    "manufacturerEvidencePages": [],
    "brand": "Alageum electric",
    "isOrderableSku": false,
    "power": 400,
    "voltage": "6(10)/0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "наружной или внутренней",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "400",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "930",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "6000\n6500",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "4,0",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "1,8",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "1262",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "770",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1275",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "130",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "130",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "1104",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "236",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 8
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed."
    ],
    "image": "/catalog-source/transformers-2026/page-008.webp",
    "imageSourcePage": 8,
    "imageCaption": "Страница 8 исходного каталога; не фотография изделия",
    "documentCount": 1,
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "400",
        "unit": "кВА",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "930",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "6000\n6500",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "4,0",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "1,8",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1262",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "770",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1275",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "660",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "150",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "230",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "130",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "130",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "1104",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "236",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      }
    ],
    "id": "alageum-tmg-01-400",
    "name": "ТМГ-400 (01)",
    "recordKind": "variant",
    "recordType": "catalog-model",
    "familyId": "tr2026-family-tmg-01",
    "familyName": "Трансформаторы ТМГ-63-2500 кВА (01)",
    "series": "ТМГ",
    "subtype": "01",
    "description": "ТМГ (01); герметичное исполнение; полностью заполнены трансформаторным маслом.",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "400",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "930",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "6000\n6500",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "4,0",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "1,8",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "1262",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "770",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1275",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "130",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "130",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "1104",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "236",
        "unit": "кг",
        "page": 9
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-01-400-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-400",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "6000",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "4,0",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-400-connection-1",
          "modelId": "alageum-tmg-01-400",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "6000",
          "UkPercentRaw": "4,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-01-400-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-400",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "6500",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "4,0",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-400-connection-2",
          "modelId": "alageum-tmg-01-400",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "6500",
          "UkPercentRaw": "4,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ]
  },
  {
    "category": "transformers",
    "productKind": "transformer",
    "sku": null,
    "designation": "ТМГ-630",
    "execution": "01",
    "source": "official",
    "sourceKind": "supplied-pdf",
    "sourceId": "transformers-2026",
    "sourceFileId": "113q2las1R18OJ6g6laJ5ZN4PFPsY635f",
    "sourceSha256": "8f27b781f1ff620ce2d67f606d6e115f2d0c35fbd31698f04c392a8ae611c70e",
    "sourceUrl": "https://drive.google.com/file/d/113q2las1R18OJ6g6laJ5ZN4PFPsY635f/view",
    "sourceTitle": "Технический каталог трансформаторов · 18.03.2026",
    "sourcePages": [
      8,
      9,
      12
    ],
    "sourceRow": {
      "designation": "ТМГ-630",
      "electricalTablePage": 8,
      "dimensionsTablePage": 9
    },
    "sourceFamilyId": "tmg-01",
    "sourceRecordType": "explicit-model-row",
    "manufacturer": null,
    "manufacturers": [],
    "manufacturerEvidencePages": [],
    "brand": "Alageum electric",
    "isOrderableSku": false,
    "power": 630,
    "voltage": "6(10)/0,4",
    "voltageUnit": "кВ",
    "cooling": null,
    "installation": "наружной или внутренней",
    "technicalSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "630",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1100",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "8500\n9300",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "5,0",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "1,3",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "1392",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "858",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1515",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "1610",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "366",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Температура умеренного климата",
        "value": "от +40°C до -45°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Температура холодного климата",
        "value": "от +40°C до -60°C",
        "unit": "°C",
        "page": 8
      },
      {
        "label": "Установка",
        "value": "наружной или внутренней",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Высота установки над уровнем моря",
        "value": "не более 1000",
        "unit": "м",
        "page": 8
      },
      {
        "label": "Исполнение",
        "value": "герметичное; внутренний объем не имеет сообщения с окружающей средой",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Заполнение",
        "value": "полностью заполнены трансформаторным маслом",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Подготовка масла",
        "value": "перед заливкой в трансформатор дегазируется",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Исключенные условия работы",
        "value": "тряска, вибрация, удары, химически активная среда",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      }
    ],
    "notes": [
      "L, B, H and other lettered dimensional columns carry no explicit unit in these tables; unit left null rather than assumed."
    ],
    "image": "/catalog-source/transformers-2026/page-008.webp",
    "imageSourcePage": 8,
    "imageCaption": "Страница 8 исходного каталога; не фотография изделия",
    "documentCount": 1,
    "rawSourceSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "630",
        "unit": "кВА",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Р о",
        "value": "1100",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "Рк",
        "value": "8500\n9300",
        "unit": "Вт",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "U к",
        "value": "5,0",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "I о",
        "value": "1,3",
        "unit": "%",
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "L",
        "value": "1392",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "B",
        "value": "858",
        "unit": null,
        "pdfPage": 8,
        "printedPage": "8",
        "table": "electrical"
      },
      {
        "label": "H",
        "value": "1515",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A",
        "value": "660",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "M",
        "value": "150",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "K",
        "value": "230",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h",
        "value": "150",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "h1",
        "value": "150",
        "unit": null,
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Полная масса",
        "value": "1610",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      },
      {
        "label": "Масса масла",
        "value": "366",
        "unit": "кг",
        "pdfPage": 9,
        "printedPage": "9",
        "table": "dimensions-and-masses"
      }
    ],
    "id": "alageum-tmg-01-630",
    "name": "ТМГ-630 (01)",
    "recordKind": "variant",
    "recordType": "catalog-model",
    "familyId": "tr2026-family-tmg-01",
    "familyName": "Трансформаторы ТМГ-63-2500 кВА (01)",
    "series": "ТМГ",
    "subtype": "01",
    "description": "ТМГ (01); герметичное исполнение; полностью заполнены трансформаторным маслом.",
    "variantSpecs": [
      {
        "label": "Номинальная мощность",
        "value": "630",
        "unit": "кВА",
        "page": 8
      },
      {
        "label": "Номинальное напряжение",
        "value": "6(10)/0,4",
        "unit": "кВ",
        "page": 8
      },
      {
        "label": "Группа соединения обмоток",
        "value": "У/Ун-0\nД/Ун-11",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Р о",
        "value": "1100",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "Рк",
        "value": "8500\n9300",
        "unit": "Вт",
        "page": 8
      },
      {
        "label": "U к",
        "value": "5,0",
        "unit": "%",
        "page": 8
      },
      {
        "label": "I о",
        "value": "1,3",
        "unit": "%",
        "page": 8
      },
      {
        "label": "L",
        "value": "1392",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "B",
        "value": "858",
        "unit": "",
        "page": 8,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "H",
        "value": "1515",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "A1",
        "value": "660",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "M",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "K",
        "value": "230",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "h1",
        "value": "150",
        "unit": "",
        "page": 9,
        "sourceUnit": null,
        "unitStatus": "not-stated"
      },
      {
        "label": "Полная масса",
        "value": "1610",
        "unit": "кг",
        "page": 9
      },
      {
        "label": "Масса масла",
        "value": "366",
        "unit": "кг",
        "page": 9
      }
    ],
    "configurations": [
      {
        "id": "alageum-tmg-01-630-connection-1",
        "designation": "У/Ун-0",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-630",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "У/Ун-0",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "8500",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "5,0",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-630-connection-1",
          "modelId": "alageum-tmg-01-630",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "У/Ун-0",
          "PkWRaw": "8500",
          "UkPercentRaw": "5,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      },
      {
        "id": "alageum-tmg-01-630-connection-2",
        "designation": "Д/Ун-11",
        "kind": "configuration",
        "sourceKind": "printed-connection-option",
        "modelId": "alageum-tmg-01-630",
        "page": 8,
        "sourcePages": [
          8
        ],
        "specifications": [
          {
            "label": "Группа соединения обмоток",
            "value": "Д/Ун-11",
            "unit": "",
            "page": 8,
            "sourceUnit": null,
            "unitStatus": "not-stated"
          },
          {
            "label": "Рк",
            "value": "9300",
            "unit": "Вт",
            "page": 8
          },
          {
            "label": "U к",
            "value": "5,0",
            "unit": "%",
            "page": 8
          }
        ],
        "isOrderableSku": false,
        "sourceRow": null,
        "rawSource": {
          "id": "alageum-tmg-01-630-connection-2",
          "modelId": "alageum-tmg-01-630",
          "familyId": "tmg-01",
          "page": 8,
          "connectionGroupRaw": "Д/Ун-11",
          "PkWRaw": "9300",
          "UkPercentRaw": "5,0",
          "scope": "Printed connection option; no synthetic SKU generated"
        },
        "notes": []
      }
    ]
  }
];
export default data;
