'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useSearchParams, useRouter } from 'next/navigation';
import { catalogImport, productById } from '@/lib/catalog/data';

const pageTypes = {cover:'Обложка',blank:'Пустая страница',overview:'Обзор производства',contents:'Содержание',product:'Продукция',continuation:'Характеристики / схемы',certificate:'Исторические сертификаты',notes:'Страница для заметок',contacts:'Контакты'};
export default function CatalogSource() {
 const params=useSearchParams();const router=useRouter();
 const page=Math.max(1,Math.min(catalogImport.pageCount,Number.parseInt(params.get('page') || '1',10)||1));
 const entry=catalogImport.coverage.find(item=>item.page===page);
 const families=(entry?.families || []).map(productById).filter(Boolean);
 function go(value){router.push(`/catalog/source?page=${value}`,{scroll:false});}
 return <div className="catalog-page catalog-source-viewer"><nav className="breadcrumbs" aria-label="Хлебные крошки"><Link href="/catalog">Каталог</Link><span>/</span><span>Исходное издание</span></nav><div className="catalog-heading compact-heading"><div><p className="catalog-kicker">104 СТРАНИЦЫ / ИЗДАНИЕ 02.09.2024</p><h1>Шкафные конструкции</h1></div><p>{catalogImport.familyCount} серий и семейств, {catalogImport.listedModelCount} каталожных обозначений и {catalogImport.configurationCount} табличных вариантов. Все страницы учтены.</p></div><div className="source-viewer-toolbar"><button className="catalog-button" disabled={page===1} onClick={()=>go(page-1)}>← Назад</button><label>Страница<select aria-label="Страница исходного каталога" value={page} onChange={event=>go(event.target.value)}>{catalogImport.coverage.map(item=><option key={item.page} value={item.page}>{item.page} · {pageTypes[item.type] || item.type}</option>)}</select></label><button className="catalog-button" disabled={page===catalogImport.pageCount} onClick={()=>go(page+1)}>Далее →</button><a href={catalogImport.sourceUrl} target="_blank" rel="noopener noreferrer">Исходный PDF ↗</a></div>{catalogImport.unresolvedLabels?.some(item=>item.page===page) && <p className="catalog-data-warning">{catalogImport.unresolvedLabels.filter(item=>item.page===page).map(item=>item.reason).join(' ')}</p>}{families.length>0 && <div className="source-page-products">На этой странице: {families.map(item=><Link href={`/catalog/${item.id}`} key={item.id}>{item.sku} →</Link>)}</div>}{page>=99 && page<=100 && <p className="catalog-data-warning">Исторические репродукции сертификатов из издания 2024 года. Текущая действительность не подтверждена.</p>}<a href={`/catalog-source/page-${String(page).padStart(3,'0')}.webp`} target="_blank" rel="noopener noreferrer" className="source-page-image"><Image key={page} src={`/catalog-source/page-${String(page).padStart(3,'0')}.webp`} width={1406} height={1988} alt={`Исходный каталог «Шкафные конструкции», страница ${page}`} unoptimized priority/><span>Открыть страницу крупнее ↗</span></a><p className="filter-help">Изображения воспроизводят источник. Габариты на схемах, противоречивые значения и обозначения проверяйте по странице и согласовывайте с производителем.</p></div>;
}
