"""add universal constraints and reconciliation

Revision ID: 8f92af1ed797
Revises: 7a30267e01ab
Create Date: 2026-08-27 12:32:10.705293
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8f92af1ed797"
down_revision: str | None = "7a30267e01ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_action_confirmations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=120), nullable=False),
        sa.Column("arguments_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_action_confirmations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_action_confirmations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_action_confirmations")),
    )
    op.create_index(
        op.f("ix_ai_action_confirmations_expires_at"),
        "ai_action_confirmations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_action_confirmations_organization_id"),
        "ai_action_confirmations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_action_confirmations_user_id"),
        "ai_action_confirmations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "external_entity_links",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("internal_id", sa.Uuid(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(length=40), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "sync_status IN ('synced','pending','error','conflict')",
            name=op.f("ck_external_entity_links_valid_sync_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_external_entity_links_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_entity_links")),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "entity_type",
            "external_id",
            name=op.f("uq_external_entity_links_organization_id"),
        ),
    )
    op.create_index(
        "ix_external_entity_links_lookup",
        "external_entity_links",
        ["provider", "entity_type", "external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_entity_links_organization_id"),
        "external_entity_links",
        ["organization_id"],
        unique=False,
    )
    op.create_check_constraint(
        op.f("ck_ai_conversations_b2b_has_principal"),
        "ai_conversations",
        "(scope = 'public') OR (user_id IS NOT NULL AND organization_id IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_ai_conversations_valid_scope"), "ai_conversations", "scope IN ('public','b2b')"
    )
    op.create_check_constraint(
        op.f("ck_document_versions_version_positive"), "document_versions", "version > 0"
    )
    op.create_unique_constraint(
        op.f("uq_documents_organization_id"),
        "documents",
        ["organization_id", "source", "external_id"],
    )
    op.create_unique_constraint(
        op.f("uq_external_status_mappings_provider"),
        "external_status_mappings",
        ["provider", "external_status"],
    )
    op.create_check_constraint(
        op.f("ck_file_objects_size_nonnegative"), "file_objects", "size_bytes >= 0"
    )
    op.create_unique_constraint(
        op.f("uq_integration_events_job_id"),
        "integration_events",
        ["job_id", "event_type", "external_id"],
    )
    op.create_index(
        "ix_integration_jobs_due", "integration_jobs", ["status", "next_attempt_at"], unique=False
    )
    op.create_check_constraint(
        op.f("ck_integration_jobs_attempts_nonnegative"), "integration_jobs", "attempts >= 0"
    )
    op.create_check_constraint(
        op.f("ck_integration_jobs_attempts_within_limit"),
        "integration_jobs",
        "attempts <= max_attempts",
    )
    op.create_check_constraint(
        op.f("ck_integration_jobs_max_attempts_positive"), "integration_jobs", "max_attempts > 0"
    )
    op.execute("UPDATE integration_jobs SET status = 'queued' WHERE status = 'pending'")
    op.create_check_constraint(
        op.f("ck_integration_jobs_valid_status"),
        "integration_jobs",
        "status IN ('queued','running','succeeded','failed','retrying','dead')",
    )
    op.create_index(
        "ix_invoices_organization_created",
        "invoices",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_invoices_organization_id"),
        "invoices",
        ["organization_id", "source", "external_id"],
    )
    op.create_check_constraint(op.f("ck_invoices_amount_nonnegative"), "invoices", "amount >= 0")
    op.create_unique_constraint(
        op.f("uq_knowledge_chunks_document_id"), "knowledge_chunks", ["document_id", "sequence"]
    )
    op.create_check_constraint(
        op.f("ck_knowledge_chunks_sequence_nonnegative"), "knowledge_chunks", "sequence >= 0"
    )
    op.create_unique_constraint(
        op.f("uq_knowledge_documents_source_id"),
        "knowledge_documents",
        ["source_id", "external_id"],
    )
    op.create_unique_constraint(
        op.f("uq_notification_preferences_membership_id"),
        "notification_preferences",
        ["membership_id", "event_code", "channel"],
    )
    op.create_check_constraint(
        op.f("ck_order_items_quantity_positive"), "order_items", "quantity > 0"
    )
    op.create_check_constraint(
        op.f("ck_order_items_unit_price_nonnegative"),
        "order_items",
        "unit_price IS NULL OR unit_price >= 0",
    )
    op.create_index(
        "ix_orders_organization_created", "orders", ["organization_id", "created_at"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_orders_organization_id"), "orders", ["organization_id", "external_id"]
    )
    op.create_check_constraint(op.f("ck_orders_amount_nonnegative"), "orders", "amount >= 0")
    op.create_check_constraint(
        op.f("ck_payment_schedule_items_amount_nonnegative"),
        "payment_schedule_items",
        "amount >= 0",
    )
    op.create_index(
        "ix_payments_organization_created",
        "payments",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_payments_organization_id"),
        "payments",
        ["organization_id", "source", "external_id"],
    )
    op.create_check_constraint(op.f("ck_payments_amount_nonnegative"), "payments", "amount >= 0")
    op.create_check_constraint(
        op.f("ck_quote_request_items_quantity_positive"), "quote_request_items", "quantity > 0"
    )
    op.create_index(
        "ix_quote_requests_organization_created",
        "quote_requests",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_sync_cursors_organization_id"),
        "sync_cursors",
        ["organization_id", "provider", "resource"],
    )
    op.create_index(
        "ix_tickets_organization_created",
        "tickets",
        ["organization_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tickets_organization_created", table_name="tickets")
    op.drop_constraint(op.f("uq_sync_cursors_organization_id"), "sync_cursors", type_="unique")
    op.drop_index("ix_quote_requests_organization_created", table_name="quote_requests")
    op.drop_constraint(
        op.f("ck_quote_request_items_quantity_positive"), "quote_request_items", type_="check"
    )
    op.drop_constraint(op.f("ck_payments_amount_nonnegative"), "payments", type_="check")
    op.drop_constraint(op.f("uq_payments_organization_id"), "payments", type_="unique")
    op.drop_index("ix_payments_organization_created", table_name="payments")
    op.drop_constraint(
        op.f("ck_payment_schedule_items_amount_nonnegative"),
        "payment_schedule_items",
        type_="check",
    )
    op.drop_constraint(op.f("ck_orders_amount_nonnegative"), "orders", type_="check")
    op.drop_constraint(op.f("uq_orders_organization_id"), "orders", type_="unique")
    op.drop_index("ix_orders_organization_created", table_name="orders")
    op.drop_constraint(op.f("ck_order_items_unit_price_nonnegative"), "order_items", type_="check")
    op.drop_constraint(op.f("ck_order_items_quantity_positive"), "order_items", type_="check")
    op.drop_constraint(
        op.f("uq_notification_preferences_membership_id"),
        "notification_preferences",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_knowledge_documents_source_id"), "knowledge_documents", type_="unique"
    )
    op.drop_constraint(
        op.f("ck_knowledge_chunks_sequence_nonnegative"), "knowledge_chunks", type_="check"
    )
    op.drop_constraint(op.f("uq_knowledge_chunks_document_id"), "knowledge_chunks", type_="unique")
    op.drop_constraint(op.f("ck_invoices_amount_nonnegative"), "invoices", type_="check")
    op.drop_constraint(op.f("uq_invoices_organization_id"), "invoices", type_="unique")
    op.drop_index("ix_invoices_organization_created", table_name="invoices")
    op.drop_constraint(op.f("ck_integration_jobs_valid_status"), "integration_jobs", type_="check")
    op.drop_constraint(
        op.f("ck_integration_jobs_max_attempts_positive"), "integration_jobs", type_="check"
    )
    op.drop_constraint(
        op.f("ck_integration_jobs_attempts_within_limit"), "integration_jobs", type_="check"
    )
    op.drop_constraint(
        op.f("ck_integration_jobs_attempts_nonnegative"), "integration_jobs", type_="check"
    )
    op.drop_index("ix_integration_jobs_due", table_name="integration_jobs")
    op.drop_constraint(op.f("uq_integration_events_job_id"), "integration_events", type_="unique")
    op.drop_constraint(op.f("ck_file_objects_size_nonnegative"), "file_objects", type_="check")
    op.drop_constraint(
        op.f("uq_external_status_mappings_provider"), "external_status_mappings", type_="unique"
    )
    op.drop_constraint(op.f("uq_documents_organization_id"), "documents", type_="unique")
    op.drop_constraint(
        op.f("ck_document_versions_version_positive"), "document_versions", type_="check"
    )
    op.drop_constraint(op.f("ck_ai_conversations_valid_scope"), "ai_conversations", type_="check")
    op.drop_constraint(
        op.f("ck_ai_conversations_b2b_has_principal"), "ai_conversations", type_="check"
    )
    op.drop_index(
        op.f("ix_external_entity_links_organization_id"), table_name="external_entity_links"
    )
    op.drop_index("ix_external_entity_links_lookup", table_name="external_entity_links")
    op.drop_table("external_entity_links")
    op.drop_index(op.f("ix_ai_action_confirmations_user_id"), table_name="ai_action_confirmations")
    op.drop_index(
        op.f("ix_ai_action_confirmations_organization_id"), table_name="ai_action_confirmations"
    )
    op.drop_index(
        op.f("ix_ai_action_confirmations_expires_at"), table_name="ai_action_confirmations"
    )
    op.drop_table("ai_action_confirmations")
    # ### end Alembic commands ###
