"""Write the reviewed catalog as ordered, bounded JSON and JavaScript chunks.

This module only changes the data representation. It never sorts records or keys,
normalizes values, downloads sources, or regenerates product/source images.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re


FORMAT = "alageum-catalog-chunks-v1"
MAX_CHUNK_BYTES = 75_000
GENERATED = "// Generated by scripts/catalog_data.py; preserve source order and values.\n"


def json_text(value):
    return json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + "\n"


def module_text(value):
    return GENERATED + "const data = " + json_text(value).rstrip("\n") + ";\nexport default data;\n"


def split_records(records):
    """Greedily partition consecutive whole records, including module overhead."""
    chunks = []
    current = []
    for record in records:
        candidate = current + [record]
        if len(module_text(candidate).encode("utf-8")) > MAX_CHUNK_BYTES:
            if not current:
                raise ValueError(f"Record {record.get('id')!r} exceeds chunk limit")
            chunks.append(current)
            current = [record]
            if len(module_text(current).encode("utf-8")) > MAX_CHUNK_BYTES:
                raise ValueError(f"Record {record.get('id')!r} exceeds chunk limit")
        else:
            current = candidate
    if current:
        chunks.append(current)
    return chunks


def read_products(path):
    """Read either a legacy array or the versioned index, in its stated order."""
    value = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(value, list):
        return value
    if value.get("format") != FORMAT:
        raise ValueError("Unknown catalog product representation")
    records = []
    for chunk in value["chunks"]:
        relative = Path(chunk["path"])
        if relative.is_absolute() or ".." in relative.parts:
            raise ValueError("Chunk paths must remain inside the index directory")
        content = (path.parent / relative).read_bytes()
        if hashlib.sha256(content).hexdigest() != chunk["sha256"]:
            raise ValueError(f"Chunk checksum mismatch: {relative}")
        items = json.loads(content)
        if not isinstance(items, list) or len(items) != chunk["recordCount"]:
            raise ValueError(f"Chunk record count mismatch: {relative}")
        records.extend(items)
    if len(records) != value["recordCount"]:
        raise ValueError("Catalog record count mismatch")
    return records


def write_catalog_data(records, metadata, root):
    """Generate both representations deterministically with unchanged exports."""
    if not isinstance(records, list) or len(records) != metadata["recordCount"]:
        raise ValueError("Products and metadata record counts disagree")
    chunks = split_records(records)
    output = {}
    descriptors = []
    imports = []
    names = []
    for number, chunk in enumerate(chunks, 1):
        stem = f"part-{number:03d}"
        relative = f"products/{stem}.json"
        content = json_text(chunk)
        output[f"docs/catalog-import/{relative}"] = content
        output[f"frontend/lib/catalog/imported-data/{stem}.js"] = module_text(chunk)
        descriptors.append({
            "path": relative,
            "recordCount": len(chunk),
            "firstId": chunk[0]["id"],
            "lastId": chunk[-1]["id"],
            "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
        })
        name = f"part{number:03d}"
        names.append(name)
        imports.append(f"import {name} from './imported-data/{stem}.js';")
    index = {
        "format": FORMAT,
        "recordCount": len(records),
        "metadata": "manifest.json",
        "maxChunkBytes": MAX_CHUNK_BYTES,
        "chunks": descriptors,
    }
    output["docs/catalog-import/products.json"] = json_text(index)
    output["docs/catalog-import/manifest.json"] = json_text(metadata)
    output["frontend/lib/catalog/imported-data/metadata.js"] = module_text(metadata)
    output["frontend/lib/catalog/imported.js"] = (
        "// Transcribed from the user-supplied 2024 PDF. See docs/catalog-import for page coverage.\n"
        + GENERATED
        + "\n".join(imports)
        + "\n\nexport const importedProducts = [\n"
        + "".join(f"  ...{name},\n" for name in names)
        + "];\nexport { default as catalogImport } from './imported-data/metadata.js';\n"
    )
    # Check every generated file before writing anything, not just product arrays.
    for relative, content in output.items():
        if len(content.encode("utf-8")) > MAX_CHUNK_BYTES:
            raise ValueError(f"Generated file exceeds chunk limit: {relative}")
    for relative, content in output.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    # Remove only obsolete generated parts when a later reviewed import shrinks.
    for directory, suffix in [
        ("docs/catalog-import/products", "json"),
        ("frontend/lib/catalog/imported-data", "js"),
    ]:
        for path in (root / directory).glob(f"part-*.{suffix}"):
            if re.fullmatch(rf"part-\d+\.{suffix}", path.name) and path.relative_to(root).as_posix() not in output:
                path.unlink()
    return index


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--products", required=True, type=Path, help="Legacy array or generated products.json index")
    parser.add_argument("--metadata", required=True, type=Path, help="Catalog manifest.json")
    parser.add_argument("--output-root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    records = read_products(args.products)
    metadata = json.loads(args.metadata.read_text(encoding="utf-8"))
    index = write_catalog_data(records, metadata, args.output_root)
    print(f"Wrote {index['recordCount']} records in {len(index['chunks'])} ordered chunks")


if __name__ == "__main__":
    main()
