/** Closed evidence-group allowlist. No substring, family-name, rating or category fallback. */
export const transformer2026GroupTypes = Object.freeze({
  'sealed-corrugated-small': 'tr26-corrugated-small',
  'sealed-corrugated-large': 'tr26-corrugated-large',
  'tm-conservator-small': 'tr26-conservator-small',
  'tm-conservator-large': 'tr26-conservator-large',
  'tmgin-rpn-630': 'tr26-rpn-corrugated',
  'tmgs-pole-mount': 'tr26-pole-bracket',
  'tmz-panel-radiator': 'tr26-panel-side-terminals',
  'tmgf-separated-bushings': 'tr26-flanged-ends',
  'tmg-switch-small': 'tr26-corrugated-small',
  'tmg-switch-large': 'tr26-corrugated-large',
  'oil-tmg-twostage-small': 'tr26-corrugated-small',
  'oil-tmg-twostage-large': 'tr26-corrugated-large',
  'oil-isolating-tmg': 'tr26-isolating',
  'oil-tm-20kv-small': 'tr26-conservator-small',
  'oil-tm-20kv-large': 'tr26-conservator-large',
  'oil-tmg-20kv-small': 'tr26-corrugated-small',
  'oil-tmg-20kv-large': 'tr26-corrugated-large',
  'oil-tmgsu': 'tr26-corrugated-small',
  'oil-tmeg': 'tr26-hood-small',
  'oil-tmpn-top': 'tr26-hood-tall',
  'oil-tmpng-side': 'tr26-side-terminal-box',
  'oil-tmto-three-winding': 'tr26-heating-three-row',
  'oil-tmto-modern': 'tr26-heating-single-row',
  'oil-omp': 'tr26-single-side-bushings',
  'oil-om': 'tr26-pole-cylinder',
  'dry-tsl-open-6-10': 'tr26-dry-cast-open',
  'dry-tslz-enclosed-6-10': 'tr26-dry-mesh-cutaway',
  'dry-tsl-open-20': 'tr26-dry-cast-open',
  'accessory-relay-tr100': 'tr26-icon-temperature-relay',
  'accessory-sensor-pt100': 'tr26-icon-temperature-probe',
  'accessory-damper-ek290': 'tr26-icon-vibration-damper',
  'accessory-thermal-cabinet': 'tr26-icon-thermal-cabinet',
  'accessory-cooling-fans': 'tr26-icon-cooling-fan',
  'dry-ts-open': 'tr26-dry-foil-open',
  'dry-tsz-enclosed': 'tr26-dry-compact-louver',
  'dry-tsi-unproven': null,
  'dry-tszi-top-bushing': 'tr26-dry-top-bushings',
  'dry-tsn-open': 'tr26-dry-nomex-open',
  'dry-tsnz-mesh': 'tr26-dry-mesh-closed',
  'dry-tsnz-top-bushing': 'tr26-dry-top-bushings',
  'measurement-ntmi': 'tr26-instrument-three-triangle',
  'measurement-nom': 'tr26-instrument-two-round',
  'measurement-nami': 'tr26-instrument-three-rect',
  'measurement-zom-znom': 'tr26-instrument-column',
  'drawing-omzh-102': 'tr26-rail-single-conservator',
  'drawing-tmzh-104': 'tr26-tilted-conservator',
  'drawing-tmg-35-small-107': 'tr26-tilted-sealed',
  'drawing-tmg-35-large-108': 'tr26-upright-sealed-35',
  'drawing-aomzh-110': 'tr26-rail-power-three',
  'drawing-tdtnsh-112': 'tr26-power-three-winding-35',
  'drawing-trdns-16000-114': 'tr26-power-split-16',
  'drawing-trdns-25000-115': 'tr26-power-split-25',
  'drawing-trdns-40000-116': 'tr26-power-split-40',
  'drawing-td-35-118': 'tr26-power-td-35',
  'drawing-tdns-10000-al-al': 'tr26-power-tdns-10',
  'drawing-tdns-10000-cu-cu': 'tr26-power-tdns-10',
  'drawing-tdns-16000-al-al': 'tr26-power-tdns-16',
  'drawing-tdns-16000-cu-cu': 'tr26-power-tdns-16',
  'drawing-tdns-25000-unspecified': 'tr26-power-tdns-25',
  'drawing-tdns-40000-cu-cu': 'tr26-power-tdns-40',
  'drawing-tm-lv04-125': 'tr26-panel-lv-four',
  'drawing-tm-lv04-126': 'tr26-panel-lv-seven',
  'drawing-tm-lv04-127': 'tr26-panel-lv-four-large',
  'drawing-tm-130': 'tr26-panel-conservator',
  'drawing-tm-131': 'tr26-panel-conservator-offset',
  'drawing-tm-132': 'tr26-panel-conservator-large',
  'drawing-tm-133': 'tr26-panel-conservator-balanced',
  'drawing-tm-136': 'tr26-panel-conservator',
  'drawing-tm-137': 'tr26-panel-conservator-offset',
  'drawing-tm-138': 'tr26-panel-conservator-large',
  'drawing-tm-139': 'tr26-panel-conservator-balanced',
  'drawing-tmn-141': 'tr26-panel-rpn-small',
  'drawing-tmn-panel-143': 'tr26-panel-rpn-large',
  'drawing-tmn110-146': 'tr26-hv-offset-conservator',
  'drawing-tmn110-147': 'tr26-hv-three',
  'drawing-tmn110-148': 'tr26-hv-three-wide',
  'drawing-tmtn150': 'tr26-hv-three-winding',
  'drawing-tdn-152': 'tr26-hv-tdn-10',
  'drawing-tdn-153': 'tr26-hv-tdn-16',
  'drawing-tdtn-155': 'tr26-hv-tdtn-10',
  'drawing-tdtn-156': 'tr26-hv-tdtn-16',
  'drawing-tdn158': 'tr26-power-low-profile',
  'drawing-tds160': 'tr26-power-tds',
  'drawing-tm-163': 'tr26-panel-low-voltage',
  'drawing-tm-164': 'tr26-panel-low-voltage-balanced',
  'photo-section-165': null,
  'photo-factory-166': null,
});
export const transformer2026GroupHolds = Object.freeze({
  'dry-tsi-unproven': 'Нужен подписанный чертеж открытого ТСИ 1,6/2,5/4,0. Рядом со строками показан кожух с подписями ТСНЗ-400/630; он не доказывает исполнение ТСИ.',
  'photo-section-165': 'Редакционное фото без однозначного обозначения и исполнения. Нужен чертеж или фото с подтвержденным соответствием каждой записи Asia Trafo.',
  'photo-factory-166': 'Фото здания завода не является доказательством конструкции трансформатора, автотрансформатора или реактора.',
});

export const transformer2026GeometryHolds = Object.freeze({
  'measurement-zom-znom': 'По страницам 99/100 нельзя однозначно классифицировать малые символы как выводы НН или пробки. Нужна подписанная схема внешних выводов. До подтверждения доступен только условный значок основного столба; 3D привязка удержана.',
});
