import { transformer2026PowerLayouts } from './transformer2026PowerLayouts.js';
/**
 * Reviewed visible construction vocabulary for the supplied transformer catalogue.
 * These definitions do NOT activate product records or assert SKU-specific geometry.
 * All dimensions below are ARBITRARY SCENE UNITS. Table dimensions are never used.
 * An external outline and visible fittings are interpreted, never hidden apparatus.
 */
export const TRANSFORMER_2026_DISCLOSURE = 'Иллюстративная компоновка по источнику; не CAD, не размеры и не точная модель исполнения';
const make = (name, pages, build, layout, observations) => Object.freeze({ name, pages: Object.freeze(pages), build, layout: Object.freeze(Object.fromEntries(Object.entries(layout).map(([key, value]) => [key, Array.isArray(value) ? Object.freeze(value) : value]))), observations, units: 'arbitrary-scene-units', exactMeshReuseAllowed: false, dimensionAccurate: false, reviewStatus: 'topology-proposal', reference: `/catalog-source/transformers-2026/page-${String(pages[0]).padStart(3, '0')}.webp` });
const oil = (name, pages, layout, observations) => make(name, pages, 'oil', layout, observations);
const hv = (name, pages, layout, observations) => make(name, pages, 'power-assembly', { ...layout, ...transformer2026PowerLayouts[pages[0]] }, observations);
export const transformer2026Types = Object.freeze({
  'tr26-corrugated-small': oil('Малый герметичный гофрированный бак', [12, 22, 30, 42, 46, 56, 59], { cooling: 'corrugated', size: 'small', hv: 3, lv: 4, fillTube: true }, 'Видны гофрированный бак, два ряда верхних вводов, высокий маслозаливной патрубок и швеллерное основание. Катки являются опцией, в модели не добавлены.'),
  'tr26-corrugated-large': oil('Большой герметичный гофрированный бак', [13, 23, 31, 43, 47, 57], { cooling: 'corrugated', size: 'large', hv: 3, lv: 4, largeLvPlates: true }, 'Высокий бак с гофрами на длинных и торцевых стенках, три более низких ввода ВН и четыре более высоких ввода НН с плоскими контактными пластинами по фронтальной и торцевой проекциям. Расширителя нет.'),
  'tr26-isolating': oil('Разделительный трансформатор с двумя рядами вводов', [49], { cooling: 'corrugated', size: 'large', hv: 3, lv: 3, equalRows: true }, 'На плане показаны два ряда по три ввода; не используется четырехвыводный ряд обычного ТМГ.'),
  'tr26-conservator-small': oil('Малый гофрированный бак с расширителем', [16, 52], { cooling: 'corrugated', size: 'small', hv: 3, lv: 4, conservator: true }, 'Расширитель над одним торцом бака, его цилиндрическая форма видна в двух проекциях; три высоких и четыре малых верхних ввода.'),
  'tr26-conservator-large': oil('Большой гофрированный бак с расширителем', [17, 53], { cooling: 'corrugated', size: 'large', hv: 3, lv: 4, conservator: true, largeLvPlates: true }, 'Высокий гофрированный бак и расширитель на торцевой опоре; три более низких ввода ВН и четыре более высоких ввода НН с плоскими контактными пластинами. Высоты условные, иерархия сохранена по источнику.'),
  'tr26-rpn-corrugated': oil('Гофрированный бак с наружным приводом РПН', [33], { cooling: 'corrugated', size: 'large', hv: 3, lv: 4, drive: true, fillTube: true, fillTubeSide: -1, lvPlates: true, lvPlateHeight: .43 }, 'Дополнительный наружный короб и вал привода отличают чертеж ТМГиН от стандартного ТМГ; внутренний переключатель не изображен.'),
  'tr26-pole-bracket': oil('Гофрированный бак с мачтовым кронштейном', [35], { cooling: 'corrugated', size: 'small', hv: 3, lv: 4, poleBracket: true, fillTube: true }, 'Две вертикальные полосы и поперечина кронштейна на стенке видны в фасаде. Опорный столб в источнике отсутствует и не добавлен.'),
  'tr26-panel-side-terminals': oil('Бак с панельными радиаторами и боковыми вводами', [37], { cooling: 'panels', size: 'large', sideTerminals: true, hv: 3, lv: 2 }, 'Четыре раздельных радиаторных блока и вводы на противоположных торцах по плану; верхние открытые вводы и расширитель отсутствуют.'),
  'tr26-flanged-ends': oil('Гофрированный бак с разнесенными фланцами вводов', [39], { cooling: 'corrugated', size: 'large', flanged: true, hv: 3, lv: 4 }, 'ВН и НН размещены на отдельных фланцах противоположных концов крышки, а не в двух продольных рядах.'),
  'tr26-hood-small': oil('Малый бак с защитным колпаком вводов', [61], { cooling: 'corrugated', size: 'small', hv: 3, lv: 4, hood: true, fillTube: true }, 'Над вводами виден защитный трапециевидный колпак; внутренние соединения колпака не реконструируются.'),
  'tr26-hood-tall': oil('Высокий бак с верхним защитным колпаком', [66], { cooling: 'corrugated', size: 'tall', hv: 3, lv: 3, hood: true }, 'Высокая узкая компоновка ТМПН с колпаком над верхними выводами и швеллерами; не боковая коробка.'),
  'tr26-side-terminal-box': oil('Гофрированный бак с боковой коробкой выводов', [67], { cooling: 'corrugated', size: 'tall', hv: 0, lv: 0, sideBox: true }, 'Выступающая закрытая коробка на боковой стенке заменяет верхний колпак; невидимые клеммы остаются скрытыми.'),
  'tr26-heating-three-row': oil('ТМТО с тремя рядами верхних вводов', [69], { cooling: 'thin-ribs', size: 'flat', hv: 3, lv: 3, thirdRow: true }, 'План показывает три ряда вводов вокруг переключателя. Условный разрыв стенки на чертеже не превращен в прозрачный бак.'),
  'tr26-heating-single-row': oil('ТМТО модернизированный с одним рядом вводов', [71], { cooling: 'thin-ribs', size: 'flat', hv: 3, lv: 3, singleRow: true }, 'План показывает шесть вводов в одном ряду. Конструкция не объединена с трехрядным ТМТО страницы 69.'),
  'tr26-single-side-bushings': oil('Однофазный прямоугольный бак с боковыми вводами', [74], { cooling: 'flat', size: 'compact', hv: 2, lv: 2, sideOnly: true }, 'Два горизонтальных ввода на торце прямоугольного бака; малые выводы на крышке. Конфликт размеров таблицы не разрешается геометрией.'),
  'tr26-pole-cylinder': make('Цилиндрический однофазный бак с кронштейном', [75], 'measurement', { tank: 'cylinder', hv: 2, lv: 4, bracket: true, poleCylinder: true }, 'Цилиндрический бак, два высоких ввода и четыре малых верхних вывода по плану и боковой монтажный кронштейн.'),
  'tr26-dry-cast-open': make('Открытый сухой трансформатор с тремя литыми катушками', [80, 84], 'dry-open', { coil: 'cast', wheels: true, links: true }, 'Три катушки, верхняя и нижняя стяжные балки, видимые диагональные связи и катки; корпус отсутствует.'),
  'tr26-dry-mesh-cutaway': make('Кожух ТСЛЗ с показанным нижним разрезом', [81], 'enclosure', { mesh: true, cutaway: true, wheels: true, sideTerminal: true, sideVents: 'lower' }, 'Сохранен характер источника: верхняя сетка, средняя панель и раскрытый нижний фрагмент с видимыми катушками. Это иллюстративный разрез, не утверждение о постоянно открытом фасаде.'),
  'tr26-dry-foil-open': make('Открытая трехкатушечная конструкция ТС', [88], 'dry-open', { coil: 'foil', wheels: false, busbarFront: 9, busbarRear: 6 }, 'Три прямоугольных блока обмоток между открытыми балками и верхними клеммами, основание без кожуха.'),
  'tr26-dry-compact-louver': make('Компактный кожух ТСЗ с жалюзи', [87], 'enclosure', { compact: true, sideVents: 'both' }, 'Компактный закрытый кожух с двумя зонами жалюзи, верхней клеммной областью и проушинами.'),
  'tr26-dry-top-bushings': make('Жалюзийный кожух с вводами на крыше', [90, 94], 'enclosure', { topBushings: true, sideVents: 'both' }, 'Закрытый кожух с двумя рядами жалюзи, тремя высокими и малыми верхними вводами; не сетчатый ТСНЗ страницы 93.'),
  'tr26-dry-nomex-open': make('Открытая конструкция ТСН с клеммными пластинами', [92], 'dry-open', { coil: 'foil', wheels: true, terminalPlates: true, busbarFront: 3, busbarRear: 4 }, 'Три блока обмоток, открытые балки, крупные передние клеммные пластины и колесная база; материал Номекс не моделируется геометрически.'),
  'tr26-dry-mesh-closed': make('Закрытый сетчатый кожух ТСНЗ', [93], 'enclosure', { mesh: true, wheels: true, sideTerminal: true, sideVents: 'lower' }, 'Замкнутый фасад с верхней и нижней сетками и средней панелью. Кожух не заменяется открытыми катушками.'),
  'tr26-instrument-three-triangle': make('Круглый измерительный бак с вводами треугольником', [96], 'measurement', { tank: 'cylinder', triangular: true, secondaryArc: true, hv: 3, lv: 6 }, 'Круглая крышка и треугольное размещение трех вводов по плану; шестигранная схема крепления основания не подменяет форму бака. Шесть малых выводов расположены двумя группами.'),
  'tr26-instrument-two-round': make('Измерительный круглый бак с двумя вводами', [97], 'measurement', { tank: 'cylinder', hv: 2, lv: 2 }, 'Круглый бак на основании и два высоких ввода; трехвводная геометрия НТМИ исключена.'),
  'tr26-instrument-three-rect': make('Измерительный прямоугольный бак с тремя вводами', [98], 'measurement', { tank: 'box', triangular: true, hv: 3, lv: 7 }, 'Прямоугольный бак, три ввода ВН треугольником и семь малых выводов в одном ряду по трем проекциям НАМИ.'),
  'tr26-instrument-column': make('Один фарфоровый столб на прямоугольном баке', [99, 100], 'measurement', { tank: 'box', column: true }, 'Прямоугольный нижний бак, один высокий ребристый столб и цилиндрическая верхняя камера по одинаковой наружной схеме ЗОМ/ЗНОМ.'),
  'tr26-rail-single-conservator': oil('Однофазный гофрированный бак с расширителем', [102], { cooling: 'corrugated', size: 'compact', hv: 1, lv: 3, conservator: true, tallBushings: true }, 'Один высокий верхний ввод и боковой цилиндрический расширитель над небольшим гофрированным баком.'),
  'tr26-tilted-conservator': oil('Гофрированный бак с наклонными вводами и расширителем', [104], { cooling: 'corrugated', size: 'small', hv: 3, lv: 4, tilted: true, conservator: true, conservatorAxis: 'long-front', tallBushings: true }, 'Три крупных наклонных ввода, ряд малых выводов и отдельный расширитель; компоновка прочитана по плану и двум видам.'),
  'tr26-tilted-sealed': oil('Герметичный бак с наклонными вводами', [107], { cooling: 'corrugated', size: 'small', hv: 3, lv: 4, tilted: true, tallBushings: true, fillTube: true }, 'Три наклонных крупных ввода на крышке гофрированного бака; расширитель отсутствует.'),
  'tr26-upright-sealed-35': oil('Большой герметичный бак с высокими вертикальными вводами', [108], { cooling: 'corrugated', size: 'large', hv: 3, lv: 7, tallBushings: true, lvPlates: true }, 'В крупном исполнении чертеж показывает вертикальные, а не наклонные высокие вводы.'),
  'tr26-rail-power-three': hv('Железнодорожная сборка с тремя видимыми вводами', [110], { terminals: 'three-only', radiatorBanks: 3, ladder: false }, 'На фасаде показаны три высоких ввода, торцевой расширитель и боковые радиаторные панели; однофазное назначение не означает два видимых ввода.'),
  'tr26-power-three-winding-35': hv('Трехобмоточная сборка 35 кВ с РПН', [112], { terminals: 'three-row', radiatorBanks: 2, ladder: true, drive: true }, 'Несколько рядов верхних вводов, расширитель, лестница, наружный привод и боковые радиаторы по странице 112.'),
  'tr26-power-split-16': hv('Сборка ТРДНС с расщепленными выводами', [114], { terminals: 'split', radiatorBanks: 2, fans: 1, ladder: true }, 'На плане две группы выводов, широкие боковые радиаторные блоки, видимые вентиляторы, расширитель и лестница.'),
  'tr26-power-split-25': hv('Сборка ТРДНС с двухъярусными вентиляторами', [115], { terminals: 'split', radiatorBanks: 2, fans: 2, fanSides: [0, 2], ladder: true, wide: true }, 'Сохранены два видимых уровня вентиляторов с одной стороны и разнесенные выводы; размеры не переносятся из таблицы.'),
  'tr26-power-split-40': hv('Сборка ТРДНС с широкими радиаторами', [116], { terminals: 'split', radiatorBanks: 3, fans: 2, ladder: true, wide: true }, 'Широкие боковые группы охлаждения, два уровня вентиляторов и разнесенные выводы по трем проекциям.'),
  'tr26-power-td-35': hv('Сборка ТД с боковыми радиаторными панелями', [118], { terminals: 'six', radiatorBanks: 2, ladder: true, wide: true }, 'Удлиненный бак, расширитель на торце, лестница и радиаторные панели по фасаду и плану; невидимые вентиляторы не добавлены.'),
  'tr26-power-tdns-10': hv('Сборка ТДНС с разнесенными радиаторами', [120], { terminals: 'six', radiatorBanks: 2, ladder: true }, 'Два ряда вводов, разнесенные боковые радиаторы, торцевой расширитель и лестница. Материал обмоток снаружи не подтверждается.'),
  'tr26-power-tdns-16': hv('Сборка ТДНС с одноярусными вентиляторами', [121], { terminals: 'six', radiatorBanks: 2, fans: 1, ladder: true }, 'В торцевой проекции видны вентиляторы по обеим сторонам; видимая наружная схема для заголовка 16000, не точный Al/Cu меш.'),
  'tr26-power-tdns-25': hv('Сборка ТДНС с расширенными блоками охлаждения', [122], { terminals: 'six', radiatorBanks: 3, fans: 2, ladder: true }, 'Верхние вводы, расширитель и широкие боковые группы с двумя уровнями вентиляторов.'),
  'tr26-power-tdns-40': hv('Высокая сборка ТДНС с боковым охлаждением', [123], { terminals: 'six', radiatorBanks: 3, fans: 2, ladder: true, tall: true }, 'Более высокая наружная компоновка и крупные боковые радиаторы по чертежу; обмотки не показываются.'),
  'tr26-panel-lv-four': hv('Панельный ТМ с четырьмя выводами НН', [125], { terminals: 'three-four', radiatorBanks: 2, ladder: false }, 'План показывает четыре малых вывода НН, три ВН и торцевой расширитель; панельное охлаждение на двух сторонах.'),
  'tr26-panel-lv-four-large': hv('Крупный панельный ТМ с четырьмя выводами НН', [127], { terminals: 'three-four', radiatorBanks: 3, ladder: false }, 'Более широкие боковые радиаторные блоки и четыре вывода НН по странице 127.'),
  'tr26-panel-conservator': hv('Панельный ТМ с двумя рядами вводов', [130, 136], { terminals: 'six', radiatorBanks: 2, ladder: false }, 'Два ряда по три ввода, цилиндрический торцевой расширитель, две боковые группы панелей. Рейтинги и назначение сохраняются в отдельных записях.'),
  'tr26-panel-conservator-large': hv('Панельный ТМ с широким охлаждением', [132, 138], { terminals: 'six', radiatorBanks: 3, ladder: false }, 'Три силовых ввода и малый ряд, расширитель и широкие боковые панели; семейный контур без размерной эквивалентности.'),
  'tr26-panel-rpn-small': hv('Панельный ТМН с выступающим наружным приводом', [141], { terminals: 'six', radiatorBanks: 2, ladder: false, drive: true }, 'Отдельный наружный узел РПН на правом торце, радиаторы и расширитель; внутренний переключатель не моделируется.'),
  'tr26-panel-rpn-large': hv('Панельный ТМН с крупными радиаторами и РПН', [143], { terminals: 'six', radiatorBanks: 3, ladder: false, drive: true }, 'Выступающий торцевой привод и широкие группы панельных радиаторов по трем видам.'),
  'tr26-hv-offset-conservator': hv('ТМН 110 кВ со смещенным расширителем', [146], { terminals: 'hv-three', radiatorBanks: 2, ladder: false, drive: true, offsetConservator: true }, 'Три высоких ввода, расширитель смещен в плане относительно их ряда; наружный привод и радиаторы.'),
  'tr26-hv-three': hv('ТМН 110 кВ с тремя высокими вводами', [147], { terminals: 'hv-three', radiatorBanks: 2, ladder: true, drive: true }, 'Три высокие вводные колонны на баке, боковые радиаторы, расширитель и лестница. Только общая наружная схема.'),
  'tr26-hv-three-winding': hv('ТМТН 110 кВ с дополнительным рядом вводов', [150], { terminals: 'hv-three-row', radiatorBanks: 2, ladder: true, drive: true }, 'Три высоких ввода и дополнительные малые группы по плану, наружный привод, расширитель и боковые панели.'),
  'tr26-hv-tdn-10': hv('ТДН 110 кВ с панельным охлаждением', [152], { terminals: 'hv-three', radiatorBanks: 2, ladder: true }, 'Высокие вводы, расширитель, лестница и панельное охлаждение; вентиляторы не видны и не добавлены.'),
  'tr26-hv-tdn-16': hv('ТДН 110 кВ с одноярусным обдувом', [153], { terminals: 'hv-three', radiatorBanks: 2, fans: 1, ladder: true, wide: true }, 'В торцевом виде видны по одному вентилятору сбоку, три высоких ввода и торцевой расширитель.'),
  'tr26-hv-tdtn-10': hv('ТДТН 110 кВ с тремя рядами выводов', [155], { terminals: 'hv-three-row', radiatorBanks: 2, ladder: true, wide: true }, 'На плане три электрически разные группы верхних выводов; показаны только внешние вводы, бак и охлаждение.'),
  'tr26-hv-tdtn-16': hv('ТДТН 110 кВ с двухъярусным обдувом', [156], { terminals: 'hv-three-row', radiatorBanks: 3, fans: 2, fanSides: [1, 2], ladder: true, wide: true }, 'Три группы вводов и радиаторы с асимметричным обдувом: один вентилятор с одной стороны, два с другой по торцевому виду.'),
  'tr26-power-low-profile': hv('Низкопрофильная сборка ТДН с торцевым расширителем', [158], { terminals: 'six-low', radiatorBanks: 2, ladder: true }, 'Все вводы короткие в сравнении с баком; высокие колонны 110 кВ не заимствованы из других страниц.'),
  'tr26-power-tds': hv('Сборка ТДС с низкими вводами и широким баком', [160], { terminals: 'six-low', radiatorBanks: 3, ladder: true, wide: true }, 'Широкий бак, малые верхние вводы, расширитель и наружные панели по фасаду и плану.'),
  'tr26-panel-low-voltage': hv('Панельный ТМ 10 кВ с низкими вводами', [163], { terminals: 'six-low', radiatorBanks: 3, ladder: false }, 'Короткие верхние вводы, цилиндрический расширитель и панельное охлаждение; отдельный контур от высоковольтных сборок.'),
  'tr26-panel-lv-seven': hv('Панельный ТМ с семью выводами НН', [126], { ladder: false }, 'Три ввода ВН и семь малых контактных выводов НН, три панельных блока на каждой стороне по плану страницы 126.'),
  'tr26-panel-conservator-offset': hv('Панельный ТМ с асимметричными группами охлаждения', [131, 137], { ladder: false }, 'Три радиаторных блока с одной стороны и два справа на противоположной стороне, два ряда по три ввода и торцевой расширитель.'),
  'tr26-panel-conservator-balanced': hv('Панельный ТМ с тремя блоками на каждой стороне', [133, 139], { ladder: false }, 'Три радиаторных блока на каждой длинной стороне по плану; отличается от расположения 3/2 на страницах 132/138.'),
  'tr26-hv-three-wide': hv('ТМН 110 кВ с асимметричными четырьмя и тремя радиаторами', [148], { ladder: true, drive: true }, 'Три высокие колонны, дополнительный низкий ввод, четыре радиаторных блока с одной стороны и три с другой по плану страницы 148.'),
  'tr26-panel-low-voltage-balanced': hv('ТМ 10 кВ с тремя радиаторами на каждой стороне', [164], { ladder: false }, 'Три отдельных радиаторных блока на каждой длинной стороне; схема 3/2 страницы 163 не переносится на этот чертеж.'),
});
export const transformer2026TypeIds = Object.freeze(Object.keys(transformer2026Types));
export const resolveTransformer2026Type = type => Object.hasOwn(transformer2026Types, type) ? type : null;
