import { test, expect } from '@playwright/test';
const api = process.env.E2E_API_URL || 'http://localhost:8000/api/v1';
async function signIn(page, email = 'catalog@demo.example') {
 await page.goto('/login?next=/admin/catalog');
 await page.getByLabel('Email').fill(email);
 await page.getByLabel('Пароль').fill('ChangeMe123!');
 await page.getByRole('button', { name: 'Войти', exact: true }).click();
}
async function apiSession(request) {
 const response = await request.post(`${api}/auth/login`, { data: { email: 'catalog@demo.example', password: 'ChangeMe123!' } });
 expect(response.ok()).toBeTruthy();
 const token = await response.json();
 return { Authorization: `Bearer ${token.access_token}` };
}
test('anonymous and tenant administrators cannot edit the platform catalog', async ({ page }) => {
 await page.goto('/admin/catalog');
 await expect(page.getByRole('link', { name: 'Войти', exact: true })).toBeVisible();
 await signIn(page, 'admin@demo.example');
 await expect(page.getByRole('heading', { name: 'Нет доступа к управлению каталогом' })).toBeVisible();
 await expect(page.getByRole('button', { name: 'Добавить товар +' })).toHaveCount(0);
});
test('create, reload, edit price, compare, select, hide and restore persist through real API', async ({ page, request }) => {
 const key = `e2e-admin-${Date.now()}`;
 await signIn(page);
 await expect(page.getByRole('heading', { name: 'Товары и цены' })).toBeVisible();
 await page.getByRole('button', { name: 'Добавить товар +' }).click();
 await page.getByLabel('Название', { exact: true }).fill(`E2E persistent ${key}`);
 await page.getByLabel('Постоянный ID').fill(key);
 await page.getByLabel('Артикул / обозначение').fill(key);
 await page.getByLabel('Видимость', { exact: true }).selectOption('published');
 await page.getByLabel('Цена', { exact: true }).selectOption('fixed');
 await page.getByLabel('Валюта ISO').fill('USD');
 await page.getByLabel('Сумма', { exact: true }).fill('1250.10');
 await page.getByRole('button', { name: 'Сохранить в базе' }).click();
 await expect(page.getByText('Товар сохранён в базе.', { exact: true })).toBeVisible();
 await page.reload();
 await page.getByLabel('Поиск', { exact: true }).fill(key);
 await page.getByRole('button', { name: 'Найти', exact: true }).click();
 await expect(page.getByRole('cell', { name: '1250.10 USD', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'Изменить', exact: true }).click();
 await page.getByLabel('Сумма', { exact: true }).fill('1500.25');
 await page.getByRole('button', { name: 'Сохранить в базе' }).click();
 await expect(page.getByRole('cell', { name: '1500.25 USD', exact: true })).toBeVisible();
 const published = await request.get(`${api}/catalog/products/${key}`);
 expect(published.ok()).toBeTruthy();
 const product = await published.json();
 expect(product.price).toBe('1500.25'); expect(product.version).toBe(2);
 await page.goto(`/catalog/${key}?source=api`);
 await expect(page.getByRole('heading', { name: '1500.25 USD', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'В подборку +', exact: true }).click();
 await page.goto('/selection?source=api');
 await expect(page.getByRole('link', { name: `E2E persistent ${key}`, exact: true })).toBeVisible();
 await page.reload();
 await expect(page.getByText('1500.25 USD', { exact: true })).toBeVisible();
 await page.goto(`/catalog/compare?source=api&ids=${key},tmg-400`);
 await expect(page.getByRole('cell', { name: '1500.25 USD', exact: true })).toBeVisible();
 const headers=await apiSession(request);
 const hidden=await request.post(`${api}/admin/catalog/products/${product.id}/hide`,{headers,data:{version:2}});
 expect(hidden.ok()).toBeTruthy();
 expect((await request.get(`${api}/catalog/products/${key}`)).status()).toBe(404);
 await page.goto('/selection?source=api');
 await expect(page.getByText('Товар больше не опубликован. Он исключён из скачиваемой подборки.')).toBeVisible();
 await page.goto('/admin/catalog');
 await page.getByLabel('Поиск', {exact:true}).fill(key); await page.getByRole('button',{name:'Найти',exact:true}).click();
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Восстановить',exact:true}).click();
 await expect(page.getByRole('cell',{name:'Черновик',exact:true})).toBeVisible();
 expect((await request.get(`${api}/catalog/products/${key}`)).status()).toBe(404);
});
test('dirty cancel and stale-save conflict preserve local draft without overwriting server', async ({ page, request }) => {
 const headers=await apiSession(request),categories=await (await request.get(`${api}/admin/catalog/categories`,{headers})).json();
 const key=`e2e-conflict-${Date.now()}`;
 const created=await request.post(`${api}/admin/catalog/products`,{headers,data:{public_key:key,slug:key,category_id:categories.items[0].id,translations:{ru:{name:key}},status:'draft'}});
 const product=await created.json(); expect(created.status()).toBe(201);
 await signIn(page);
 await page.getByLabel('Поиск',{exact:true}).fill(key);await page.getByRole('button',{name:'Найти',exact:true}).click();
 await page.getByRole('button',{name:'Изменить',exact:true}).click();
 await page.getByLabel('Название',{exact:true}).fill('Local unsaved draft');
 page.once('dialog',dialog=>dialog.dismiss());
 await page.getByRole('button',{name:'Отмена',exact:true}).click();
 await expect(page.getByLabel('Название',{exact:true})).toHaveValue('Local unsaved draft');
 const changed=await request.patch(`${api}/admin/catalog/products/${product.id}`,{headers,data:{version:1,translations:{ru:{name:'Server winner'}}}});expect(changed.ok()).toBeTruthy();
 await page.getByRole('button',{name:'Сохранить в базе'}).click();
 await expect(page.getByRole('alert')).toContainText('Товар уже изменён');
 await expect(page.getByLabel('Название',{exact:true})).toHaveValue('Local unsaved draft');
 await expect(page.getByRole('button',{name:'Сохранить в базе'})).toBeDisabled();
 const saved=await (await request.get(`${api}/admin/catalog/products/${product.id}`,{headers})).json();expect(saved.translations.ru.name).toBe('Server winner');
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Загрузить актуальную версию'}).click();
 await expect(page.getByLabel('Название',{exact:true})).toHaveValue('Server winner');
});
